### ISSUE TITLE
変数に格納してから返す意図について

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#100]
関数において、一旦変数に代入してから値を返す書き方をしている箇所が多いですが、どのような意図があるのでしょうか？

**Comment by kujirahand** [comment]
特に意識していませんが、プログラムの読みやすさ・わかりやすさを優先するとき、そうする場合があります。

**Comment by massongit** [comment]
ちょっと気になったので聞いてみました。
ありがとうございます。
