### ISSUE TITLE
配列orOjbjectの要素から配列を記述する際に明示的な()が必要

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#1000]
以下のBが動かないのですが、以前は動いていたような気もします。Cのように個々に()が必要です。
※配列(A[1])ではなくプロパティアクセス(A["AAA"])も同様。
```
Aは[1,2,3]
「A={A}」を表示
Bは[A[1], A[1], A[2]]
「B={B}」を表示
Cは[(A[1]), (A[1]), (A[2])]
「C={C}」を表示
```
変数の整理に配列やオブジェクト(ハッシュ変数)を使ってまとめているとはまります。特に、描画系で位置やサイズを要素２や要素４の配列で渡したいケース。

**Comment by kujirahand** [comment]
「変数@A,B」の形式で二次元配列変数にアクセスできるように
#976 の対応が不完全でした。修正します。
