### ISSUE TITLE
「・・・には・・・ここまで」構文が「ここまで」で閉じられていなくてもエラーにならない

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1045]
これです。
https://nadesi.com/cgi/kaizen3/index.php?m=thread&threadid=6
（どっちに書いた方がいいのかなやむー）

**Comment by kujirahand** [comment]
両方にありがとうございます！

改善掲示板の方はGitHubアカウント無い方用に作ったものです。GitHub英語で怖いという感じありますし（＾＾

もし、改善掲示板に書いてくださった投稿は、必要に応じてこちらに書き写して作業しようと思っています。コミットログがたどりやすくなりますので😆

**Comment by kujirahand** [comment]
『には』の他に、『回』『繰り返す』『エラー監視』も『ここまで』チェックをしていませんでしたので修正します。

**Comment by snowdrops89** [comment]
ありがとうございます！！
では、こちらに書くようにします☆
そう・・・キホン英語だけのページが開いたら、キャッと言って閉じちゃうような人なので、アカウント作るのも大変大変でしたwww
でも、おかげさまで、色々賢くなってる☆

**Comment by kujirahand** [comment]
@snowdrops89  さん。おぉ、素晴らしいです！
これからもよろしくお願いします。
