### ISSUE TITLE
demoにある外部ライブラリを直接リポジトリに配置しないようにする

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#1051]
`demo` ディレクトリ以下には外部のライブラリ由来のファイルが配置されています。
デモ実行時に外部へのアクセスを減らしたいというのが理由ですが ( https://github.com/kujirahand/nadesiko3/issues/864 )、リポジトリ内に直接配置してあると、意図せずファイルを書き換えてしまう可能性があるので、直接配置せずに済む方法を検討すると思います。

<方法案>
* demo内にpackage.jsonを設け、ライブラリをnpmでインストールするようにする
* git submoduleで各ライブラリのリポジトリを紐づける

**Comment by kujirahand** [comment]
こちらですが、git submoduleやnpmでインストールすると、ものすごいたくさんの不要ファイルをダウンロードすることになります。

そこで、npm start した時に、ファイルが存在しなければ、ミニマイズされた最低限ファイルのみダウンロードする簡単なスクリプトを作りたいと思います。

**Comment by kujirahand** [comment]
必要なファイルだけ extlib にダウンロードするように修正しました。

ただし、現状だと curl コマンドが必要なので、cnako3 に #1053 のAJAX受信を実装して !非同期モードに置き換えるようにします。

**Comment by kujirahand** [comment]
なでしこだけで完結するように修正しました。この件閉じます。
@massongit さん、良い提言ありがとうございました。
引き続き、#1054 で少しずつ対応していきます。
