### ISSUE TITLE
対応ブラウザ一覧取得がエラーになります

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1069]
ちょっとたまたま気がついたのですが、「対応ブラウザ一覧取得」をすると、
```
エラー『ReferenceError: process is not defined』が発生しました。
```
なるエラーになってしまいます。

ちなみに、v3.1.23からのようです。v3.1.21では動きました。
結構前からでしたね。

**Comment by kujirahand** [comment]
`webpack.config.js`で対応ブラウザ一覧を取り込むようになっているのですが、これがうまく動いていない用ですね。ビルドプロセスが正しく動いているか必要がありそうです。

```
class CanIUseDBDataReplacementPlugin
...
```

**Comment by kujirahand** [comment]
修正完了です。
