### ISSUE TITLE
変数のスコープに関して

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#108]
あるブロック内で初めて使用された (宣言された) 変数は、そのブロック内でのみ有効にする (ブロックを抜けたら使えなくする) とプログラミングしやすいかと思います。

**Comment by kujirahand** [comment]
うっかり、コメントし忘れていましたが、「＊＊とは変数」と書くと、ローカル変数を作れます！

- https://nadesi.com/doc3/go.php?26
