### ISSUE TITLE
全角文字列で単置換が動作しない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1105]
https://nadesi.com/cgi/kaizen3/index.php?logid=61&m=log

以下はうまく動くが。。。

```
「e,f,g」の「,」を「-」へ単置換して表示。
```

以下はうまく動かない。

```
「番号0000」の「0000」を「0001」に単置換して表示 //番号0000と表示される
```

修正する。

**Comment by weyk** [comment]
同じ仕組みで実装されている「出現回数」も上手く動いていないようです。
内部での最初の置換後が、「\0」の特殊文字の扱いになってしまい「0」とは一致しません。
「\」以外に単に「\」を付けるのは危険なようです。かなりの数の特殊文字があります。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes

**Comment by kujirahand** [comment]
ご報告ありがとうございます。すぐ修正します。
