### ISSUE TITLE
非同期モードで変数スコープが混ざる

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#1110]
非同期モードで実行中の時、非同期な事象(秒待機や、DOMイベント)が重なると
変数スコープが混ざる。
追ってつなげます。

**Comment by weyk** [comment]
PRのdraftで出しました。

非同期モードでの動きが変わるため、非同期モードで動く命令も変更が必要です。
・非同期モードで同期化する際の処理が変わり、分離され複数有るどのスタックに戻るか判るようにする必要がある。
・同期化しないコールバックについて、変数を操作してスタックを分離するように指示する必要がある。
※結果的に、コールバックする部分の大半です。命令から同期的にコールバックされて命令の終了したらコールバックも呼ばれなくなるタイプのものだけ不要です（Array.forEach()とか)

特に、変数スコープが混ざらないようにするためには、変数のスタックを分離が必要となるコールバックの呼び出しに対応が必要となるので、出来る限りは対応しても、完全に対応させるのは難しいかかもしれません。
例えば、各イベントのコールバック全般や、requestAnimationFrame、秒後、秒毎、などがあります。
基本的には、コールスタックをさかのぼったときに、なでしこのメインループにたどり着けるならば、分離不要となるはずですが、自動的に軽量に判定する方法が思いついていません。

また、テストの未追加です。動作の際は、秒待機を含んだクリックした時のボタンを作って、複数回クリックして確認していました。

なお、スタックを混ぜない方法として、「混ざらず安全に並行して処理が流せる」方法のため、ユーザが正しく処理をコントロールできるかも一考が必要かも。Javascriptの本来のシングルスレッド故の簡単さから少し離れる感じがします。

**Comment by kujirahand** [comment]
こちら、遅くなってすみません、ありがとうございます。
マージしました！！
