### ISSUE TITLE
ファイルローカルな変数が持ちたい。

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#1112]
いろいろ考えててみたもののうまく行かないので備忘かねて。

ここでのターゲットは「ファイルローカルな変数が持ちたい。」です。

いくつかの理由で、大きなプログラムを作成するのが難しいです。
・nakoファイルから、nakoファイルを「取り込む」とユーザ関数とグローバル変数はすべて共有化されるためモジュール化の手法としては使えない。
・無名関数が定義場所のローカルスコープを見ることができず値のやり取りにグローバル域が必要になる。
・グループ(ClassやMethodをもつObject)がなく、カプセル化が困難。

そこで、以下のルールでASTを変換することで、上記のうちの「取り込む」が行われた場合にファイルをまたがないスコープの変数が使えるようにならないか　と考えています。
・変数でもユーザ関数でもグローバルになるもの(vars[1],vars[2]に格納されるもの)の先頭に「_」を付けたものが対象。
　ローカル変数の先頭に「_」を付けるのは禁止する（混乱・記述ミス防止。他のファイルの同名のファイルスコープ変数からのご認識防止）
・ASTからgenerateされる前にファイル名毎に割り振った文字列を前に付加する。
　「_ワーク」が「A_ワーク」のように。
　長くてもいいなら、ファイル名がわかりやすそう。
・取り込みがおこなれない場合、名称の置換はされてもされなくても動く（「_AAA」は「_AAA」のままでも動く）
・これにより、「main.nako」とそこから取り込まれている「sub1.nako」と「sub2.nako」で、同じ「_ワーク」というグローバル変数が合った場合でも、その３つは、独立した変数になる。
　例えば、コンパイル後は「A_ワーク」「B_ワーク」「C_ワーク」とか「main_ワーク「sub1_ワーク」「sub2_ワーク」になる。
・ユーザ関数名を文字列で渡す命令は記述方法の変更が必要（関数の参照を直接渡したい）

もともと、ファイル分割したいなぁと思ったのは、expressを利用したプログラムの作成です。
マウント毎にファイルを分割して、個別のファイルにすると考えた場合、同じ変数名や関数名が頻出する可能性が高そうなため。

**Comment by kujirahand** [comment]
いよいよモジュールの実装の時間が来ましたね！

取り込みが行われる場合に、変数名の前にファイル名を付けるのが良さそうですね。
なでしこv1のように「ファイル名::変数名」のようにアクセスできるようにすると良いでしょうか。

変数名の管理をモジュールを含めた木構造にすると良いかもですね。もともと、変数の検索を行う時、以下のように呼び出し元の関数の変数も参照できるように実装していたのですが、現状「ローカル→グローバル→システム」と三つ検索するだけになっています。

> ローカルスコープの変数 → 呼び出し元の関数の変数 → その呼び出し元の関数の変数 → グローバル変数 → システム変数

これが、  #932 が動かない理由でもあるのですが。。。

また、現在、外部依存ファイルの取り込み処理も、かなり複雑になっているので、一度、モジュールシステム導入と同時にスッキリさせたいところです。

**Comment by kujirahand** [comment]
結局、[weyk](https://github.com/weyk)さんの案が秀逸だったので、
「`モジュール名__変数名`」として解決するように修正しました。

**Comment by kujirahand** [comment]
現状、モジュール名がうまく解決できていない問題が発覚！
