### ISSUE TITLE
Plans for Nadesiko v3 and v1?

### ISSUE THREAD

**Issue by nobodxbodon** [kujirahand/nadesiko3#1130]
你好，眨眼间 [上次交流](https://github.com/kujirahand/nadesiko3/issues/238) 已是四年前了。再次恭喜 Nadesiko 语言入选中学教科书！

从 [这里](https://nadesi.com/top/index.php?%E3%81%AA%E3%81%A7%E3%81%97%E3%81%93%E3%81%8C%E6%95%99%E7%A7%91%E6%9B%B8%E3%81%AB%E8%BC%89%E3%81%A3%E3%81%9F%E4%BB%B6) 看到，教科书中使用的是 v1（Windows版）。而 [这里](https://www.eznavi.net/site/press/index.php?site=20211013) 的意思是 v3 可以用于大学入学考试吗？

请问对这两个版本分别有何计划呢？比如有哪些功能需要增强或修改？

**Comment by nobodxbodon** [comment]
感谢您的回复！我刚看到 [v3 和 v1 的对比介绍](https://nadesi.com/doc3/index.php?%E3%81%AA%E3%81%A7%E3%81%97%E3%81%93v1%E3%81%A8%E3%81%AE%E4%BA%92%E6%8F%9B%E6%80%A7)。请问教科书中的抚子语言例程都可以在 v3 中运行吗？

今天还看了 [DNCL 与抚子语言的比较](https://www.eznavi.net/index.php?site=ez20210407)，并冒昧地向 [望月先生](https://twitter.com/EZNAVInet) 请教了一个简单的抚子语言问题。因为以前没听说过 DNCL，请问哪里有 DNCL 的详细介绍呢？

另外，在抚子语言用于中学教学之后，对 v3 的开发计划有哪些影响呢？个人感觉对新手来说报错信息很重要，而很多市面上的编程语言的报错信息都难以被新手理解。不知是否有这方面的用户反馈呢？

**Comment by nobodxbodon** [comment]
抱歉！刚刚在 [这份文档末尾](https://www.eznavi.net/site/press/eznavi/img/2021/20211013-0.pdf) 找到了 DNCL 的文档链接。

**Comment by kujirahand** [comment]
我Close这个Issues. 谢谢。
