### ISSUE TITLE
関数の中で日数差などを使うと引数もローカル変数も全部グローバルになっちゃう（？）

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1131]
**再現方法：**

```
Ａ＝「2022/1/1」
Ｂ＝３０。

Ａを表示。#2022/1/1
Ｂを表示。#30

「2022/12/31」でテスト。

Ａを表示。#2022/12/31
Ｂを表示。#50

●(Ａで)テスト
    変数 Ｂ＝５０。
    //今日と昨日の「日」による日時差。
    今日と昨日の日数差。
ここまで。
```

　日数差の処理とは無関係の変数も変わってしまうというナゾ現象です。
　時間差とかも同様なんですが、日時差だけは大丈夫でした。

**Comment by weyk** [comment]
2021/02/14ごろの変数の展開　の修正のタイミングで外側のスコープ(グローバル変数)の__varsをユーザ関数内のローカル変数を見るつもりで参照する組み合わせができてしまったっぽいです。
ユーザ関数内でpureでは無い命令を使用してる場合にスコープが混ざります。

**Comment by kujirahand** [comment]
久々に生成されたコードを見たら、かなり複雑になっていますねー。読み解くだけで大変ですね。
もう少しシンプルにコード生成できると、この手の問題を修正しやすくなりますね。

**Comment by kujirahand** [comment]
スコープの問題を直すと「ナデシコする」が動かなくなるのですが、ローカルスコープが壊れるのが問題なので、とりあえず、ナデシコするの解決は後回しにして、ローカルスコープの問題を修正します。
こちらは別件であげます。
