### ISSUE TITLE
生成されるコードがカオスすぎる問題

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1134]
altJSならではの問題ながら・・・
生成されるコードがカオスすぎるので、オプションを整理しつつ改めて生成されるコードをある程度読みやすくする。

**Comment by weyk** [comment]
既定のオプションでの生成で読みづらいjavascriptが生成される要因の１つが、undefinedの引数・戻り値チェックです。
オプションの変更含めると、パフォーマンスモニタの呼び出し回数・呼び出し時間の測定もかなり混沌が注入されます。
上記2つは今は実行速度最優先で必要な箇所それぞれに全体が展開しています（共通関数を準備して利用等をしていない）
あとは、「それ」対応と、非pure関数のための対応部分ぐらいですが、このための処理があると知ってさえいれば読める範囲と思います。

元々の読みづらさというか、わかりにくさとしては、
・解析時のthis（nako_genかnako_compiler?)の持つ__varslistや__vars（nako_genにかかれているコード）
・実行時のthis(nakoGloal)の持つ__varlistや__vars（nako_genにてcodeとして文字列で生成されるコード）
を行ったり来たりする点でしょうか。

**Comment by kujirahand** [comment]
@weyk さん、フォローありがとうございます。
続きは #1134 で改善したいと思います。
ありがとうございます！
こちらは閉じます。
