### ISSUE TITLE
テーブル作成命令を使うとDOM親要素がテーブルになってしまう

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1177]
タブン、tableタグを親要素にしてそこへtrとかtdを追加しているんだと思うのですが、その後DOM親要素がそのままテーブルのままになっているようで、テーブル作成した後に普通に他の部品を作ろうとすると、テーブルの中に入っちゃいます。
　自分でDOM親要素設定すればだいじょぶなんですが、最初は必ずアレ？！ってなると思いますし、いちいちテーブル作成前に今のDOM要素を覚えておいて作成後に元に戻すというのも手間なので、できればDOM親要素を元にもどして終了してくれるとよいと思います。
```
親＝DOM親要素。
表＝「名前,年,性別
うさこ,11,♀
うさまる,6,♂」のテーブル作成。

「いろはにほへとちりぬるを・・・」のラベル作成。
親にDOM親要素設定。
「いろはにほへとちりぬるをわかよたれそつねならむ・・・」のラベル作成。
表の「ボーダー」に「solid」をDOMスタイル設定。
```

**Comment by kujirahand** [comment]
修正しました！報告感謝！
