### ISSUE TITLE
貯蔵庫エディタで非同期モードが動かない

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1186]
```
!非同期モード
3回繰り返す
　　「{回数}: 探すのに時があり」と表示。
　　1秒待機。
　　「{回数}: 諦めるのに時がある」と表示。
　　1秒待機。
ここまで。
```
を、貯蔵庫エディタで実行しようとすると、
```
[実行時エラー]main.nako3(0行目): エラー『非同期モードでは「ナデシコ続」は利用できません。』が発生しました。
```
と、なります。
マニュアルの簡易エディタ２では動きます。

緩やかに利用が非推奨となっているみたいですが、ガッツリ使えなくなっております～。
そして、代わりの「秒待つ」ですが、これは関数の中では使えないものでしょうか？

```
時間表示
●時間表示
　5回
　　今を表示。
　　1秒待つ。
　ここまで。
ここまで。
```
とすると、
```
[実行時エラー]エラー『SyntaxError: await is only valid in async functions, async generators and modules』が発生しました。
```
となってしまいます～。
もしこれが仕様だとするとだいぶ不便です。
非同期モードでは、出来ましたので。

**Comment by kujirahand** [comment]
貯蔵庫で非同期モードが動かない問題は、以前から報告が上がっているのですが、なかなか原因が掴めずの状態なんです。

#1113

後半の「秒待つ」の問題は、#1154 で修正済みと思います。
とりあえず、これから、バージョンアップします！

**Comment by kujirahand** [comment]
あれれ、バージョンアップしても、だめですね。。。
コマンドラインcnako3だと問題ないのですが。。。

**Comment by kujirahand** [comment]
#1190 で修正します。

**Comment by snowdrops89** [comment]
秒待つ出来ました！
ありがとうございます☆
そして、非同期モードが動かない件は既出だったんですね。気付きませんでした･･･(/ω＼)
とゆうわけで、こっちは閉じます～。
