### ISSUE TITLE
マニュアルにplugin_browserの命令が表示されていない

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1195]
なぜかそこだけ空欄になっております～。
https://nadesi.com/v3/doc/index.php?wnako&show

かな順の一覧などにも表示されていないようです。
個別の命令は、リンク先が分かれば開くのですが、上のカテゴリとか引数とかの書かれている表？は出てこないみたいな（？）
https://nadesi.com/v3/doc/index.php?plugin_browser%2F%E7%94%BB%E9%9D%A2%E6%9B%B4%E6%96%B0%E5%87%A6%E7%90%86%E5%8F%96%E6%B6%88&show

**Comment by kujirahand** [comment]
こちら修正しました！
ご報告に感謝です！
