### ISSUE TITLE
呼び出した関数の中の秒待つが待たれない（？）

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1209]
以前の、関数の中で使えないのとはベツの現象です。
　こんな感じです。
```
x＝0。
１０回
　x=x+10。
　[x,10]へ遅延描画。
ここまで。

●(XYへ)遅延描画
　　XYへ2の円描画。１秒待つ。
ここまで。
```
　これは、3.3.4までは1秒おきに●が描かれていたのですが、現在は一瞬で全部描画されてしまいます。
　このコードだけのことならば、遅延描画関数の中で秒待つせずに、ループの中で秒待つすればいいだけなんですけれど、何かと不都合が・・・

**Comment by kujirahand** [comment]
v3.3.10で修正しました！

**Comment by snowdrops89** [comment]
ありがとうございました☆
正常動作確認しました！
