### ISSUE TITLE
グローバルの配列とローカル変数のナゾ現象

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1213]
ちょっとどういったアレかよく分からないので、題が分かりづらくてスミマセン。
　例えば・・・
```
変数 A＝空配列。

B＝[10,20,30]
Bでテスト

●(Aで)テスト
    Aを表示。# 10,20,30
    A[0]を表示。A[1]を表示。A[2]を表示。# 10 20 30
ここまで。
```
　今回の修正で、コレは問題なく実行出来るようになりました。
　が！
```
変数 A＝空配列。

B＝[10,20,30]
Bでテスト

●(Aで)テスト
    Aを表示。# 10,20,30（ここでは正しい）
    もし(A[0]=10)かつ(A[1]=20)ならば、はいを表示。
    違えば、いいえを表示。# 0が表示される（えっ！）
    A[0]を表示。A[1]を表示。A[2]を表示。# undefined　undefined　undefined　（えーっ？！）
ここまで。
```
　とゆう感じです・・・
　これは、グローバルでAを宣言していなければ起こりません。
　3.3.4までは大丈夫でした。

**Comment by kujirahand** [comment]
配列でも1つの参照ならOKで、2つだとNGという非常にレアケースな問題、ご報告ありがとうございます。

内部の配列参照でスタックを参照しているのですが、スタックをポップするときに、なぜかローカル変数の管理オブジェクトを初期化しているようでした。修正しました。

**Comment by snowdrops89** [comment]
ありがとうございます！！
動くようになりましたﾟ+.ヽ(≧▽≦)ﾉ.+ﾟ
