### ISSUE TITLE
ＤＯＭ部品の作られる場所が変です

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1237]
貯蔵庫でｖ3.3.27にすると、作成したDOM部品が一番下に表示されます。
タブンDOM親要素が「nako3_div」に設定されてなくてbodyかなんかになっているんじゃないかと思います。
そして、単に表示する場所が違うせいかなと思いますが、クリアや再実行をしてもクリアされずにどんどん追加で作成されるようです。

**Comment by kujirahand** [comment]
確かに。以下を実行するとDOM親要素が空っぽなので、DOM親要素設定が動いていないようです。。。

```
描画中キャンバス["id"]を表示
DOM親要素["id"]を表示
```

**Comment by kujirahand** [comment]
理由が判明。理由は、JS実行で引数のsysがなかったから。。。
https://github.com/kujirahand/nadesiko3core/commit/590cc1b0310d47cd3cbe98226d7c4ac71824c800
でcoreを修正。

**Comment by kujirahand** [comment]
v3.3.31にアップしたところ上記のサンプルOKでした。
貯蔵庫も、v3.3.31 にすると直りました。

**Comment by snowdrops89** [comment]
v3.3.31で修正確認しましした☆
寝て起きたらなおってた！
素早い対応ありがとうございます❤
