### ISSUE TITLE
DOM親要素が再び空です～

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1246]
#1237 の再来とおもわれ。

```
"CV="&描画中キャンバス["id"]を表示
"DOM="&DOM親要素["id"]を表示。
[50の乱数,50の乱数,50の乱数,50の乱数]へ四角描画。
「OK」のボタン作成。
```
　貯蔵庫でv3.3.50を指定した場合。（win版はまだためしてないのですが）

**Comment by kujirahand** [comment]
1fcb9b2fddbcd1241e625f5be173fe1f4500e7aa
で修正しました！

**Comment by snowdrops89** [comment]
なおってるの確認しました！　ありがとうございます☆
おぉ～、同じ現象に見えて、原因違うってあるんですねーｗ（゜ｏ゜）ｗ
