### ISSUE TITLE
NAKOワーカーが使えなくなっているような？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1249]
使い方自体よく分かっていないのでアレですが；
マニュアルのサンプルを実行すると、`[エラー]no message`となります～。
https://nadesi.com/v3/doc/index.php?%E6%96%87%E6%B3%95%2FNAKO%E3%83%AF%E3%83%BC%E3%82%AB%E3%83%BC&show

貯蔵庫エディタでは、エラーも出なくて、うんともすんともいわないような・・・💦
v3.2.51では大丈夫で、v3.3.2では、`[エラー]ReferenceError: require is not defined`が出ますので、ESModule化で色々変わったためのナニカなのかもですが、v3.3.49からはなぜかエラーもでなくなってしまったのでした。

**Comment by kujirahand** [comment]
貯蔵庫では動くようになりました。
しかし、v3/doc ではセキュリティエラーが出ます。
再度確認します。
https://nadesi.com/v3/doc/index.php?%E6%96%87%E6%B3%95%2FNAKO%E3%83%AF%E3%83%BC%E3%82%AB%E3%83%BC&show

**Comment by kujirahand** [comment]
上記のセキュリティエラーですが、ブラウザによるセキュリティの問題なので、簡単には直せそうにありません。v3/docにもワーカーを配置すれば動くようですが、リソースが分散してしまうので、マニュアル側に、貯蔵庫で試すように注記を入れました。
本Issueは閉じます。
