### ISSUE TITLE
ループで秒待つを使った場合、エディタでクリアや再実行をしてもループが動き続けてしまうようです

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1285]
https://n3s.nadesi.com/id.php?1627
他の方の作品なんですけれどね。なんでバグるのかしらと思ってみてみたら、そうゆうことのようでした。
一回目の無限ループが動いたまま、二回目のループも動いてしまう。

**再現方法**
　１０秒以内に実行ボタンを二回以上押したりクリアしてみる。
```
C=0
C<10の間
　Cを表示。
　C=C+1。
　1秒待つ。
ここまで。
```

秒毎、秒タイマーを使えば大丈夫なのですが、秒待つがイイ感じに使えるようになった今、特にｖ１からの方は、この書き方馴染みがありますよねー。

**Comment by kujirahand** [comment]
こちら、報告ありがとうございます。
JSのawaitを使ったコードで、クリアボタンを押した時に、promise内のsetTimeout関数がクリアされない問題です。

以下のコードが問題の箇所。
https://github.com/kujirahand/nadesiko3core/blob/467761fe870ebe36a71e4e0dc809f87e6a82cb01/src/plugin_system.mjs#L2136

「秒後」と同じように、timerIdをsys.__timeoutに追加すれば直りそうです。

**Comment by snowdrops89** [comment]
なおりましたの確認しました！
ありがとうございます☆
