### ISSUE TITLE
「AからBまで繰り返す」でBからAまでも実行してしまう問題

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1351]
たぶん、AからBまで繰り返すで、A>Bの場合が考慮されていないかと。

```
「なでしこv3」開発掲示板への書き込み:
[URL] https://nadesi.com/cgi/kaizen3/index.php?logid=194&m=log
tomo さんより
このような多重ループを書きました。
n=3
kを0からn-1まで繰り返す。
　jをk+1からn-1まで繰り返す。
　　「k:{k}, j:{j}」を表示する。
　ここまで。
ここまで。

結果は
k:0, j:1
k:0, j:2
k:1, j:2
k:2, j:3
k:2, j:2
となりましたが、k=2,j=3とk=2とk=2は条件を満たさないのに表示されています。
CやJavascriptでも確認しましたが最後の2つは表示されません。
```

**Comment by snowdrops89** [comment]
えっ、でもこれは、なでしこ的には正しいのではないでしょうか。
なでしこでは、ｖ１の時から、逆順での繰り返しが普通に出来ました。
「数を３から０まで繰り返す」でカウントダウンが出来る仕様です。

Javascriptのコードで最後の二つが表示されないのは、第二引数に「j=<n-1」、jがn-1以下とゆう条件式を与え、第三引数に,
「j++」で１こずつ増える、とゆう式を与えているからですが、なでしこの場合は純粋にAの数からBの数までで、第二引数は条件式ではないし、いくつずつ増減するかを設定する引数は無いので、このコードで最後の２つの時には、Aが3、Bが2となり「jを3から2まで繰り返す」が普通に実行されているだけで、何の問題も無いと思うんです。

でも、「Nずつ増やし(減らし)繰り返す」文が新しく出来たんですが、「数を3から0まで1ずつ増やし繰り返す」としても、普通に減っていきますよねー・・・。ステップ値が設定できるだけで、増やす、減らすは、実際にはどっちでも良いというか（？）
何かJavascriptのfor文と同じように書ける繰り返し構文があってもよいのかしら？　とは思わなくもないですが。
タブン、他の言語から移植しようとした時に、このように引っかかってしまったり、間文やもし文を併用しなければならずキレイに書けなかったりするんですよね？

**Comment by kujirahand** [comment]
そうですね！現行バージョンで問題なさそうなので閉じます！
ありがとうございました！！
