### ISSUE TITLE
配列連番作成の引数Bの助詞

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1370]
マニュアルの例文がエラーになっています

https://nadesi.com/v3/doc/index.php?plugin_system%2F%E9%85%8D%E5%88%97%E9%80%A3%E7%95%AA%E4%BD%9C%E6%88%90&show

引数Bの助詞が`まで`と`の`であるのに対し、`までの`を使っているせいですが、もしかしてサンプルのまちがいというより命令の方が`までの`にしたかったのに`まで`になっちゃってるのでは？　と言う気がしました。
違ってたらスミマセン。でも、「までの」のほうが自然な気がしたもので・・・

**Comment by kujirahand** [comment]
その通りです！！
`までの`を助詞に追加します。

**Comment by kujirahand** [comment]
v3.3.81で修正しました。閉じます！
