### ISSUE TITLE
『配列入替』を追加する

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1375]
https://twitter.com/snowdrops89/status/1599624927346589697

**Comment by snowdrops89** [comment]
あああ、なんかスミマセン。ありがとうございます！
内容的にはカンタンな処理なので無くて困るというアレではなかったのですが、ｖ１のつもりで書いてエラーなっちゃう率の高いヤツでした💧

**Comment by kujirahand** [comment]
なかなかv1の命令には追いつかないですねー。
とりあえず、追加しました！！

**Comment by kujirahand** [comment]
マニュアルを書く

**Comment by kujirahand** [comment]
https://nadesi.com/v3/doc/index.php?plugin_system%2F%E9%85%8D%E5%88%97%E5%85%A5%E6%9B%BF&show

**Comment by kujirahand** [comment]
マニュアルも書いた。
