### ISSUE TITLE
初心者ユーザー向けのインストーラーを用意する

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#140]
なでしこv1と同じように、エディタ、Node.js全部込みのパッケージを用意する。

また、ユーザーの作ったプログラムを簡単にパックして、配布できるようにする。

初心者ユーザーだと、Node.jsのインストールとコマンドラインによるライブラリインストールすらハードルが高いと思いますので。

**Comment by massongit** [comment]
#98
