### ISSUE TITLE
空白除去バッグ

### ISSUE THREAD

**Issue by luckasRanarison** [kujirahand/nadesiko3#1408]
文字例を空白除去してスペースが除去されていません

```
「　これ　は　おかしい　」を空白除去して表示
```
出力
```
これ　は　おかしい
```

**Comment by snowdrops89** [comment]
なでしこの「空白除去」命令は文字列の前後の余分な空白文字をトリムするための命令で、文字列中の空白文字については除去されません。
　文字列中の空白文字を全て除去したい場合には、「置換」命令などを使用して、空に変換すると良いと思います。

　・・・ということを、マニュアルに追記しました。
https://nadesi.com/v3/doc/index.php?plugin_system%2F%E7%A9%BA%E7%99%BD%E9%99%A4%E5%8E%BB&show

**Comment by luckasRanarison** [comment]
すみません、そういうことがマニュアルに記載されてるのが知りませんでした(なでしこの文法しか読みませんでした)、エディターでたまたまにその関数を見つけて誤解しました。
ちなみに私は日本人じゃないですけどなでしこは本当に面白いと思います :)
