### ISSUE TITLE
プラグインを取り込んでサンプルで使われている変数を宣言すると、二重定義はできませんとなります。

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1409]
このようなプラグイン(https://n3s.nadesi.com/id.php?1964)があったとして、
```
●(Aを|Aの)二倍とは
    A*2を戻す。
ここまで。

もし、プラグイン名＝「メイン」ならば、
    数＝５。
    数を二倍して言う。
ここまで。
```

　サンプル部分で使われている数を、取り込み先のプログラムで宣言して使用しようとすると、エラーなります。
```
！『https://n3s.nadesi.com/plain/1964.nako3』を取り込む。

変数 数＝１０。
数の二倍を言う。

＃[エラー][文法エラー]main.nako3(3行目): 変数『1964__数』の二重定義はできません。
```

　といって、内容が引き継がれているわけではなく。
```
！『https://n3s.nadesi.com/plain/1964.nako3』を取り込む。

数を言う。

※[実行時エラー]main.nako3(3行目): TypeError: t is undefined
```

　宣言しなければ、だいじょぶなのですが。
```
！『https://n3s.nadesi.com/plain/1964.nako3』を取り込む。

数＝１０。
数の二倍を言う。
```

**Comment by kujirahand** [comment]
報告ありがとうございます。
こちら、「1964__数」(プラグイン名__変数名)自体はプラグインの空間に定義されているのですが、取り込んだ時にはプラグイン名が「メイン」ではないので値は設定されないという感じです。変数定義だけは、前処理時に行われるのですが、定義時に値が初期化されるわけではないので、値は代入されていないという挙動です。

『もし、プラグイン名＝「メイン」ならば』の部分が関数内ではなくグローバル領域に書かれているために起きている問題です。
そこで、『もし、プラグイン名＝「メイン」ならば、プラグイン1964メイン関数』と書いておいて、「プラグイン1964メイン関数」内で数を定義するとこの問題が解決すると思います。

**Comment by snowdrops89** [comment]
ありがとうございます！
なるほどー。プラグインにテストというかデモとゆうかをくっつける時は、注意が必要なんですね。
テスト部分を関数にして、ローカル変数にしてしまえば、だいじょぶということですよね？
とすると、UIを使ってアレ出来るようにしていた場合、イベントから見えなくなっちゃいますよね。
通常の関数ですと引数で渡せるのですが、イベントやタイマーのような、にわ的な関数の場合、何かうまい手立てがあるでしょうか。
取り込み先から絶対に使われないような変数名にしておくしかない？
あるいは、凝ったものはサンプルとしてくっつけず、別途投稿するようにした方がよいのでしょうか。

**Comment by kujirahand** [comment]
あ、すみません。読みが浅かったですね。

改めて読み直して正しい挙動としては、以下の★1が、「メイン__数」の変数が生成されるべきですね。。。

```
！『https://n3s.nadesi.com/plain/1964.nako3』を取り込む。
変数 数＝１０。# ----- ★1
数の二倍を言う。
＃[エラー][文法エラー]main.nako3(3行目): 変数『1964__数』の二重定義はできません。
```

変数宣言の処理を見直したいと思います。

**Comment by snowdrops89** [comment]
修正を確認しました☆
ありがとうございました！
