### ISSUE TITLE
タートルグラフィックスにウサギやワニなどを用意する(?)

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#141]
ご意見をいただいたので転記：

マイナビを見ながらカメの画像は変えることができるので、子供とかだったら画像を変えたくなるのでカメ以外も用意できたらいいですね。もしくはカメの名称を変えれたらいいですね（例：カメ作成→ウサギ作成　など）。

実装案：

- いくつか動物で始める命令を作る(ウサギ作成、ワニ作成、クジラ作成）
- カメ作成でカメを作った後に、「ウサギへカメ変身」と書くようにする

**Comment by massongit** [comment]
#41
