### ISSUE TITLE
Raspberry Pi対応

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1411]
Raspberry Pi対応の確認。

https://nadesi.com/doc3/index.php?%E3%83%A9%E3%82%BA%E3%83%91%E3%82%A4%E3%81%A7%E5%8B%95%E3%81%8B%E3%81%9D%E3%81%86

**Comment by kujirahand** [comment]
非公式バイナリで試したが、Raspberry Pi Zero Wで動かなくなっている。

**Comment by snowdrops89** [comment]
動きましたよ～☆

まず、[ラズパイで動かそう](https://nadesi.com/doc3/index.php?%E3%83%A9%E3%82%BA%E3%83%91%E3%82%A4%E3%81%A7%E5%8B%95%E3%81%8B%E3%81%9D%E3%81%86#hca2d4c58)に記載された、非公式バイナリインストールの手順で、設定を更新のパスが間違っています。

この手順通りであればバイナリは`/usr/local/lib/nodejs/node-v16.5.0-linux-armv6l`にインストールされているので、パスは`/usr/local/lib/nodejs/node-v16.5.0-linux-armv6l/bin`に通す必要があります。

そして、nodeに`--no-expose-wasm`のパラメーターを付けて起動する必要があるようです！
詳しくはこちらで記事にしました。

https://qiita.com/snowdrops89/items/498f7917b9d86eecd71b

**Comment by kujirahand** [comment]
検証と詳しい動作手順の紹介、ありがとうございます！！
直接リンクさせていただきました！！

今、半導体不足で、新規でRaspberry Piが入手できない状態のようですが、早く供給が安定すると良いですよねー。
そうしたら、電子工作＋なでしこも、もっと楽しめるようになるかも？！

**Comment by kujirahand** [comment]
ありがとうございます！こちら一度閉じたいと思います。
