### ISSUE TITLE
イベントの中で連文を使い、それを「＝」で代入するとエラーになります

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1427]
```
「テスト」のボタン作成して、テストボタンに代入。
テストボタンをクリックした時には、
    答＝1に5を足して2を掛ける。# できない
    //1に5を足して2を掛けて答に代入。# できる
    //答＝1に5を足す。答＝答に2を掛ける。# できる
    答を表示。
ここまで。
```
イベントの中でなければ問題は無く、「代入」で代入することは出来、連文を使わず分けて書いた場合は大丈夫・・・とゆうナゾ現象です。
v3.4.5までは大丈夫でした。

コンソールに
```
Uncaught ReferenceError: await is not defined
```
というエラーがでています。

**Comment by kujirahand** [comment]
不思議ですね。秒後でも再現しました。先日の非同期構文の連文の修正が関係していそうです。生成後のコードが複雑すぎて、修正には熟読が必要です。。。

```
0.1秒後には
    答＝1に5を足して2を掛ける。# できない
    答を表示。
ここまで。
```

**Comment by kujirahand** [comment]
下記の修正ミスを修正しました。
https://github.com/kujirahand/nadesiko3core/commit/ef92368abff17bc3a89fb9565fcd5d1478050cd1

**Comment by snowdrops89** [comment]
修正を確認しました☆
ありがとうございます！
