### ISSUE TITLE
BigInt四則演算のサポート

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1448]
https://nadesi.com/cgi/kaizen3/?m=thread&threadid=70
より

BigIntをサポートし、その四則演算を可能にします。

```
a=1234567890123456789
a*3を表示
```

一部の変数を明示的に巨大整数変換をするのは譲れるとして、計算にかかわるすべての変数を bigint に変換しないといけないのは骨が折れます。

そこで、なでしこcore 側で、bigint と number の四則演算をしようとした時に、現状ではエラーになる動作を、number を自動的に bigint に変換して計算する仕様を追加したいです。

さらに、可能なら #1410 の「浮動小数点数を10進数で計算できるようにする」の案の実もできるような機構を考慮したいと思います。簡単なオプションで切り替えるとか。

現在のバージョンは、3.4.xですが、こちらの実装をもって、3.5.xにバージョン番号を移行しようと思います。

**Comment by kujirahand** [comment]
@TumoiYorozu さん

> （もしもこの方針に賛同できるけど時間がなければ、私の方でPRを作れないかも試そうかと思います）

とのこと！
こちら、ぜひぜひ挑戦してみてください！

**Comment by TumoiYorozu** [comment]
とりあえず現状でもハック的な方法で多倍長整数は使えるので、まず第一歩としてbigint と number の四則演算(+剰余・べき乗)を自動的に bigint に変換して計算してくれる機能を追加を考えています。
bigint へ変換するときは、以下のような関数をユーザーが定義して使うことを想定しています。
```
●(Aを)巨大整数変換とは
　　「{A}n」をJS実行。
ここまで
```
他にもなでしこパーサーで、 `1234567890123456789n` の様な n が末尾に来る数値を bigint に解釈するのも現実的そうです。
`巨大整数変換` 関数等を言語機能側で実装するかは任せます。


言語機能として `12345678900987654321` の様な2^53を超える整数を自動で bigint にする・計算結果が±2^53の範囲から外れる整数値を自動で bigint にするのは、ロジックが大変そうです。

「浮動小数点数を10進数で計算できるようにする」というマイルストーンもある程度同意ですが、現状の number と共存させてユーザーが意識せず自動で変換するのか、number を全廃止してすべて10進にするのか、自動変換はせずにユーザーに型の意識を持って使ってもらうのかでかなり変わりそうです。


とりあえず実験的機能を兼ねて、ある程度ユーザーに型の意識を持って使ってもらう前提で、
・bigint の四則%^演算のサポートを追加
・可能なら、`1234567890123456789n` の様な bigint リテラルの追加
はしたいかなと思っています。

**Comment by TumoiYorozu** [comment]
試しに core のコードを確認したのですが、四則演算等を全て JS の 演算子で計算する実装だったので、「演算子の片方が bigint で片方が number だったら bigint に変換する」ってロジックは可能ではあるけど、条件分岐が増えて bigint を使わない計算もそこそこ遅くなりそうなので、やはり提案を辞めようかなという気持ちになってきました。

なでしこ上で `123n` などの数値を bigint リテラルとして解釈する、というのは試した限り現実的そうですが、文法として追加するのはいかが思いますか？

**Comment by kujirahand** [comment]
調査ありがとうございます。
bigintリテラルの案は良いと思います。

それでも、速度低下は、ちょっと危惧していた点でした。
それで、コンパイル時点で型が分かるようになると良いと思います。

構文木（AST）にbigintを判別できるような型属性をつけておいて、コンパイル時点でbigintならbigintの計算のコードを生成する感じでできると良さそうです。

そのためにも、今後、少しずつ、組み込み関数や引数にもどんな型を返すのかデータ型を明示する仕組みを追加していきたいと思います。

**Comment by TumoiYorozu** [comment]
ひとまず、bigint リテラルのサポート PR を作りました。

https://github.com/kujirahand/nadesiko3core/pull/105

**Comment by kujirahand** [comment]
この後、マニュアルに追記します。

**Comment by kujirahand** [comment]
v3/doc の 文法/数値 にBigInt記法を追記しました。以上で、このIssuesを閉じます。

https://nadesi.com/v3/doc/index.php?%E6%96%87%E6%B3%95%2F%E6%95%B0%E5%80%A4&show
