### ISSUE TITLE
配列を整数・実数変換した時に、中の要素それぞれを整数変換する案

### ISSUE THREAD

**Issue by TumoiYorozu** [kujirahand/nadesiko3#1452]
以下のようなコードを実行した時に、現行はそれぞれの先頭要素のみが変換されてそれだけが帰ってきますが、
各要素を変換した配列が帰ってくる方が良いのではと思いました

```
「12,34,56」を「,」で区切るを整数変換を表示

「101,102
201,202」をCSV取得して整数変換を表示
```

現状の出力
```
12
101
```

**Comment by kujirahand** [comment]
そうですね。配列かどうかをチェックして処理を行えるようになると便利そうです。

**Comment by TumoiYorozu** [comment]
実装しようとしましたが、 `TOINT` 命令等との挙動は合わせたい気がし、TOINT で配列の中の要素が整数変換されるのは違うかなと思い、「配列数値変換」命令を追加案 PR を出しました。

https://github.com/kujirahand/nadesiko3core/pull/106

二次元・多次元配列についてはとりあえず放置しました。

**Comment by kujirahand** [comment]
うっかり、こちら閉じ忘れてました。
改めて、 @TumoiYorozu さん、感謝です！！
