### ISSUE TITLE
@がうまく動作していない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#158]
```
# 配列への代入
A=空配列
A@0=10
A@1=30
A@2=50
# 配列を参照
A@1を表示。# → 30
```

**Comment by massongit** [comment]
ぱっと見『空配列』が定義されていなさそうに見えるので、それが原因かもしれないですね。

**Comment by kujirahand** [comment]
修正作業してくださって、ありがとうございました。
ただ、空配列は、src/plugin_system.jsで定義してあったのに、何かのタイミングで消えてしまったようなのです。文法を触らなくても、システム変数で対処する方がエレガントなので、そちらにしますね。
反映できなくてすみません。

**Comment by kujirahand** [comment]
修正済み
