### ISSUE TITLE
未入力でOKした場合もダイアログキャンセル値が戻ります

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1586]
v3.4.23でダイアログキャンセル値が追加されたのですが、ダイアログキャンセル値の効果って、尋ねる文などで未入力でOKした場合とキャンセルボタンを押した場合を仕分けられることだと思うのですが、現状はどちらもダイアログキャンセル値が戻ります。
```
ダイアログキャンセル値＝「キャンセル」
「名前は？」と尋ねる
それを言う
```
ｖ１ですとこれは、未入力でOKした場合には空、キャンセルした場合には「キャンセル」になりますが、ｖ３ではどっちも「キャンセル」となってしまいます。

追記
Window.promptの調べると、テキストを入力せずに OK をクリックした時は空文字、キャンセルボタンをクリックしたときは null をかえすとゆうことなので、nullの時だけダイアログキャンセル値を返すように出来たらタブンよさそげだと思うのですが🤔

**Comment by snowdrops89** [comment]
早速ありがとうございます☆
まだ貯蔵庫には反映されてないですか？

**Comment by kujirahand** [comment]
@snowdrops89 あ、すみません。先ほどアップデートしました！

**Comment by snowdrops89** [comment]
確認しました。ありがとうございます！

**Comment by kujirahand** [comment]
確認ありがとうございました！
