### ISSUE TITLE
PEGJSの文法コンパイルが遅い問題

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#163]
PEGJSのコンパイルが遅すぎる --- PEGJS is so slowly.

- 文法の分割
- PEGJS以外のパーサを使う

など、対策を考える。

文法に手を入れようと思うが、コンパイルが遅すぎて、やる気をなくす問題。

**Comment by massongit** [comment]
参考までに

パーサコンビネータを高速化した - Object.create(null)
http://susisu.hatenablog.com/entry/2017/03/14/142341

**Comment by kujirahand** [comment]
@massongit 有益な情報に感謝。

ちょっと、調べてみたところ、いろいろある様子。
PEGJSは遅い部類の模様。

ジェネレータ

- https://zaa.ch/jison/ --- CoffeeScriptもこれをベースにしている
- https://github.com/susisu/loquat2 --- 最速のパーサジェネレータ
- https://github.com/jneen/parsimmon --- loquat2がライバルとしていたやつ

速度比較

- https://sap.github.io/chevrotain/performance/
- https://github.com/SAP/chevrotain/tree/gh-pages/performance

**Comment by massongit** [comment]
1. テキストファイルかなにかにBNF記法でPEG.jsで記述されている文法を書き出す
2. 書き出したBNFを元に文法を最適化
3. 新たなパーサでBNFを表現

みたいな感じでやるのが良いのかもしれないですね。

**Comment by bd82** [comment]
Hello.

Author of Chevrotain here...

Can I participate in this discussion in **english**?

I get the gist of the discussion using google translate but I'm afraid
I do not speak Japanese 😄

**Comment by kujirahand** [comment]
いろいろ見た感じ、やはり、Jisonが使いやすそうな印象です。
Lexerもカスタムスキャナも適当に書けそうなので。

- https://zaa.ch/jison/docs/#custom-scanners

日本語のトークン分割は、手書きした方が、効率的ですし。

**Comment by kujirahand** [comment]
結局 BNF 記法だと、日本語文法がうまく表現できないので、試しに手書きのパーサを書いてみました。試行錯誤ながら、なんか一日で、数値の代入と計算、関数呼び出しまで実装できたので、このまま作ってみます。

**Comment by kujirahand** [comment]
全てのテストに通ったので、問題なさそうなら閉じようと思います。

**Comment by kujirahand** [comment]
既にPEGJSのパーサーは廃止されました。
