### ISSUE TITLE
貯蔵庫で表示ログ・表示ログクリアがおかしい

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1669]
質問掲示板より。
https://www.eznavi.net/site/bbs/index2.php?pagetop=1890&cere=3

同じv3.6.6のマニュアルのサンプルでは正常なので、貯蔵庫の方の問題かもなのですが、
```
# --- 普通に表示 ---
「受けるより」と表示。
「与える方が」と表示。
「幸福」と表示。
# --- 表示ログの内容を表示 ---
表示ログを表示。
```
表示ログが空になっているようで、表示されません。

そしてなんと‼️
```
B1=「1」のボタン作成
B1をクリックした時には
　　「111」を表示
　　「222」を表示。
　　表示ログを言う。
ここまで。
B2=「2」のボタン作成。
B2をクリックした時には
　　表示ログクリア。
　　「333」を表示。
　　表示ログを言う。
ここまで。
```
表示ログクリアをすると、ボタンが消えてしまいます。

**Comment by takjoe** [comment]
代わりに立ててくださりありがとうございます！

**Comment by kujirahand** [comment]
ご報告ありがとうございます😊
#1670 を実装することで直ると思います。
できるだけ早く作業します。

**Comment by kujirahand** [comment]
#1670 の修正は、めちゃくちゃ時間がかかることが分かったので、
とりあえず、貯蔵庫修正しました。
ご報告に、改めて感謝です😊😊😊

**Comment by kujirahand** [comment]
本番環境(n3s.nadesi.com)で解決したのを確認しましたので、閉じますねー。感謝✨
