### ISSUE TITLE
文字列から整数, 浮動小数点数への暗黙的な型変換

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#167]
([なこ丼のトゥート](https://nadesiko-users.info/@tomomo_system/1909)より)

v1との互換性を考えると、文字列から整数, 浮動小数点数への暗黙的な型変換ができた方が良いかもしれません。

* テストコード
```
基本料金は「500」
通信パケットは「5000000」
通信料金は通信パケット/100
基本料金+通信料金を表示 # ここで「50500」と出てくれば成功
```

**Comment by kujirahand** [comment]
確かに「&」演算子以外は、数値に変換すべきですね。
