### ISSUE TITLE
「予約語一覧取得」「助詞一覧取得」の結果が空

### ISSUE THREAD

**Issue by mikecat** [kujirahand/nadesiko3#1692]
[なでしこ3簡易エディタ - 日本語プログラミング言語「なでしこ3」](https://nadesi.com/doc3/index.php?%E3%81%AA%E3%81%A7%E3%81%97%E3%81%933%E7%B0%A1%E6%98%93%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF) (v3.6.7) で

```
予約語一覧取得。
それをJSONエンコードして表示。
```

を実行すると、

```
[]
```

という結果が得られました。

これは不具合でしょうか？
それとも仕様 (現在予約語は存在しない) でしょうか？

**Comment by kujirahand** [comment]
ご報告ありがとうございました。
すぐに修正したいと思います。

**Comment by kujirahand** [comment]
v3.6.9で修正しました。
