### ISSUE TITLE
「文字描画幅取得」を使うとエラーが発生する 

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1714]
掲示板からの転載です。
https://www.eznavi.net/site/bbs/index2.php?pagetop=1959&cere=5

再現方法
```
文字幅＝「なでしこ」の文字描画幅取得。
文字幅["width"]を表示。
```

エラー内容
```
[エラー]missing ) after argument list
```

二回目以降の実行は該当部分を消しても
```
t.__removeAllDomEvent is not a function
```
となる。

v3.6.2から発生しているようです。
v3.5.3では問題ありませんでした。

**Comment by kujirahand** [comment]
ご報告ありがとうございます。
どうやら、関数の戻り値がないというフラグが設定されていたようです。
それで、戻り値がない関数を代入文で使おうとするとJSの文法エラーがでるということですので、別件で修正します。

**Comment by kujirahand** [comment]
v3.6.13で本番に反映しました！
ご協力、ありがとうございました！！！

**Comment by kuromame96** [comment]
掲示板に書き込んだ者(ひろきくん)です。
最初からこちらに書き込めばよかったですね😅

修正ありがとうございます。
