### ISSUE TITLE
関数の引数が省略された時のエラーについて

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1716]
まず、v3.5.3までは、これが問題なく動いていました。
```
「Ａ」と「Ｂ」で挨拶。

●(AとBでCの)挨拶
    Cを表示。
    もし、C＝「朝」ならば、
        「{A}:おっはー」を表示。
        「{B}:おはよー」を表示。
    違えば、
        「{A}:こんにちは」を表示。
        「{B}:こんにちは」を表示。
    ここまで。
ここまで。
```
このときCには空が入っていて、空の場合の処理を書くことで省略時のデフォルト値を設定することも出来ました。。
なでしこ３には、ｖ１のような関数の引数が省略された場合のデフォルト値を設定する機能がないため、いろいろ裏技を模索して、引数を省略できる関数を作っていました。

ところが～‼️
v3.6.2以降、これは、
```
[エラー]expected expression, got ','
```
なるJSのエラーが表示されるようになってしまいました～😭

できれば元の通りに使えるようになると助かります。
もちろん関数の引数不足はエラーとして、裏技ダメ🙅とゆう事であればそれはそれで仕方ないのですが～🥲
その場合はエラーメッセージはなでしこの、何行目のこの関数の引数が足りないよ！　という形にした方が良いと思います。

そして・・・ｖ１のようにデフォルト値を明示して引数省略の指定ができるようにすることはだいぶ難しいのでしょうか。

**Comment by kujirahand** [comment]
こちらの問題、お騒がせしました。。。
[引数の問題がある場合に壊れたJSが生成される場合がある問題](https://github.com/kujirahand/nadesiko3/commit/703799ea22bcd5e07de278c154d981aa7da298ae) https://github.com/kujirahand/nadesiko3/issues/1729 で修正しました！
最新のv3.6.15で修正されています。

本来は、v1の引数のデフォルト値の指定ができると良いですよね。検討します。
関数のデフォルト値を指定できるようにする #1732
