### ISSUE TITLE
「反復」構文で、変数「対象」がローカル変数になってしまった問題

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1723]
v3.6でプログラムが動かない - クリックした時にはの構文で問題が起きます。

以下より抜粋:
https://discord.com/channels/1211143706783129692/1211143707269791801/1272531703214374997

```
「古典『源氏物語』の作者は誰？」を表示。
「回答A清少納言
回答B平清盛
回答C紫式部
回答D夏目漱石」を改行で区切って反復
　対象のボタン作成
　それをクリックした時には
　　　対象からテキスト取得
　　　もし、それが「回答C紫式部」ならば
　　　　「当たり！」と言う
　　　違えば
　　　　「はずれ。回答C紫式部でした」と言う
　　　ここまで
　ここまで
ここまで
```

なでしこ3.5.3までは動いていた
なでしこ3.6.2～3.6.13(最新)では動かない
正式に動かなくなるのか、たまたま今のバージョンがバグって動かないのか、本気でわかりません。

**Comment by snowdrops89** [comment]
反復などを使って対象に何かが代入されている状態でクリックなどのイベントが発生しても、対象にDOMオブジェクトが設定されず、対象の内容が先に代入されたもののままになっているようです。
例：
```
[1,2,3]を反復。ここまで。
A=「てすと」のボタン作成。
Aをクリックした時には
　対象を言う。
ここまで。
```

**Comment by weyk** [comment]
コンパイルされたスクリプトで確認しました。
もともと、どのケースでも「対象」はグローバル変数の「対象」が
使われていて、ユーザが上書きを注意する構成だったと思うのですが、
反復命令がローカル変数の「対象」を定義するようになって(変わって?)、
（トップレベルのローカル変数が定義されるというのも今までにはないイレギュラーかも）
さらに、同一スコープに同名のローカル変数が存在しているため
本来は常にグローバル変数の「対象」を参照するはずがローカル変数の「対象」を
参照するようソースが生成されてしまっているようです。
（今の「クリック時」は常にグローバルの「対象」に設定する）

実際には参照不可能は変数(イベント発生時には寿命が尽きている)への参照を持つ
スクリプトを生成していることになるので実は大きな問題かも。

個人的には
・この機会に引数代わりのグローバル変数経由での情報のやり取りは廃止する。Strictモードのように。名前付き引数が適任かも。
　（互換ならコールバック関数に値付きローカル変数を定義する仕組みが要る？ちょっとトリッキー。）
・ユーザ関数から無名関数内部への値の引き渡しはユーザ側でグローバル変数を用意して管理する。
・現状、ユーザ関数内で定義した無名関数からユーザ関数のローカル変数はスコープが繋がらないので誤った参照を生成しない。

**Comment by kujirahand** [comment]
v3.6.14で修正しました。

**Comment by kujirahand** [comment]
反復以外でも、nako_gen.mtsで、`varname_set`を使っている場合に、何かしらの問題を起こす場合がありそうです。
#1725 で引き続き調査しますが、とりあえず、こちらは修正完了です。
閉じます。

**Comment by kujirahand** [comment]
@weyk さんへ。あれ？夕方、軽く見たときには、何かとても良い提案コメントがあったと思うのですが、今、こちらに見当たらないですね😿。良かったら、別のIssuesで立てていただけると幸いです。
