### ISSUE TITLE
グラフが作成できるように

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#173]
各種、グラフライブラリをラップして、手軽にグラフが表示できるようにする

**Comment by massongit** [comment]
グラフライブラリについて載っているサイトを載せておきます。
* [JavaScriptでグラフ描画入門！全８個のライブラリをコード付きで一挙に解説！ - paiza開発日誌](http://paiza.hatenablog.com/entry/2016/06/07/JavaScriptでグラフ描画入門！全８個のライブラリをコー)

**Comment by kujirahand** [comment]
軽量でかつライセンス重視のC3.js辺りがよいでしょうか。

**Comment by kujirahand** [comment]
やっぱり、いろいろ調べてみて、手軽にカッコイイグラフが作れる、Chart.jsにしてみます。
