### ISSUE TITLE
Node用なでしこプラグインについて考える

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#174]
コマンドライン版のなでしこでは、npmを利用して、なでしこプラグインもインストールできるようにする。実装意見も募集中。

雰囲気としては、gulpのプラグインみたいな感じで、「nadesiko3-sqlite3」など「npm install nadesiko3-プラグイン名」でプラグインがインストールできるようにする。

### 実装案1 - 自動で全部読み込む - v1と同じ感じ

cnako3.jsの実行時に、node_module以下にあるプラグインを全部読み込んで、命令が自動的に使えるようにする。ソースコードと同じディレクトリに「node_module/nadesiko3-xxx」のようなモジュールがあれば、そこから、必要な命令定義を取り込むようにする。

### 実装案2 - 明示的に読み込む命令を用意する - node互換

Nodeのrequireにあたる命令を用意する。requireされることで、そのプラグインがcnako3で使えるようになる仕組み。全部を強制的に読み込む必要がないので、起動時の動作が軽い。

### メモ

実装案2が有力。

**Comment by massongit** [comment]
実装案2のrequireにあたる命令として、v1でいうところの『取り込む』命令を使うと良い感じになるのではないでしょうか？

**Comment by kujirahand** [comment]
それでは、実装案2で行くことにしますね。
