### ISSUE TITLE
「押されたボタン」「マウス入った時」「マウス出た時」「ダブルクリック時」を実装

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1756]
https://nadesi.com/cgi/kaizen3/index.php?m=log&logid=332 より

「右クリック時」（contextmenu イベント）もあると良いなと思います。
伴って、「クリック時」のエイリアス的な感じで、「左クリック時」もあると良いかもしれません。

**Comment by snowdrops89** [comment]
「右クリック時」もあればあったで良いのですが、ｖ１ではクリックのイベントは「クリック時」のみで、「マウス押した時」に「押されたボタン」で「左、右、中央」が取得出来るようになっています。
ｖ３では、対象イベント["button"]で、「0（左）、1（中央）、2（右）」と取得出来るのですが、これが「押されたボタン」に入るようになると、ｖ１との互換性が向上すると思います。

あと、「ダブルクリック時」(dblclick)も欲しいですね（便乗😅）
また、「マウス入った時」(mouseover)、「マウス出た時」(mouseout)も、案外必要になるものです。
ついでにマウスホイールも回したいですね（mousewheel）

1754で「変更した時」が追加されたのは朗報でした。
ぜんぶ「DOMイベント発火時」で出来るから、ま、いっか～と、ガマンして使ってた部分ありますが、やはりｖ１で使えるくらいのイベントは、日本語で出来るようになるとうれしい。
最近のトップページの様子を見るといよいよ本格的にメインはｖ３としていく方針なのかなと思ってて、であればやはりDOM部品がｖ１のGUI部品くらい使い勝手が良くなるとイイですね✨
こんなこと出来ないかしらと思うたびにHTMLやJavascriptのイベントを調べなきゃなのは、初心者にはハードルが高いっていうか出来ないものと思われてしまう可能性があります🥲

**Comment by kujirahand** [comment]
@snowdrops89 さん、マウスイベントについて提案ありがとうございます！
素晴らしいです。
「押されたボタン」「マウス入った時」「マウス出た時」「ダブルクリック時」「マウスホイール時」を実装したいと思います。

**Comment by kujirahand** [comment]
5f219025da6e250602794094fefae36c30a3c856 にて実装しました。うっかり Issuesの番号付け忘れちゃった😭

**Comment by kujirahand** [comment]
v3.6.23で実装しました！

**Comment by kujirahand** [comment]
変更時のイベントがチェンジじゃなくて'click'になっているようですと指摘あり
https://github.com/kujirahand/nadesiko3/commit/9b682744854b2d8fe4b7a36db240c60c328db309

**Comment by snowdrops89** [comment]
お試ししてみた結果、クリック時でも押されたキーを設定するようになっているようなのですが、クリックでは対象イベント["button"]は常に０で中央や右は検出出来ないっぽいので(0も左を検出しているのか不明)、押されたボタンはクリックでは取得出来ずマウス押した時で取得するとした方が良いと思います（たしかｖ１はそうなってます）

ちなみに、マウス移動した時、マウス入った時、マウス出た時も対象イベント["button"]は常に０っぽいです。
今更なのですが対象イベント["buttons"]の方がいいかも？
これは、マウス移動した時、マウス入った時、マウス出た時でも取得出来て、0:押されていない、1:左、2:右、4:中央で、組み合わせで同時押しも検出出来ます。
それか、押されたボタンはｖ１同様マウス押した時にだけ左右中央と日本語で取得して、別途押下中ボタンみたいのを作るとか？🤔


それからワタクシうっかりしておりましたが～💧
大本のおさねさんの要望としてはこんてきすとめにゅーイベントの追加だったのでした。
https://nadesi.com/cgi/kaizen3/index.php?m=log&logid=332
ワタクシが便乗して色々マウスのイベントを要望した結果、こちらは追加されないままとなってしまいましたが、このイベントのDOMイベント処理停止をしないと右クリックに独自の処理をさせるプログラムは書けないので～。
ただこれはマウスのイベントではなく、右クリックメニューはマウスだけじゃなくキーボードでも開いてこのイベントが発生するので、イベント名が「右クリック時」で良いかどうかは考え所なのですが。

**Comment by kujirahand** [comment]
良い提案をありがとうございましす！！

「クリック時」「ダブルクリック時」には「押ボタン」が利かないよう修正。「右クリック時」を追加。「マウス移動時」「マウス離した時」「マウス入った時」「マウス出た時」の助詞を修正。また、「押したボタン」判定にbuttonsを利用する用に修正。 #1756
