### ISSUE TITLE
Windows版インストーラーを作る

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#178]
Windows版では、アーカイブにいろいろ含めるのを止めて、Node.jsやその他のアプリを自動でインストールするように工夫する。例えば、chocolateyを利用する。

- https://chocolatey.org/install

## 手順案1

- chocolateyを入れる
- その後、Node.js/Gitを入れて、GitHubからなでしこのソースコードを引っ張ってくる。
- npmでモジュールを自動ダウンロード
- なでしこ3をビルドする

## 手順案2

- chocolatey
- choco install nodejs
- npm install nadesiko3

**Comment by kujirahand** [comment]
## 手順案3

ただし、chocolateyは入れて貰うのが大変なので、Node.jsになでしこが梱包されたものを作る。そして、バッチファイルをダブルクリックすると、npm startが実行されるようにする。

**Comment by massongit** [comment]
参考までに: http://www5a.biglobe.ne.jp/~nobukich/index_j.htm

**Comment by massongit** [comment]
プログラミング初心者はコマンドラインでの操作に抵抗感を覚える場合が多いと思います (少なくとも昔の自分はそうでした)。
従って、GUIの操作のみでインストール作業が行える __手順案3__ が良いのではないかと思います。

**Comment by kujirahand** [comment]
インストーラーは、次のステップとして、とりあえず、node一式と起動用のバッチファイルを梱包したアーカイブをアップロードしました！

https://github.com/kujirahand/nadesiko3/releases/tag/3.0.19

**Comment by kujirahand** [comment]
とりあえず作ったが、Electronを含めたこともありアーカイブが巨大すぎるので別の方法を考える。

Node.jsがインストールされていて、バッチファイルをダブルクリックすれば、なでしこ3が使えるようになる仕組みを考える。

**Comment by kujirahand** [comment]
以下に、お試しで、Windows版のインストーラーをアップしました。
https://github.com/kujirahand/nadesiko3/releases/tag/3.0.24

**Comment by kujirahand** [comment]
#263 で、sleepモジュールで、Winだとコンパイルが必要。

結局、WindowsでNodeをしっかり使うには、Visual StudioとPython2と・・・といろいろインストールする必要があり、かなりハードルが高い印象。

そこで、やはり、Nodeと各種モジュール一式を梱包したパッケージを作って別途配布する作成が好ましいという結論に。

**Comment by kujirahand** [comment]
現在、Nodeとモジュールと全てを梱包したWindows版のなでしこv3を別リポジトリにて絶賛配布中なので、とりあえず、こちらのIssueは閉じる。

- https://github.com/kujirahand/nadesiko3win32
