### ISSUE TITLE
貯蔵庫のCSSについて再考したいです

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#1786]
これはなでしこというより貯蔵庫の問題なのですが、偶数行の指定が反映されていません。

```
DOM部品オプション["テーブル背景色"] = [青色,緑色,赤色]
「名前,年齢
桃太郎,98
さる太郎,87
きじ次郎,77」のテーブル作成。
```

調査をみると、要素にはちゃんとlimeが設定されているのですが、CSSで上位のクラスに設定されている

```
.showblock table tr:nth-child(odd) td {
  background-color: #f0f0ff;
}
```

が優先されているためです。
これより下の行で、

```
#nako3_div td {
  background-color: initial;
}
```
と、打ち消してやれば解決すると思いますのでご確認をおねがいします。
ちなみに、マニュアルのサンプルでは、マッタク何一つ反映されていません～。
タブンkonawiki3の設定が優先されているものとおもいますが。

**Comment by kujirahand** [comment]
反映されるようになりました！
- Konawiki3 --- https://nadesi.com/v3/doc/go.php?1078
- 貯蔵庫 --- https://n3s-sandbox.nadesi.com/widget.php?2753&run=1&allow=1

**Comment by snowdrops89** [comment]
確認しました。ありがとうございました！

**Comment by kujirahand** [comment]
CSSの問題は複雑で難しいですね。もうちょっと考えてみます。

**Comment by kujirahand** [comment]
#1856 に話題が移ったのでこちらは一度閉じますね。ありがとうございます！
