### ISSUE TITLE
オブジェクトプロパティ構文の記号をどれにする？

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1807]
#1793 で実装したオブジェクトプロパティ構文ですが、記号の「＄」に違和感があるという意見もあります。

さて、どれが良いでしょうか？

- (1) 「$」のまま
- (2)  v1互換、オブジェクトプロパティ構文の記号を「→」「->」とする。矢印記号は絵文字にたくさんあるので、それも考慮する。
- (3) v1互換、そして親言語のJavaScriptに倣って「.」にする
- (4) もっと別の記号。

少し使っていたら、$も悪くないかもとなりそうですが。

**Comment by snowdrops89** [comment]
私の個人的なイチオシは３でしょうかねー。
確かにお試しで使って既に$にも慣れて来ちゃいましたけど、ｖ１やJavascriptと一緒というのはやはり多くの人に受け入れられやすいと思います。
あと打ちやすさで言うと、辞書型変数の＠や、ｖ１の配列の￥がキー一つで出るのに対して＄はシフトキーが必要ですからね～。超個人的なことで言えば、「.」のほうがしゅっと打てます～。

**Comment by kujirahand** [comment]
@snowdrops89  意見ありがとうございます。
そうですねー。個人的には「$」が気に入ったので、「.」か「$」のどちらかでアクセスできる仕様にしてみます。

**Comment by kujirahand** [comment]
とりあえず、「$」と「.」好きな方を使えば良さそうなので、閉じます。
