### ISSUE TITLE
開発環境のセットアップのドキュメントへをより易しくなるような補足を追加したい

### ISSUE THREAD

**Issue by mr-xx** [kujirahand/nadesiko3#181]
こんにちは、

https://github.com/kujirahand/nadesiko3/blob/master/SETUP.md
について。

先ほど自分で環境セットアップを行ってみたのですが、

npm install --no-optional

のところでつまづきました。

これは、私が、以下のことを理解できていなかったからでした。

- nadesiko3のリポジトリをローカルにダウンロードし展開する
- 展開したディレクトリの中で、「npm install --no-optional」を実行する

おそらく開発の知識、経験があれば上記のつまづきポイントは回避できるレベルかとは思いますが、私のような開発ビギナーのために、補足説明を入れると良いのではないかと感じました。

**Comment by kujirahand** [comment]
やはり、コマンドラインを使ってのインストールはハードルが高いですよね(ToT
親切なアーカイブを用意すると言いつつ、まだ準備が整わずですが、
#178 
実現急ぎます。

**Comment by kujirahand** [comment]
とりあえず、Windows版をリリースしたので、解決とします。
