### ISSUE TITLE
JSONエンコードめっちゃ使うので使いやすいエイリアス作る

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#1813]
「JSONエンコード」「JSONエンコード整形」めっちゃ使うので、手軽に使えるエイリアスを作ろうと思います。

### 条件
- 「JSON」だけだと、既に変数名で使われているパターンが多いと思うので、一工夫必要です。
- IMEオン・オフの状態で、手軽に入力できる単語にしようと思います。

### JSONエンコードの候補：
- JSON_ / _JSON
- JSON_E / JSON_ENC / JSON_ENCODE
- JSON_STR
- JSON_STR

### JSONエンコード整形の候補：
- JSON_ENC2
- JSON_ENC_
- JSON_ENC_S

**Comment by kujirahand** [comment]
参考までに、ChatGPTが出してくれた案：

エイリアスを決める際には、入力のしやすさと既存の変数名との競合を避けることが重要です。以下の点を考慮して追加の候補を提案します：

### JSONエンコード
1. **JENC**: 短く、衝突の可能性が低い。
2. **JSTR**: JSONを文字列にするイメージに沿った名前。
3. **JE_**: JSON Encodeの略。衝突を避けるため末尾にアンダースコア。

### JSONエンコード整形
1. **JENC_F**: 整形（Formatted）を示す。
2. **JSTR_PRETTY**: Pretty printを意識した名前。
3. **JF_**: JSON Formatの略。短いエイリアスが欲しい場合に適切。

### IMEオン・オフの影響を考慮
日本語入力中でも容易に入力できる案として、ひらがな入力も視野に入れると次のような選択肢も考えられます：
- **じえん**（JENCの音読み）
- **じえふ**（JENC_Fの音読み）

これらを含めていかがでしょうか？

**Comment by snowdrops89** [comment]
JSON_E と JSON_ES に一票。
※整形（Formatted）なんて今知りましたわ（えっ）というレベルの人が「えんこーどせいけい」を素直に略すｗ

**Comment by kujirahand** [comment]
とりあえず、JSON_E / JSON_ES / JSON_D で登録してみます。
