### ISSUE TITLE
命令の途中にひらがなが入っている命令が使えないので直す

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#188]
> 命令の途中ににひらがなが入ってるヤツは全部同現象でダメなんじゃないでしょうか。
> 「文字抜き出し」「カタカナか判定」「数字か判定」「数列か判定」

**Comment by massongit** [comment]
`src/nako_lexer.js`の`trimOkurigana`関数が関数名の『送り仮名』を省略するのではなく『仮名全て』を省略する挙動をしていたのが原因なようです (そこを修正するとテストのかなりの項目が通らなくなるため、現時点ではPRを作成していません)。

**Comment by massongit** [comment]
`src/nako_lexer.js`の`trimOkurigana`関数において、命令の途中のひらがなが全て除去されているのが原因でした。
とりあえず`trimOkurigana`関数に寄せて`src/plugin_system.js`を書き換える形で上記の関数については解決を図ってみました。

**Comment by kujirahand** [comment]
とりあえず、送り仮名の省略は仕様ということで、命令定義するときに気をつける方向で行きましょう。
コマンドヘルプ作成時に、送り仮名の問題がないか確認するようにすると良いと思います。
