### ISSUE TITLE
plugin_system.jsの関数のテスト作成

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#189]
#188 に関連して、plugin_system.jsに記述されている関数のテストを作成する。

**Comment by massongit** [comment]
新しくファイルを作ってそこにテストを記述する形が良いでしょうか？

**Comment by kujirahand** [comment]
「test/func_system_test.js」があるので、こちらに追記していただいても良いですし、新規に専用のファイルを作っていただいても大丈夫です！
テストが徹底されると嬉しいです！！
どうぞ、よろしくお願いします。

**Comment by massongit** [comment]
既にテストが作成されているのでcloseします。
