### ISSUE TITLE
対応するブラウザについて (IE)

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#19]
現在サポートされているコンシューマ向けのWIndowsの中で一番古いVistaが 4/11 にサポート期限を迎え、それ以降のWIndowsではIE11をサポートしていることから、それより古いIEはサポートしなくても良いのではないかと思いますが、どうでしょうか？

参考
* [Tech TIPS：一目で分かる、各Windows OSでのInternet Explorerのサポート終了時期 - ＠IT](http://www.atmarkit.co.jp/ait/articles/1503/11/news134.html)
* [Windows Vistaサポート終了 早く10に乗り換えを - 日経トレンディネット](http://trendy.nikkeibp.co.jp/atcl/pickup/15/1003590/022700804/)

**Comment by kujirahand** [comment]
そうですね。さすがに、サポート終了した古いブラウザは、サポート外でも良いと思います！

**Comment by massongit** [comment]
Babelでの対応ブラウザの設定にはbrowserslistが使われていますが、[公式サイト](https://github.com/browserslist/browserslist)によると、デフォルト値は次のようになっているらしいです。
* `> 0.5%`: 世界的な利用統計で利用しているユーザーが0.5%超となったバージョン
* `last 2 versions`: 最新2バージョン
* `Firefox ESR`: Firefox延長サポート版
* `not dead`: 最新2バージョンであるが、世界的な利用統計で利用しているユーザーが0.5%未満となっており、公式によるサポートが2年間なかったバージョン (例: `IE 10`, `IE_Mob 10`, `BlackBerry 10`, `BlackBerry 7`, `OperaMobile 12.1`) を除外

これに『日本を対象とした利用統計で利用しているユーザーが0.5%超となったバージョン』 (`> 0.5% in JP`) を追加した条件を対応ブラウザの条件とするのはいかがでしょうか？

**Comment by kujirahand** [comment]
良いですね！ぜひやりましょう！
