### ISSUE TITLE
リポジトリに対するトピックタグの付与

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#197]
GitHubにはトピックタグ機能が存在するため (詳細: [GitHubにトピック（タグ）機能が追加されました - Qiita](https://qiita.com/howdy39/items/fe8b51ec042098587cf1))、これをこのリポジトリにも付与することで、より多くの人に存在を知ってもらえるのではないかと思います。

**Comment by kujirahand** [comment]
追加しました。
アドバイスに感謝！
