### ISSUE TITLE
Code Climateの導入

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#226]
『Code Climate』というサービスを利用すると、Github上の公開リポジトリのコードの品質をチェックすることができるようです。
なでしこ3のリポジトリに導入してみるのはいかがでしょうか？

<参考>
* [Code ClimateのCode Climate BadgeをGitHubに表示する方法 - Change the World!](http://changesworlds.com/2014/09/introduction-to-code-climate-and-github/)

**Comment by kujirahand** [comment]
さっそく試してみました。
https://codeclimate.com/github/kujirahand/nadesiko3

画面が変わってしまっている・・・どうやって、バッチを作るのかな？

**Comment by kujirahand** [comment]
それにしても、ファイル内のコードが長すぎるという指摘が多いけど、
あまりにも、ファイルを分割しすぎると、逆にメンテナンス性が低くなりそう・・・。

**Comment by massongit** [comment]
バッジはこちらで生成できます→ https://codeclimate.com/github/kujirahand/nadesiko3/badges
結構細かく分割させるようですからね.....

**Comment by massongit** [comment]
また、Code ClimateがPR作成時に実行されるようにするのもありかと思います ([Settings] - [Git repository] 内の Integration with pull request status update の横にある Connectをクリックすると有効になるようです)。
