### ISSUE TITLE
「々」を含む変数名が使えない？

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#232]
以下のプログラムでエラーが出ます。
```
々=50
```

**Comment by massongit** [comment]
『々』を漢字として認識するように修正しました。

**Comment by massongit** [comment]
【参考】
文字をUnicodeエスケープした際にどのような表現になるかを見る際には以下のサイトが使えそうです→ [[JavaScript]\uXXXX形式にunicodeエスケープする関数 / LiosK-free Blog](http://liosk.blog103.fc2.com/blog-entry-67.html)

**Comment by kujirahand** [comment]
感謝！
