### ISSUE TITLE
和暦変換

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#240]
v1の『和暦変換』関数を導入する。

**Comment by massongit** [comment]
[input type=dateで和暦（元号＋年）を表示する工夫 - Qiita](https://qiita.com/adonim312/items/d6f5e1e751882e9a221c)によれば、Dateクラスに和暦を表示する機能があるようですが、少し試した範囲ではmochaのテストで失敗します (ブラウザ依存？)。

**Comment by massongit** [comment]
CLI上でも使うことを考えると、v1の内部で参照している (と考えられる) 変換表を移植するのが良いということになるのでしょうか。

**Comment by kujirahand** [comment]
そうですね。変換表を使えば簡単に実装できそうですねー

**Comment by massongit** [comment]
明治以前の改元日は旧暦表記な場合が多そうなので、旧暦変換関数の実装も必要そうです。
