### ISSUE TITLE
エディタのダウンロードボタン

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#247]
エディタのダウンロードボタンを押すと、JSファイルがダウンロードされます。
しかし、WindowsだとデフォルトでWSHと関連付けられているため、正しく動かないと思われます。
そこで、バッチファイルとして出力してあげるオプションを作ると良いと思いました。

**Comment by massongit** [comment]
バッチファイルの代わりにJSを実行するHTMLファイルとして出力するというのもありな気がしますがいかがでしょう？

**Comment by kujirahand** [comment]
用途によって分けられると良いですよね。

- バッチファイル / Node.js用JavaScript / Electron用 / Web用ガジェットHTML

出力的にはヘッダを追加したりするだけなので、JSの幅広い用途に合わせられたらベストだと思います。とは言え、ダウンロードボタンのUIは、工夫しないと見栄えが悪くなってしまいますよね。

Pythonのブラウザ実行環境のJupyter Notebookとか、Google App Scriptのエディタとかがお手本になりそうなんですが、ファイルとか編集とか、画面上部に配置されていて、プルダウンで選べるようになってますね。個人的には、Jupyter NotebookのUIは、かなり使い勝手が良いと思ってます。

どちらにしても、UIを刷新して、利便性を向上させられたら良いですね。

**Comment by kujirahand** [comment]
ダウンロードは既に実装済み。
