### ISSUE TITLE
色定数の実装

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#26]
色定数に関してですが、type`const`として`PluginSystem`に追加すれば良いでしょうか？

**Comment by kujirahand** [comment]
Webブラウザ用のプラグインを作ろうと思いますので、そちらで定義していただければと思います。
これから、コミットしますね。

**Comment by massongit** [comment]
http://www.undefin.net/nadesiko/cg/lesson/L1-6.html
>「茶色」や「灰色」はありそうですが定義されていないので使えません。
 
を見て、色定数の数をv1よりも増やすのもありではないかと思ったのですが、どうでしょうか？ (個人的にはJSで色名が付いているもの (http://www1.kiwi-us.com/~mizusawa/penguin/html_hint/javascript/JAVAcolor.html) はある程度サポートしても良いのかなと思っています)

**Comment by massongit** [comment]
http://www.undefin.net/nadesiko/cg/lesson/L1-6.html
>「茶色」や「灰色」はありそうですが定義されていないので使えません。
 
を見て、色定数の数をv1よりも増やすのもありではないかと思ったのですが、どうでしょうか？ (個人的にはJSで色名が付いているもの (http://www1.kiwi-us.com/~mizusawa/penguin/html_hint/javascript/JAVAcolor.html) はある程度サポートしても良いのかなと思っています)

**Comment by kujirahand** [comment]
良い提案をありがとうございます。
WEBでは、いろいろな色が定義されていると便利なので、ぜひ、増やしましょう！

逆に、v1でも、あまり使われていなかったものは、v3で実装しない方向で考えています。
