### ISSUE TITLE
制御文の中括弧に関するコーディング規約を決める

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#315]
制御文の記述方法で意見の食い違いが発生しているため、このあたりのコーディング規約を決めた方が良いかと思います。
具体的には、ESLintのルール[`curly`](https://eslint.org/docs/rules/curly)のパラメータをどのような値に設定するかという形で議論するのが良いと思われます。

**Comment by massongit** [comment]
自分としては`all`に設定するのが良いと考えています。
理由としては、

```js
if (condition) process()
```

を

```js
if (condition) {
   process()
   process2()
}
```

のように書き換えたいと思ったときに、

```js
if (condition) 
   process()
   process2() // if文のブロックの中に入っているつもり (実際にはブロックの外)
```

という風に間違った書き方をしてしまうのを防ぐため、単文であっても、中括弧を付けた方が良いのではないかと考えているためです。

**Comment by kujirahand** [comment]
良い提案をありがとうございます！
特に、es-lintのオプションで語るのは良いですね。

とは言え、プログラミングコードの見やすさから言っても、断然、multiが良いように感じます。
- https://eslint.org/docs/rules/curly#multi

特に、forやwhileの繰り返しの中からの脱出で、条件が明確な場合に、脱出のif文が3行になると、めちゃくちゃプログラムが見づらくなるので。フォントのサイズを比較的大きくしてプログラミングしているので、とにかく、行数が少なくなり、見やすさが向上するのは、大歓迎です。

```
while (n > 50) {
    if (n === 3) break
    hoge
    hoge
    if (n === 47) return
    hoge
}
```

**Comment by massongit** [comment]
`all`にした方が良いと考えた理由で示したものについても、IDEの補完機能を使えば、ある程度防げるものではあるので、`multi`で良いのではないでしょうか。

**Comment by kujirahand** [comment]
なるほど、@massongitさんはIDEを利用していましたね。確かに、IDEを使えば、``all``を採用した場合にも自動でカッコ内を省略したりと、見やすくしてくれますね。私はIDEを使っていないので気づきませんでした。利用する環境に応じても、コードの記述スタイルの好みが反映されますね。

とは言え、JavaScriptをIDEで書く人は少数と思いますので、IDEを使わなくても見やすい``multi``でいきましょう！（最初から最後まで、強情ですみません。）

**Comment by kujirahand** [comment]
curlyをallに変更する
