### ISSUE TITLE
JSのイベントで、preventDefaultを実行できるようにしたい

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#326]
JSのHTML DOMイベントでpreventDefaultを呼べるようにする。

**Comment by massongit** [comment]
DOMイベント追加命令やDOMイベント発火時命令で、イベント呼び出し時にpreventDefaultを呼ぶかどうかを選択できるようにする感じですか？

**Comment by kujirahand** [comment]
そうですね。他に、キー押した時、キー離した時、マウス押した時、マウス離した時などなど、ですね。イベントが呼ばれた時に、イベント引数を覚えておいて、「DOM初期イベント停止」とか、分かりやすい名前で実装する感じです。
