### ISSUE TITLE
Gitterの導入

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#333]
[Gitter](https://gitter.im/)というGitHubのリポジトリに紐づけられるチャットツールがあるようです。
これを開発者用のコミュニケーションツールとして導入するのはいかがでしょうか？

**Comment by kujirahand** [comment]
一応、以下に作ってみました。

https://gitter.im/nadesiko3/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by kujirahand** [comment]
READMEに書いたので、閉じますね！
感謝。
