### ISSUE TITLE
『関数』から始まる変数が定義できない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#341]
0b94445a6e72872d86dbd69be708eb0184bb9b9a の変更において、関数から始まる変数名が定義できなくなっています。

「関数説明」とか「関数定義」という名前の変数を使っている、batch/pickup_command.nako3が実行できなくなりました。

関連 - #221

**Comment by kujirahand** [comment]
変数名に関数を含めることができないというのは、ちょっと理不尽な感じです。

引数に関数を取る場合、引数定義を「関数f」とするのではなく、v1互換で「{関数}f」と書くことにしましょう。

**Comment by kujirahand** [comment]
```
＃（1）の案
●({関数}aをbで)演算処理とは
  それは、a(b)
ここまで
＃（2）の案
●(関数 aをbで)演算処理とは
  それは、a(b)
ここまで
```

一晩考えたら、見た目的にも(2)の案が良い気がしてきました。

**Comment by massongit** [comment]
(2)案は『関数』と関数名の間に空白を入れる形だと認識していますが、初心者目線で見るとわかりづらいような気もします (日本語では分かち書きを行う習慣がないため、重要性が認識されづらいのではないでしょうか)。

**Comment by kujirahand** [comment]
それでは、v1に似せて、(1)の案で行きましょう。

**Comment by kujirahand** [comment]
こちら、作業しました。これからコミットします。
