### ISSUE TITLE
package.jsonのバージョン情報について

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#37]
`src/lang/package.json`内のバージョン情報に関してですが、`なでしこ3ベータx`というバージョンだった場合、`src/lang/package.json`の`version`の値は`0.0.x`となる、といった認識で合っているでしょうか？

**Comment by kujirahand** [comment]
そうですね。package.jsonのバージョンについては考えていませんでしたが、```0.0.x```とするのが良さそうですね。
