### ISSUE TITLE
デモページからプログラムを実行した際、ページ上に実行結果が表示されない

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#4]
デモページ ( `src/lang/demo/index.html`) でデフォルトのコードのまま『実行』ボタンをクリックした場合、『表示』命令の実行結果がデモページ内の実行結果欄ではなく、コンソールに表示されてしまいます。

<原因>
`src/lang/src/nako_gen.js`の`addPlugin`関数での`__varslist`への関数挿入  (65行目) の際に、 __関数への参照__ が挿入されています。
それによって、デモページ上のJavascriptによる『表示』命令で実行される関数の書き換え (11行目) が`src/lang/src/nako_gen.js`の`__varslist`に反映されなくなったことが原因と考えられます。

<解決策>
`src/lang/src/nako_gen.js`において、`__varslist`の役割の一部を`plugins`に担わせるということが考えられます (ただし、全体像を把握しきれていないため、本当にそれで良いのか自信がありません)。

**Comment by kujirahand** [comment]
いろいろと修正ありがとうございます。プルリクエスト、マージさせていただきました。
プラグインの機構については、まだ、試作段階なので、もうちょっと練っていこうと思います。
