### ISSUE TITLE
doc/plugins.mdの記述に関して

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#40]
doc/plugins.mdの『Webプラグインの追加手順』に関してですが、『script src="plugin_xxx.js で独自プラグインを読み込む』は『メインHTML (wnako3.jsを読み込んだのと同じHTMLファイル) で、独自プラグイン (plugin_xxx.js) を読み込む』ということで良いのでしょうか？

**Comment by kujirahand** [comment]
その通りです。リアルタイムコンパイルのために、プラグインファイルの読み込みが必要です。

（plugin_turtle.jsが、今のところ雛形になります。ー近々もう少し単純なものも用意します。）

ただし、今後、JSに変換済みのものに関しては、wnako.3.jsの取り込みも不要になる予定です。
