### ISSUE TITLE
グラフィックス追加

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#41]
#31 に関連して、[v1のチュートリアル](http://nadesi.com/doc/kouza/)で登場する『クジラ』や『ワニ』のグラフィックスを追加するのもありなのではないかと思ったのですが、どうでしょう？

**Comment by kujirahand** [comment]
それも良いアイデアですね！
v1のワニはヒドイと話題だったので、いくつか動物の画像をデザインの得意な方に依頼してみます。

**Comment by kujirahand** [comment]
とりあえず、マスコットの追加が容易な状態にできたので、Issueは閉じます。
