### ISSUE TITLE
なでしこのbnf

### ISSUE THREAD

**Issue by misogihagi** [kujirahand/nadesiko3#417]
どこかになでしこのbnfありませんか？仕様がわからなくて…
なければ自分で作ろうと思ってるんですけど…

**Comment by kujirahand** [comment]
なでしこ3を作ったばかりの時に、PEG文法で作っていたのですが、PEGJSの性能の問題で手動で書き直しているんです。BNF作ってもらえるなら嬉しいです！

**Comment by kujirahand** [comment]
nadesiko3go では、敢えてyaccを使ってみました。BNFを確認できます。
https://github.com/kujirahand/nadesiko3go/blob/master/parser/parser.go.y
