### ISSUE TITLE
配列に「代入」が出来ないようなのですが

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#434]
現象：「は」や「＝」による代入はモチロン出来るので即困るということでは無いのですが、「代入」による代入が出来ないようなのです。ご確認をお願いします。
再現方法：
#-----------------------------------------------
値段は空配列。
値段[0]は3000
値段[0]を表示。

値段[1]＝3000
値段[1]を表示。

値段[2]に3000を代入。  //これだけエラーになる。
値段[2]を表示。
#-----------------------------------------------
（ようやくここに書く術が分ったような気がしたので、なこ丼もなくなってしまったしと、思い切って書いてみましたが、コレで合っているでしょうか。また、v1のバグ掲示板のように、要望なども書いて良いのでしょうか？　ここは何だか、畏れ多くて...；）

**Comment by massongit** [comment]
自分の方で配列への代入ができるようにするPR (プルリクエスト, ソースコードの変更提案) を出しました。
再現方法が書いてあって原因特定や実装がしやすかったです。

**Comment by snowdrops89** [comment]
ありがとうございます！
いつも、素早い対応ですばらしいです！！
