### ISSUE TITLE
変数なのか関数なのか

### ISSUE THREAD

**Issue by misogihagi** [kujirahand/nadesiko3#443]
```
●テスト
それは５
ここまで
テスト＝８
テストを表示
```
以上を実行するとテストに代入された８が現れずに関数として呼び出され５が出力されます。
これを解決するには構文解析の時点で関数と変数を区別しているのをやめるところから始めるべきかなと思っています

**Comment by kujirahand** [comment]
関数の変数的な呼び出しは、とにかく非常に便利なので、なんとか解決方法を探る方向でいきたいですね。

**Comment by massongit** [comment]
関数の代入的呼び出し: https://nadesi.com/doc3/index.php?%E9%96%A2%E6%95%B0%E3%81%AE%E4%BB%A3%E5%85%A5%E7%9A%84%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%97%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6, https://github.com/kujirahand/nadesiko3/issues/290

**Comment by massongit** [comment]
引数が1つではない関数に対して関数の代入的呼び出し的な表記を行った場合、変数として上書きする、というのが矛盾が生じなくて良さげですね。

**Comment by kujirahand** [comment]
一応の解決を見ているので、閉じますね。問題的および解決ありがとうございました！！
