### ISSUE TITLE
空ハッシュ, 空オブジェクト追加

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#450]
NodeJSの `{}` に相当する定数 `空ハッシュ` を追加します。

**Comment by misogihagi** [comment]
名称ですが空オブジェクトでもいい気がします

**Comment by massongit** [comment]
nodejsに寄せて考えると、連想配列はオブジェクトの一部であり、 `{}` はオブジェクトの初期化で用いることから `空オブジェクト` と表現するのが妥当そうです。
ただ、なでしこ3に寄せて考えると、ハッシュの初期化を行う際に使うものとなるので、 `空オブジェクト` と `空ハッシュ` を両方用意するのが良さげですね。
