### ISSUE TITLE
色定数の表記ゆれに関して

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#46]
#26 関連

『赤色』->『赤』のように、『〜色』の『色』を外した表記を許容しても良いのではないかと思いますがどうでしょうか？

**Comment by kujirahand** [comment]
提案ありがとございます。
でも、なるべく、１文字の変数・関数をデフォルトで入れたくないので、色の揺れは、ナシで行きたいと思います。スミマセン。
1文字の変数は、ユーザーがよく使っていますので、空けておきたいんです。

**Comment by massongit** [comment]
了解しました。
