### ISSUE TITLE
命令の説明や詳細な解説をGit管理するように変更するかも？

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#473]
#469 のマニュアルの作成と関連して、命令の詳細な解説もGitリポジトリで管理した方が良いかも？と思い始めました。

それと同時に、なでしこ3の命令の解説をKonaWiki3に移行に移行すると良いかもと思いました。KonaWIki3ならばデータベースを利用せずテキストファイルがデータになるWikiなので更新管理やマニュアル化が容易。

そもそも、なでしこ3自身でWIKIを作ってどこかでホスティングさせるのは良い案かも。とは言え、今後のドキュメント管理に関する意見募集です。

**Comment by massongit** [comment]
KonaWiki3への移行を行う場合、 https://github.com/kujirahand/konawiki3/issues/3 の実現は必須な気がしますね (Gitへのコミットを自分で行わないといけないとなると、「Gitは詳しくないけれども解説を書きたい」という人の意欲を削いでしまうので)。

**Comment by misogihagi** [comment]
github pagesはどうでしょう。
リポジトリにはマニュアルのマークダウンとスタイルを置いておくだけです。
プルリクエストでコミットできて透明度が上がるのかなと思います。
多少フロントエンドの知識は必要ですが。。。

**Comment by misogihagi** [comment]
https://misogihagi.github.io/docutest/docs/doc1
一応突貫工事で作ったマニュアルです。
こんな感じで書けると思います。
https://raw.githubusercontent.com/misogihagi/docutest/master/docs/doc1.md

**Comment by massongit** [comment]
なでしこ3のユーザーの中にはGitには詳しくないけれども、マニュアルの編集はしたいユーザーが一定数いると考えられます。
これらのユーザーから見ると、GitHub PagesはGitを扱わないといけない点で敷居が高くなってしまうのではないかと思います (Gitを扱える人からすれば手軽にサイトを公開できて良いのですが)。

**Comment by massongit** [comment]
https://github.com/kujirahand/konawiki3/pull/5
Konawiki3でGitを使えるようにするPRを出してみました。

**Comment by kujirahand** [comment]
Konawiki3でGit使えるようにしてくださりありがとうございます！
とりあえず、nadesiko3docというマニュアル用のリポジトリを作りました。

- https://github.com/kujirahand/nadesiko3doc

それで、この後、今あるkonawiki2のデータをkonawiki3用に書き出してみようと思います。

**Comment by kujirahand** [comment]
既に運用開始したので閉じます。
