### ISSUE TITLE
ローカル変数定義を実装する

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#48]
まだ、未実装だったので、実装する。

-v1互換 「Ａとは変数」も良いけど、値の初期化が書きづらいので、JSっぽくして「変数のＡは３０」とか「定数のＡは５０」のように、初期化も自然にできる感じにするのはどうか。

**Comment by massongit** [comment]
『〜とは〜』と『〜の〜は〜』の両方に対応すると書きやすいような気がします (GUIのオブジェクトのように、一旦定義した後に『その〜=〜』でパラメータを設定していくような場合には、『〜とは〜』で定義できると便利だと感じるので)。

**Comment by kujirahand** [comment]
そうですね。v1互換も考慮して、両方定義したいと思います。
貴重な意見、ありがとうございます！

**Comment by kujirahand** [comment]
2349feee9c40ff5d5b0a1c32e0366cc43a490a48
で実装。
