### ISSUE TITLE
日付計算ライブラリ変更

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#481]
ref. #471

現状では日付計算ライブラリとして `moment.js`, `moment-timezone` を使っていますが、ビルド時のサイズ増加の大きな要因の一つとなっているため、より軽量なライブラリに変更します。

**Comment by massongit** [comment]
`day.js` が良さそう？
https://qiita.com/Ancient_Scapes/items/f5fbe7314c6f71a263da

**Comment by massongit** [comment]
`day.js` はデフォルトのタイムゾーンが設定できないのが難点

**Comment by kujirahand** [comment]
day.jsで良さそうです。
なでしこで、タイムゾーン指定する機会は、それほど多くないと思います（＾＾；
