### ISSUE TITLE
fetchを行うライブラリを統一する

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#487]
複数のfetchを行うライブラリ( `isomorphic-fetch`, `whatwg-fetch`, `node-fetch` ) に依存している状態なので、このうちのいずれかに統一します。

**Comment by kujirahand** [comment]
あ、勝手にアサインしちゃったんですが、良いでしょうか？もし良かったらお願いします。

**Comment by massongit** [comment]
やってみます

**Comment by massongit** [comment]
<各ライブラリの最終更新日>
isomorphic-fetch: 4年前
whatwg-fetch: 2年前
node-fetch: 13日前

node-fetchに統一するのが良さそう
