### ISSUE TITLE
README.mdの動的生成部分を分離する案

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#489]
README.mdに対応ブラウザが表示されるようになったのは、非常に素晴らしいことだと思います！

とは言え、比較的文面に修正がある、README.mdをテンプレートから自動生成するのは、テンプレートから生成することを忘れてしまって、README.mdを直接修正してしまうという、うっかりミスを誘発します。うっかり、何度かやってしまいました。そこで、対応ブラウザを表示する専用のページを作って、そちらへのリンクを追加して確認してもらう感じにしたいと思います。

ただし、それだと、せっかく正確に表示される対応ブラウザが探しづらくなってはいけないので、なでしこ3エディタに、対応ブラウザへのリンクを追加するなど、工夫を入れることでカバーできたらと思いますがどうでしょうか？

案としては、以下の手順で作業するのはどうでしょうか？

 - 1. README.md の動的部分を doc/browser.md に分離する
 - 2. package.jsonにある生成スクリプトを doc/browser.mdの生成スクリプトに修正
 - 3. なでしこ3エディタに、対応ブラウザへのリンクをつける
 - 4. マニュアルWikiおよび簡易エディタにも対応ブラウザへのリンクをつける

どうでしょうか？

**Comment by massongit** [comment]
確かにオペミス発生しやすいですよね...... (自分も間違えたことありますし)。
基本的に上記の方針で良いとは思うのですが、エディタからいきなりGitHubのページ ( `doc/browser.md` ) するのもアレなので、以下のようにするのが良さそうだと思いました。

1. `README.md` の動的部分を削除
1.  `package.json` にある生成スクリプトを `doc/browsers.md` (GitHubでの閲覧用) と `demo/browsers.html` (Webからの閲覧用) の生成スクリプトに修正
1. `README.md` に `doc/browsers.md` へのリンクをつける
1. なでしこ3エディタに、`demo/browsers.html` へのリンクをつける
1. マニュアルWikiおよび簡易エディタにも `demo/browsers.html` へのリンクをつける

**Comment by massongit** [comment]
さらに言えば、cnako3に対象ブラウザを表示するオプションを追加して、 `doc/browsers.md` を表示しても良いかもしれませんね ( `doc/browsers.md` はテキストとして読んでも可読性のある形式になるはずなので、そのままCLIに流す形です)。

**Comment by kujirahand** [comment]
良いですねー。そんな感じでいきましょう！
cnako3のCLIに表示するのも、良いアイデアと思います。

**Comment by kujirahand** [comment]
Pull Requestにコメント書いたのですが、一度マージするとクローズしたのと同じになってしまう感じですね。コメント再掲します。すみません。

上記のコミット、良い仕事ありがとうございます！

せっかく先日ライブラリをスリムアップしたので、対応ブラウザ表示だけは、外部リンクを表示するようにして、マークダウンとHTMLのライブラリは、外部プラグインで対応できるようにしませんか？

せっかく対応していただきましたし、かなり需要があると思いますので、plugin_markdown.js を新設して、状況に応じて取り込んで使えるようにする感じです。plugin_turtle.jsと同じ扱いです。

**Comment by massongit** [comment]
別のプラグインに分離するPRを出しました: https://github.com/kujirahand/nadesiko3/pull/492

**Comment by kujirahand** [comment]
素晴らしいです！
