### ISSUE TITLE
HTMLへの埋め込みがうまくいかないように思われます

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#497]
現象：公式ページの「HTMLへの埋め込み方法」の通りに行っても、動作しないように思われます。
再現：https://snowdrops89.github.io/test/v3_0_72_test.html
　スクリプトの取込部分は、「利用準備」のコード部分のコピペですが、「こんにちは」と言ってくれません。
　これは、このまま取込部分をv3.0.70に変えることで動作する事を確認しており、文字コードがっ…等の事件ではないものと思います。
　もちろん、簡易エディタ等ではv3.0.72の機能を利用出来ています。
　ずっと以前もあったHTML取込だけうまくいかない事件なのか、今回からスクリプトの取り込み先が変更になっているので、単にここに記述ミスがあるのか、わたしにはちょっと分かりかねますが、ご確認をお願いいたします。

（あと、ナデシコと言うよりサイトのことですが、「具体例」のところをクリックすると、HTMLが開いて、動作の確認が出来ない感じになってしまっています）

**Comment by massongit** [comment]
`https://nadesi.com/v3/cdn.php?v=3.0.72&f=release/wnako3.js` は `https://cdn.jsdelivr.net/npm/nadesiko3@3.0.72/release/wnako3.js` にリダイレクトされますが、これを `https://cdn.jsdelivr.net/npm/nadesiko3@3.0.72/release/wnako3.js?run` に置き換えると正常に動作します。
したがって、 `https://nadesi.com/v3/cdn.php` のパラメータに `run` を取れるようにして、 `run` が付いている場合はリダイレクト先のURLにパラメータ `run` を付与するようにするのが良さそうです。

**Comment by kujirahand** [comment]
以下のように修正しました！
ご報告および、修正方法の指摘、ありがとうございました！

 - https://nadesi.com/doc3/go.php?22
