### ISSUE TITLE
CI導入

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#505]
CIを導入し、PRやコミットが投げられた際にテストが通るか確認するようにします。
GitHub Actions ( https://github.co.jp/features/actions ) はパブリックリポジトリなら無料なので、これを使うと良いかと思います。

**Comment by kujirahand** [comment]
GitHub Actions設定してみました。

**Comment by kujirahand** [comment]
1ed725e59ed2706e69ec1801511fb65addc03e9b
