### ISSUE TITLE
HTML埋め込み時のタートルグラフィックスが動きません

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#537]
公式ページのHTMLへの埋め込み方法の通りにタートルグラフィックスのプラグインを取り込んでもうまく動作しないようです。
再現：https://snowdrops89.github.io/test/turtle_test_3_1_0.html

ちなみにこれは、タートルグラフィックスのプラグイン取込部分だけ、v3.0.70のにすることで動きます。
https://snowdrops89.github.io/test/turtle_test_3_0_70.html
ので、取込方法の問題かと思うのですが、ご確認をお願いします。

**Comment by weyk** [comment]
少し試したので記載。

Edgeのパフォーマンスモニターをオンにして試したところ、307のLocation以降からそれにより読み込んだJavascriptを実行するまで、間があるようです。
3_0_70の方は、turtoleのタグでRedirectされないので、htmlの読み込み途中でhtml解析が中断され、その場で実行されていて、その後、DOMContentLoadedにて、wnakoが動いているのように見えました。
対して、3_1_0の方は、wnakoとturtleの両方がRedirect後、wnakoが読み込まれてturtleが読み込まれて、wnakoが実行された後でturtleの実行の前にDOMContentLoadedが発火して、pluginに定義のある命令が文法エラーになっているようです（plugin_tutrleが実行されてないので、追加命令が存在しない）
※ネットワークモニタで見ると、plugin_tutleのdownloadはされている。
デバッグタブで見ても、wanako.jsは出てくるものの、plugin_turtle.jsは出てきませんでした。

DOMContentLoadedって、そんな仕様(307を挟むとhtmlのDOMContentLoadedの範疇から外れる）なんでしたっけ？
onloadにするとか、setTimeoutを経由すると動くかも　ですが、根本対策とはちょっと違う感じです。

**Comment by massongit** [comment]
```html
<script type="texrt/javascript" src="https://nadesi.com/v3/cdn.php?v=3.1.0&amp;f=release/plugin_turtle.js"></script>
```

`type="texrt/javascript"` の部分でtypoしていますね (正しくは `type="text/javascript"` )。

**Comment by massongit** [comment]
https://snowdrops89.github.io/test/turtle_test_3_1_0.html のHTMLをコピペし、上記のtypoを修正したところ、正常に動きました。

**Comment by snowdrops89** [comment]
ほんとだ！　全然気付きませんでした(/ω＼)
修正して、無事出来るようになりました！
ありがとうございます☆

ちなみにこれ、公式ページのHTMLへの埋め込み方法の自体がアレしてまして、wikiのとこじゃないので私には修正できませんので、権限のある方によりシュッと修正して置いて頂ければと思うところです。
https://nadesi.com/doc3/index.php?HTML%E3%81%B8%E3%81%AE%E5%9F%8B%E3%82%81%E8%BE%BC%E3%81%BF%E6%96%B9%E6%B3%95

**Comment by massongit** [comment]
@kujirahand 修正の方お願いします。

**Comment by kujirahand** [comment]
わっ、タイポが原因だったなんて。お恥ずかしい😔
修正しました。皆さん、ご協力ありがとうございました！！
