### ISSUE TITLE
「今日」「明日」などを（）で括らないと「＝」での代入が出来ないのは仕様ですか？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#545]
「今日」「明日」などを使用した命令文が、表示や「代入」での代入は普通にできるのですが、「＝」や「は」で代入しようとすると、文法エラーとなります。
色々試した結果（）で括れば行けると言うことが分かりましたが、違和感が否めない気がして、ｖ１では全て問題のない構文なので、何とかなればなあと思うところです。

再現：
#-----------------------------------------------
今日の曜日番号取得して表示。

#『A』への代入文で計算式に以下の書き間違いがあります。
//A=今日の曜日番号取得。Aを表示。 //エラー出る。
A=(今日)の曜日番号取得。Aを表示。 //できる。

//Aは、今日の曜日番号取得。Aを表示。 //エラー出る。
Aは、(今日)の曜日番号取得。Aを表示。 //できる。

今日の曜日番号取得してAに代入。Aを表示。 //できる。

#(...)の解析エラー。『今日』の近く。
//(今日の曜日番号取得)+1を表示。 //エラー出る。
((今日)の曜日番号取得)+1を表示。 //できる。
#-----------------------------------------------

**Comment by weyk** [comment]
参考までに。

現在、以下の２点がうまくいってないみたい。
・引数を取らない命令の扱い。直後に演算子が続いたり行が終わらないと変な解析経路に入ってエラーになる。
　１語命令の次が助詞や後続の命令のための助詞だと、１語命令として解析できず失敗する。
　→後ろに()を付けて関数と分かるようにするとマシになる
(今日()の曜日番号取得)+1を表示
・全体を囲う()などが無い数式の途中に命令があると、数式の扱いが途切れてしまう
　複数命令として「して」でつなげらられるけど、数式としてつながっているわけではない
今日の曜日番号取得して、それ＋１を表示

**Comment by massongit** [comment]
修正のPRを出しました。

ちなみに以下のように書くと、

\`\`\`
A=今日の曜日番号取得。Aを表示。
\`\`\`

コードっぽく表示されたりします。

```
A=今日の曜日番号取得。Aを表示。
```
