### ISSUE TITLE
「日時差」が動かないように思います

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#549]
ｖ１には無い命令で、私が間違っているのかも知れませんが、おそらくこういうことだろうと思ったのですが、動かず。

```
「2020/07/17 00:00:00」と「2020/07/18 00:00:00」の「時間」による日時差を表示。
```

[文法エラー](1行目): 『「2020/07/18 00:00:00」の』『「時間」に』『よる日時差』がありますが使い方が分かりません。 [バージョン] 3.1.2

というエラーになります。

素人考えでは、助詞の一覧に「による」は無かったので、そのせいかしらと思ったり……？

**Comment by weyk** [comment]
本体の助詞リストに「による」を追加すると動くので、推測通りで間違いなさそうです。
（自サイトのESモジュール版のほうで試しました）

と、すると、もし、標準でも外部でもplugin_*の命令の助詞として指定されているものが、本体の助詞リストにないと、エラーとなるのだとすると、以下のいずれかにした方がよさそうです。
・pluginから命令を取り込む際、本体の助詞リストにない助詞が含まれていたら、取り込み自体をエラーにする。
・追加する命令で指定された助詞は本体の助詞リストに動的に追加する。

どちらにしても一長一短ですが、plugin作る人が少ないなら、大差はないですね。

**Comment by massongit** [comment]
とりあえず `日時差` の助詞周りを修正するPRを投げました。
うぇいくさんの提案については別Issueにしました: https://github.com/kujirahand/nadesiko3/issues/551
