### ISSUE TITLE
ホットキー登録がエラーになります

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#553]
みなさんいつもありがとうございます！
素早く対応して頂き気付いたらもうクローズになっててなかなかお礼も書き込めずスミマセン＞＜

**現象：**
ｖ１互換であれば、このようなコードとなるかと思うのですが、エラーとなります。
ご確認をお願いします。

```
「a」に「挨拶」をホットキー登録。

●挨拶
　「こんにちは」と言う。
ここまで。
```

**エラーコード：**
[実行時エラー] 関数『ホットキー登録』:TypeError:u is not a function

**Comment by weyk** [comment]
ちょっと調べてみました。

ここでエラーになっているuとは、hotkeysをrequireした返り値です。
このパッケージは、メインの機能の関数のプロパティに追加のAPIの関数を生やしている形をしています。
実行のエラー時、ブラウザで覗いてみると、esModuleのような形式になっていて、
・メインの関数は、defaultの配下にいる
・そのほかは、通常通り
という形に変形してしまっています。
上記をどう直すのが良いのかはわかりませんが、代案としては、もともと、hotkeysは、ブラウザで
実行した場合、windowsにhotkeysというプロパティを生やしてそこにも居座ります。
なので、
・hotkeysのrequireは、結果を受け取らない。
・呼び出しは、window.hotkeysを利用する（const hotkeysが消えれば、自然とこちらが呼ばれる）
がわりと単純です。
実行時のグローバル変数の探索コストと、hotkeysの名称が短縮化(上記でのu)されないという微妙なデメリットはあります。
