### ISSUE TITLE
ES Modules対応

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#562]
https://qiita.com/shimataro999/items/8a63ec06f33ccd2ea9ca

Node.js v12におけるES Modulesの記述方法に対応させます。

**Comment by kujirahand** [comment]
よく読んでみたら、`CommonJSでは、これまで通り拡張子を省略できる`とのことですね。
観測的にも、CommonJS形式はこれまで通り使えるのではないかとのこと。なので、現状で、ライブラリをES Modulesに対応させるメリットが、あまりないのではと思います。

**Comment by massongit** [comment]
改めて調査し、修正のPRを投げました: https://github.com/kujirahand/nadesiko3/pull/569
調査結果もPRに書いてあります。
