### ISSUE TITLE
demo/index.htmlのテストボタンの使い方が分からない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#566]
@massongit すみません。今更ですが、素晴らしい機能ありがとうございます。

ただ、テストボタンをどのように使ったら良いか、分かりません。
どこかに、利用するサンプルありますか？

エディタの[❓]ボタンを作って、使い方のヘルプが出るようにすると良いと思います。

**Comment by massongit** [comment]
こちらのPRに書いてある説明を見ていただければ、一旦はわかるかと思います。
https://github.com/kujirahand/nadesiko3/pull/396

ヘルプが出てくるようにするのはアリだと思います。

**Comment by kujirahand** [comment]
@massongit どこかで見たと思っていて、#396 でしたか！
早い返信ありがとうございます。

**Comment by kujirahand** [comment]
連続で「テスト」ボタンを押すと以下のエラーがでます。

```
Error:Mocha instance is already disposed, cannot start a new test run. Please create a new mocha instance. Be sure to set disable `cleanReferencesAfterRun` when you want to reuse the same mocha instance for multiple test runs.
```

**Comment by massongit** [comment]
エラーの件を別Issueに切り分けました: https://github.com/kujirahand/nadesiko3/issues/579

**Comment by kujirahand** [comment]
こちら、ありがとうございました！
簡単な説明も付けたので閉じます。
