### ISSUE TITLE
plugin_testの「なる」が一般的な動詞すぎる

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#568]
plugin_testに「なる」という動詞がありますが、一般的な動詞すぎるので、別名にできたらと思います。
「ASSERT等」が、タイプしにくいのがそもそもの問題でしょうか。

以下の命令はどうでしょうか？

 - AとBでテスト実行。🌟
 - AとBをテスト確認。
 - AがBとテスト等しい。
 - AとBをイコールテスト。
- AとBがテスト正しい
- AとBがテスト異なる

「AとBでテスト実行」が一番しっくり来るでしょうか。

**Comment by massongit** [comment]
`AとBでテスト実行` だと等しいというニュアンスが伝わらないので、 `AがBとテスト等しい` の方が良いかもしれないです。

**Comment by weyk** [comment]
条件（等しいとか異なるとか）は、命令につなげず、引数にする方が自然になるとも思います。
Objectが無く、また、引数の型による多態が無いためか、
命令語がかなり日本語として怪しくなってます。
AとBを「等値」でテストする
とか。enumのように、
AとBを等値でテストする
のように書けるとよいのですが、うまい方法が思いつきません。
（なでしこ１の変数宣言を必須にせず、同値の文字列として扱われる仕様も混乱の元なきがしますし）

**Comment by kujirahand** [comment]
ちなみに、思い出してv1を見ると`テスト実行`を採用していましたね。

- https://nadesi.com/man/index.php?%E3%83%86%E3%82%B9%E3%83%88%E7%B5%90%E6%9E%9C%E5%8F%96%E5%BE%97

v1のtestフォルダを見ると、かなりたくさんのテスト実行の例があります。
英語でもよくあるassertコマンドなども、等しいというニュアンスはそこにないので、その辺りは、こだわらなくても良いかと思います。テスト書くときは、等しいか等しくないかのチェックが大半と思いますので。

**Comment by weyk** [comment]
mochaとassertでやってますが、chaiとかのテスト見るとassertよりも解り易いなぁと感じています。
決め打ちのルールを覚えてしまえば、書く側は、assertのが楽かもしれません。
（いまだに、「assertって、真と偽とどっちで止まるんだっけ」という覚えぐわいですが）
とりあえず、命令いちいち調べずとも、ソースをみて何やっているか読み取れるというのが、
人のソースを読むにしろ、過去の自分のソースをいじるにしろ、誰かのソースをもとに
改造したものを作るにしろ、使いやすいと思っています。初見で知らない単語（命令）で
動きの予測ができないものが並ぶと、実際以上に複雑に見えるというのもあると思っています。

が、単に私の考えなので、忘れてください。v1にあったのなら、
v1と同じに、なでしこ流の命令語が良いのではないでしょうか。

**Comment by kujirahand** [comment]
とりあえず、v1互換で、「テスト実行」を導入してみます。
とは言え、「AがBとテスト等しい」もエイリアスで追加することで、より分かりやすくなるでしょうか。

**Comment by kujirahand** [comment]
コミットするとき、入れ忘れました。

72a02080710650d7ef993278d8e13158eae02e82
