### ISSUE TITLE
タートルグラフィックスでゾウとパンダが表示されません

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#587]
お疲れさまです☆
「ゾウ作成」「パンダ作成」をしても、画像が表示されないようです。
普通に考えると、これで出来ると思うのですが（カメ作成のデモの作成部分だけゾウに変えた物）
```
N=50
ゾウ作成
12回
　　Nだけカメ進む
　　90だけカメ右回転
        N=N+10
ここまで
```
パンダも同様です。
動作はするので、画像が引っ張れていないだけだと思うのですが。

画像そのものは存在していて、
```
カメ画像URL=「https://nadesi.com/v3/cdn.php?v=3.1.2&f=/demo/turtle-elephant.png」
カメ作成
```
とすれば、ゾウさんで出来ますので、なんかパス的な？？（超素人考え；）
ご確認をお願いいたします。

あっ、あと、マニュアルのデモでは、「カメ作成」もカメさんが表示されておりません。

**Comment by weyk** [comment]
ふと思い当って、ちょっと調べました。

requestは、htmlが起点になるので、
「GEThttps://nadesi.com/doc3/turtle-elephant.png」
というrequestが発行されていて、結果、画像ファイルが無くて404でエラーになっています。
単純には、doc3配下にゾウとパンダの画像ファイルの設置漏れ　と思われます。
自身のurlを基準にurlを補正して、参照するのも手なんですが、利用者(設置者)がどうファイルを配置してくれるのかはわからないという問題もあります。
plugin_turtle.jsを単体で手軽に使えるようにという点を考えると、カメの画像も含めて、data urlにしてjs内に埋め込んでしまうのも手と思います。
