### ISSUE TITLE
「カメ移動」した時の、カメの向き

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#588]
普通に考えると、カメが移動したら進行方向を向くのが自然、あるいは、進むとは違ってカメの向きは変わらない、ということなら分かるのですが、どうも、横に進むと進行方向に対して右回転、縦に進むと左回転した状態で表示されます。なので、45度の角度ならば進行方向（または逆）になりますが、それ以外の角度だと、あらぬ方向を向くのがどうにも気になるというか……？
```
カメ作成。500にカメ速度設定。
[100,0]へカメ起点移動。
[100,100]へカメ移動。
[0,100]へカメ移動。
[100,0]へカメ移動。
[200,50]へカメ移動。
```

**Comment by weyk** [comment]
ちょっとだけ現象を確認しました。
現象というか原因ですが、移動命令により移動した際、起点の座標と移動先の座標から、そのベクトルに従い移動後のカメの向きを算出しているんですが、算出する際の、atan2の引数の順番が逆です。
誤：Math.atan2(x,y)
正：Math.atan2(y,x)
そのため、例えば、右に進んだ場合、右は+xの方向ですが、x,yの扱いが入れ替わっているので、+yの方向(下)を向いてしまう　ということのようです。

**Comment by snowdrops89** [comment]
ご確認ありがとうございます☆
なるほど！　わたしにしては珍しく（？！）完全に理解しました。
そういうコトであれば、簡単に直りそうですね＾＾
