### ISSUE TITLE
「ここまで」を打つのがだるいと感じる人に解決策を考える件

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#596]
2020/12/24
プログラムの冒頭に「!インデント構文」あるいは「!ここまでだるい」と書くと、
インデント構文として使えるようにプリプロセス処理を実行するようにしました。

使い勝手求む。

```
!ここまでだるい
3回
　　3回
　　　　「だるい」と表示。
```

上記のように書くと9回だるいと表示されます。

-----------
# 元々の議論:

#306 のインデント構文も考察しつつ。

`句点「。」を「ここまで」と同義にするのはどうか`という案がここに来て急浮上中で議論したいです。

たしかに、改行でも文を区切ることができるので、わざわざ句点を打つ必要はありません。そこで、「。」を打ったときは「ここまで。」と同義でも行けそうな予感もしています。

```
もし、AがB以上ならば
　　「A」と表示
違えば
　　「B」と表示
ここまで
```

これの「ここまで」を「。」と同義にすると・・・

```
もし、AがB以上ならば
　　「A」と表示
違えば
　　「B」と表示。
```

とか

```
●(AとBの)加算処理とは
　　それはA+B
。
```

など。

うーん。思いつきは良かったけど、やはり、ちょっと日本語として意味が読みづらいかも？？？

**Comment by kujirahand** [comment]
なお、プロデルのように「おわり」を使うのは論外。日本語として破綻してるので。

**Comment by kujirahand** [comment]
それでも、「ここまで」を「。。。」で置き換えられれば、それなりに見られるかも？？？

```
もし、AがB以上ならば
　　「A」と表示
違えば
　　「B」と表示
。。。
```

やはり却下。これなら、以前廃止した「---」をここまでと同義にするのと同じで、あまりよろしくないです。

**Comment by massongit** [comment]
インデントを使うのであれば、エディタ上でタブが入力できるようにする必要がありますね。

**Comment by eznavi** [comment]
一番良いのは、大変ですが、インデント有無併用できるのがうれしいですね。
インデントでPython風に「：」も良いですね、なでしこから旅立つ人のためにメジャー言語に近いものにしたいですね。

**Comment by kujirahand** [comment]
とりあえず簡単な解決案で「ここまで」と「🐟」を同意にするのは面白いかなと思っています。

```
もし、A＝Bならば
　　「等しい」と表示
違えば
　　「違う」と表示
🐟
```

**Comment by eznavi** [comment]
絵文字いいですね。１文字ですからね。
なでしこの絵文字があれば良いですが・・・。

**Comment by kujirahand** [comment]
ここまで議論してきて、普通にインデント構文を使いたい時は、何かしらモードで切り替えられるようにしたいと思います。
プログラムの冒頭に「##インデント構文」あるいは「##ここまでだるい」と書くと、インデント構文として使えるようにプリプロセス処理を実行するようにしたいと思います。
プリプロセス処理では、単純にインデントの段が下がるところに「ここまで」を挿入するだけで、なんとかなると思います。

**Comment by kujirahand** [comment]
文法/インデント構文
https://nadesi.com/doc3/go.php?16403

使い方をWikiにまとめました。

**Comment by kujirahand** [comment]
実装済み、閉じます。
