### ISSUE TITLE
NakoGenのc_let関数について

### ISSUE THREAD

**Issue by massongit** [kujirahand/nadesiko3#60]
NakoGenのc_let関数において、変数is_topが`true`で初期化されていますが、これは正しいのでしょうか？

**Comment by kujirahand** [comment]
変数is_topはtrueで正しかったのですが、
システム変数が更新できないバグがあったので( 2c03349e69b55b78ac1d78f565ba1977a76bee84 )
明示的に初期化せず、その後の、if文で初期化するように修正しています。
ご指摘、ありがとうございました。
