### ISSUE TITLE
HYPOTの価が？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#603]
数学が壊滅的にアレなので何なのですが、底辺と高さから斜辺を求めるヤツですよね？
底辺の２乗＋高さの２乗のルートで、１と１ならヒトヨヒトヨになるものだと思うのですが、１になってしまいます。

**再現方法:**
```
1と1のHYPOTを表示。
HYPOT(1,1)を表示。
```
ｖ１では、1.4142135623731となります。

**Comment by kujirahand** [comment]
v3.1.3で修正済み
