### ISSUE TITLE
算術関数や三角関数の日本語命令

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#604]
ｖ１にはあったような、例えば先のHYPOTなら「斜辺」というような、日本語での命令の実装はないのでしょうか。
個人的な要望で言うと、「符号」と「絶対値」と「小数部分」が欲しい！　です。
毎回、わざわざ変換する関数を貼っ付けるんです（笑）
余弦とか正弦とかは、私は使って無いのですが、可能な限りはｖ１と同じように記述出来るとうれしいです。

**Comment by kujirahand** [comment]
#581 で追加する

**Comment by snowdrops89** [comment]
ありがとうございます！！
