### ISSUE TITLE
Error: Cannot find module 'electron'

### ISSUE THREAD

**Issue by kna** [kujirahand/nadesiko3#607]
なでしこのパーサーをモジュールモードで使おうとしているのですが、
現時点の最新版(v3.1.2)では以下の問題があります。

- `src/index.js`からelectronが呼ばれますが、
  electronがdependencyにないため、読み込みに失敗します(`Error: Cannot find module 'electron'`)。
  こちらからも確認できます。https://npm.runkit.com/nadesiko3

- 回避策として、モジュールを使う側がelectronをdependencyに追加することができますが、
  使う側の最終的なアーカイブにelectronが含まれるのでとても大きくなってしまいます。

このため、この問題の無いv3.0.69を使っています。

できればモジュールモードで使うときはelectronを不要にできると嬉しいです。

#518 などでレポジトリを分けることも検討されているようなので、その一環で解決されるかもしれませんが、
要望としてあげさせていただきました。

**Comment by kujirahand** [comment]
以下にて、Electronをindex.jsから外しました。RunKitでも動くようになりました。
a49d93bb0938068d082aa982190370419518cba9

**Comment by kna** [comment]
ありがとうございます。
こちらでもモジュールモードでelectronなしで動くことを確認できました。

**Comment by kna** [comment]
ここで修正いただいたものも利用して、vs codeの拡張をすこし作ってみました。
https://github.com/kna/nadesiko3-vscode-extension

継続して開発する予定はないのですが、ご参考までにお伝えします。
