### ISSUE TITLE
npm testが通らない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#61]
Pull requestsをマージした後で気付いたのですが、
どこかの修正が問題で、現在、npm test でエラーが出ます。

func_testのテストで「実行時エラーTypeError:Assignment to constant variable.」と出て、問題が出ています。

**Comment by massongit** [comment]
修正を行いました (コミット前にtestを実行するのを忘れないように気をつけたいと思います)。

**Comment by kujirahand** [comment]
いつも、リファクタリングありがとうございます！！
