### ISSUE TITLE
尋ねるの数値変換が不完全

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#616]
なでしこ３の「尋ねる」命令
数値変換するどうかの正規表現がわりと適当で、「1.23」や「1...3」が数値の1になってしまったり、「-123」は文字のままっだりするので直す。

**Comment by weyk** [comment]
テスト書いてる時に気になったまま、放置していたのですが、"9007199254740992"のような入力はどうしましょうか？
あまり細かく正確に動作するとしても、おそらく、ユーザも良くわからないという可能性も高そうです。
（9007199254740991は数値が帰るのに、9007199254740992は文字列になる　とか）
別途、どんな入力でも変化しないほうが良い場合は、「文字列尋ねる」用意して、そちらを使ってもらいますか？
※9007199254740992は、javacriptで正しく扱える正の整数の値プラス１。つまり、精度の制限で表現できない数値。

**Comment by kujirahand** [comment]
次のような解決策にしましょう。

 - [1] 「尋ねる」命令は互換性を重視＞数値判定の正規表現をもう少し厳しくする
 - [2] 型変換を強制しない「文字列尋ねる」を追加する

**Comment by snowdrops89** [comment]
ｖ１では、数字を全角で入力しても数値として認識してくれましたが、ｖ３では文字列となってしまうようです。
できればこのあたりもｖ１互換にしていただけると嬉しい感じです。
