### ISSUE TITLE
【要検証】Googleスプレッドシートのマクロでなでしこが使える？！

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#629]
最近、スプレッドシートのマクロがV8エンジン対応になった。
もしかすると、スプレッドシートのマクロもなでしこで動かせる？！
検証してみる。

**Comment by massongit** [comment]
MS Office連携に似た感じの機能になりそうで良いですね。
アドオンを作って公開、みたいなことも可能かもしれません。

**Comment by kujirahand** [comment]
調べてみた感じ、スプレッドシートのマクロ Google Apps Scriptでは、require や import は使えないっぽいです。
TypeScriptもローカルでコンパイルしたのを使うような感じみたい？

 - https://developers.google.com/apps-script/guides/typescript

いずれにしても簡単にできそうにないとのことで、ちょっと残念です。

wnako.jsを丸ごとコピペすれば使えるかな？

**Comment by massongit** [comment]
webpackで固めたものをアップすればその辺りはクリアできそうな気がします。

**Comment by kujirahand** [comment]
結局使えないという結論。残念。
