### ISSUE TITLE
スクロールした時にタッチYの位置がずれる

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#634]
マウスは大丈夫なのですが、タッチの場合、スクロールした状態でタッチをすると、スクロール分だけタッチYの位置がずれます。試していませんが、横にスクロールしていた場合は、同様にタッチXの価がずれるものと思います。

**再現方法：**
（タートルグラフィック用あたりでお試し）
```
[100,100]へ10の円描画。
「タッチX：100 , タッチY：100」のラベル作成して、座標確認へ代入。

描画中キャンバスをタッチ開始した時には、
　[タッチX,タッチY]へ10の円描画。
　座標確認へ「タッチX：{タッチX} , タッチY：{タッチY}」をテキスト設定。
ここまで。
```
スクロールなしで[100,100]の印をタップすれば、大体その辺りになりますが、少しスクロールして同じ場所をタップすると、マウスYの価が変わり、円描画もずっと下の方になされます。

タブンですが、タップの位置はウェブページのトップからの距離で取得され、そこからDOMの位置との差でイベントのDOM内のX,Yを算出されているんだけど、DOMの位置が、ブラウザ画面の上端からの距離になっちゃっているのではないでしょうか。（素人考え）
ご確認をお願いいたします。

**追記：**
マニュアルのデモでは、スクロールしていても正常に動いているので、もしかしたら違うかも知れません・・・
しかし、簡易エディタや、HTML埋め込みで試した場合には、こうなります。

**Comment by weyk** [comment]
イベントでは、以下の３種類の座標が取れるんですが、
screenX/screenY（モニター上の座標）
pageX/pageY（ブラウザで見えて無い範囲を含めたページ内での座不応）
clientX/clientY（ブラウザで見えている範囲の座標）
タッチイベントでは、今はpageX/pageYを参照してました。
マウスイベントでは、clientX/clientYを利用しているので、タッチベントでも
現在のpageX/pageYをclientX/clientYに修正すれば、正しくなりそうです。
※なでしこでは、イベントターゲットの矩形の分を引いて相対位置にしています。
ただし、イベントターゲットが一部や全体が隠れている時に正しい値が返せるかは、
確認が必要そうです。

マウスイベントも同様ですが、この座標は、必ずしもイベントターゲットの大きさの範囲に
収まっているわけではないので、利用の際は注意が必要です。
（ドラッグを続けている間は、元の要素の範囲を外れてもイベントを受け取り続けるため。
　開始の時点では、マウスイベントでは必ず対象の要素の上です。タッチイベントの開始は、
　必ずしも対象の要素の上とは限らないという仕様だそうです。）

なお、Firefoxをデスクトップで使用している場合、touchイベントそのものが発火しなかったり、
古い形の、ontouch*で始まるpropertyによるイベントハンドラがlegacy扱いで既定では無効に
なっていたりするので、さすがに、もう、addEventListenerに書き換えた方がよさそうです。
（有効にするには、メニューから開くオプション画面ではなく、about:configから変更する
　必要がある模様）
