### ISSUE TITLE
ブラウザ系pluginのテスト

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#651]
ブラウザ用pluginのうち、browserとturtleのテストをブラウザ上で実行するテストの件です。
手元では、
・ブラウザのランチャとしてkarmaを使用。e2e用途のツールと違い比較的簡単。
・karmaではテストするもの(テスト＋テスト対象)を１ファイルにバンドルする必要がある。今はkarma-webpackを使用。
・とりあえず、対象ブラウザは、Firefoxのheadless。
・テストフレームワークは、testでも使用してるmocha+assert(のbrowser用polyfill)。
・alert/confirm/prompt等はtestdoubleでstub化する。
という感じです。
test_browserというフォルダにして、testと区別して配置予定。
従来のtestはnode用で、nodeのmochaで動かすものを入れるということで使い分ける。

準備が整ったら、このissueに紐づけてPR予定。
気になっているのは、karma-webpackが一向にwebpack v5対応しないこと。別のバンドラ使うのも悩ましい。
（karma-webpack@4からwebpack@4にpeerDependencyになっている）
※browser/turtleのすべての命令の網羅は未。またあとで・・・

**Comment by kujirahand** [comment]
こちら既に実装済みですね。素晴らしいです！
お疲れ様でした！
