### ISSUE TITLE
バンドルしたファイル自体のテストを考える

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#652]
webpackの更新(v5)とreactの更新(新トランスれた)もあるので、バンドル済みファイルの動作テストが欲しいと考えています。
少し用途が異なるものの、karmaにハンドラを追加してテスト用htmlを入れ替えたりすることで、ブラウザからバンドル済みファイルをscriptタグで読み込んだ状態にはできると踏んでいます。
網羅的な動作のテストは、test/test_browserにて一通り行われている前提なので、あくまでも、webpack/babelによるバンドルがうまくいっているかどうかの確認が目的になります。webpack自体は正常終了している前提なので、あまりエラーとなるケースは無いのかもしれません。また、エラー発生タイミングも、webpackやbabelの設定を触ったときぐらいしかないので、「忘れたころの災害に備える」という感じです。
（が、jsxからimport reac from "react"を消すて、clasicなトランスれたで変換すると、結構簡単に実行時のエラーになります。新とらんすれた書き換え時に体験）

そこで、各バンドル済みファイルが、問題ないと判断するのに最低限ひつようなテストはどんなのが良いでしょうか？
reactでのeditor/versionもエラー無く動作することは確認しておきたいです。
karmaはe2eのテストツールではないので、なでしこで実行したlog(表示するの中身)で判定したり、htmlのDOMを参照してDOMの構造や値を読んで判断するような実装になります。

**Comment by kujirahand** [comment]
実装されました。@weyk さん感謝！
