### ISSUE TITLE
タッチ配列とは？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#656]
タッチ時の解説に、『タッチ配列』に配列で[ [x1,y1],[x2,y2]...]のように座標が設定される。と、あるので、指を動かして取得された[タッチX,タッチY]が順々に追加されていくものと思ったのですが、その場その場の[タッチX,タッチY]が返って来るだけです。正しい仕様が分かりませんが、その時の座標が[タッチX,タッチY]で返るだけなら、タッチX、タッチYとほとんど変わらずあまり意味が無いし、上記の説明とも合わないようです。
**再現方法：**
```
描画中キャンバスをタッチした時には
　タッチ配列を表示。
ここまで。
```
タッチ配列に配列追加してるけど、グローバル変数になっていないから、呼び出されるたびに初期化されてる的な？（素人考え）

そして、タッチ開始時とタッチ終了時にも全く同じ説明が書かれていてよく分からないのですが、これはどうなるものなのでしょうか。
とにかく全部の座標がずっと追加されて行っちゃうのか、タッチ開始時で初期化されてタッチ終了時までの一連が取得されるのか？　個人的には後者が良さげに思うのですが。

**Comment by weyk** [comment]
受信した、そのイベントのデータになります。変数自体はグローバル変数で、呼び出されるたびに
そのイベントの情報で上書きされていて、累積したデータはありません。
では何かというと、マルチタッチの場合で、イベントに２つ以上のタッチ情報があった場合を
含めた、複数分の情報です。
データの座標は、タッチX,タッチYと同じで、イベント対象の要素の左上を0とした、相対座標です。
※タッチX,タッチYと同様、座標は、要素内とは限らないので注意。

多くの、本物のタッチデバイスでは、マルチタッチに対応しており、２～10の指を
追跡可能です。イベントの契機となった変化のタッチ情報のうち、１つ目の座標が
代表でタッチX,タッチYに設定されていて、１つ目とその残りが、タッチ配列に
設定されます。

そこで、注意点として、イベントの種類に関連したタッチ情報がタッチ配列に格納されます。
なので、デバイスが追跡しているタッチ情報のうち、タッチ開始ならば、「新たにタッチされた
場所」が、タッチ終了ならば、「新たに離れたタッチの最終位置」のみが入いっています。
タッチされた全体を追跡したい場合は、タッチ開始でタッチ位置を追加していって、終了か
キャンセルで削除してゆくという感じになります。
※生のイベント情報には、変化しなかったタッチ情報の全体も常に格納されています。

なお、指を追跡の際に重要な情報がタッチIDなのですが、生のイベント情報にしかないので
必要な場合は、生のイベント情報から、取り出しなおさないといけないことになります。
（タッチIDは、新たにタッチされると、新しいIDが割り振られ、移動・終了・キャンセルで
　同じIDとともに座標が報告されてくることで、１つ１つの指の動きを正確に追跡可能に
　しています）

**Comment by snowdrops89** [comment]
ありがとうございます！！
理解しました。
１本の指でタッチした場合には[x1,y1]しか入らないから[タッチX,タッチY]ってだけのことのように思えるけど、複数の指などでタッチした場合に、[x2,y2]...以降の部分が設定されるということですね？
例えば、タッチ配列[0]とタッチ配列[1]にそれぞれ描画することで、二本の指で同時に線を引いたり出来る的なことですよね？
マルチタッチということを今日初めて知ったわたしですが、スマホの二本指で拡大縮小するヤツ（？）なども、そういうアレなのですね。
何か質問コーナーのようになってしまいすみませんでした。おかげさまで賢くなりました。ありがとうございました☆
