### ISSUE TITLE
無名関数を定義できるようにしたい

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#66]
JSのAPIをラップするうえで、無名関数を定義できるようにしたいのです。
現状のPEG文法に大幅な変更を加えることなく、かつ、自然な日本語に見えるようにしたいです。

**Comment by massongit** [comment]
```
以下をへんすうにセット
ここから
(処理)
ここまで
```
のような形にすると、日本語として自然になりそうですね。

**Comment by kujirahand** [comment]
例えば「配列カスタムソート」命令を例に考えてみると、どんな感じになるでしょうか。

ほぼJavaScriptで考えてみる場合：
```
A=[1,10,100]

# 変数に代入
F=関数(a,b){ それはa-b }
AをFで配列カスタムソートして表示。

# 命令の引数に使う
Aを関数(a,b){ それはa-b }で配列カスタムソートして表示。
```

**Comment by massongit** [comment]
```
A￥0=1
A￥1=10
A￥2=100

# 変数に代入
これ(aと, bを)をFに代入
ここから
a-b
ここまで

AをFで配列カスタムソートして表示。

# 命令の引数に使う
Aをこれ(aと, bを)で配列カスタムソートして表示。
ここから
a-b
ここまで
```
おそらくはこのような感じになるのではないかと (上の例では`以下`になっていたのを`これ`に変更しています)。

**Comment by kujirahand** [comment]
『これ(引数)ここから..ここまで』も良いですね。ただ、複数の無名関数を利用したい場合に、構文の下に本体を定義するというのが、ちょっと分かりづらいでしょうか。
そこで、せっかくなので、もう少し考えてみます。
以下は、JSのアロー関数みたいなのが使える感じで手軽に実装できるバージョン。

- 関数の定義が「●」なので、無名関数の定義を「λ(らむだ)」にしてみます。
- 「ここから」の別名を「→」、「ここまで」の別名を「←」と定義してみます。

```
A=[1,10,100]

# 変数に代入
F=λ(a, b)→それは(b - a)←
AをFで配列カスタムソートして表示。

# 命令の引数に使う
Aを(λ(a, b)→それはb-a←)で配列カスタムソートして表示。
```

簡潔ですが、ちょっと日本語として微妙になってしまいますね。

**Comment by massongit** [comment]
『λ』は数学に馴染みがない人には分かりづらい (「この文字ってどう入力するの？」という話になってしまう) ような気がするので、別の記号が良いような感じがしますね (一番最初の案の『関数』など)。

**Comment by kujirahand** [comment]
確かに、λは読みにくいので、「関数」で考えてみます。
そして、「ここから」の別名を「→」、「ここまで」の別名を「←」と定義してみます。

```
A=[1,10,100]

# 変数に代入
F=関数(a, b)→それは(b - a)←
AをFで配列カスタムソートして表示。

# 命令の引数に使う
Aを(関数(a, b)→それはb-a←)で配列カスタムソートして表示。
```

良さそうなので、実験的にこれで実装してみます。

**Comment by kujirahand** [comment]
eb724de18434919cf43e09c4afcb155d6d3e393e

**Comment by kujirahand** [comment]
既に、無名関数が定義できるようになっているが、Node.jsの関数群を利用するためには、もっとシンタックスシュガーが必要。たとえば、なでしこのイベント記述のように書けるようにしたら、どうかと考えました。

例えば、JavaScriptのsetTimeoutをなでしこで実装する場合を考えてみます。

```
3秒待った時は
　　「ここに三秒後の処理を記述」と表示。
ここまで
```

構文的には、『(関数名)は...』と書いたときには、代入文の内容を関数の定義と判断して、関数の第一引数に与えるという仕組みです。これ、かなり行けるかも。

**Comment by massongit** [comment]
このIssueはcloseしても良いかと思います。
