### ISSUE TITLE
ユーザ関数コンパイル時の外側の変数の参照の解決の問題

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#680]
関数宣言取り込み時の、変数の探索とローカル変数の保持に変更が必要かもしれません。
以下のコードで「Hは5」の位置で表示が変わるのは、コンパイル時の関数の外側の影響を受けているためです。
```
Hは5
●Fとは
Hは2
Hを表示
ここまで
# Hは5
F()
Hを表示
```
コンパイル時、宣言されているブロックの階層を元に、何番目の階層を
参照しようとするかを静的に決めている(__varslist[2-]のどこか)っぽいのですが、
実行時は、この変数の意味はコールスタックの呼び出し履歴に変わるため、
コンパイルの静的な解析時にローカル変数(__vars)と、グローバル変数(__varslist[2])以外を
指していたものは、想定外のところを参照することはないでしょうか。
※上記のややこしさ対策に限れば、「関数内での代入による宣言代行」の禁止でしょうか。
　ちょうど、javascriptのvarと似てますね・・・（あちらはglobal変数が作られちゃいますが）

javascriptの真似する場合、自身のローカル変数以外のグローバルではない変数への
参照は、indexベースではなく、変数群そのものを指示しておく必要があるように
思います。
（自身のローカル変数は、push/popのstackから切り離されるので残るが、
　それ以外のstackは、呼びだし履歴に応じて変わってしまう）

現象の確認・確定もまだなのですが、忘備もかけてissueにあげておきます。
まずは、問題となる現象が本当に発生するかどうかと、もし、期待する動作と
実際の動作が異なる場合、期待する動作の明確化が必要かなと思われます。

**Comment by kujirahand** [comment]
複雑で変更の影響力が大きい部分なので慎重に取り組みます。

**Comment by weyk** [comment]
別の人が再発見して直したらしいので。
