### ISSUE TITLE
なでしこの実行速度の高速化

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#683]
単純なフィボナッチのテストを実行してみると、Node.jsに比べて6.3倍遅い。せめてPython3と同等の速度で実行したい。

| 言語 | かかった時間 |
|----|------|
| JavaScript(Node.js v13.10.1) | 0.072s |
| なでしこ v3.1.7 | 0.458s |
| Perl v5.18.4 | 0.523s |
| Python v3.7.4 | 0.413s |

Perlより速いのが慰めですが、ボトルネックを洗ってNode並に速くしたいです。

検証したコード

```fib.js
function fib(n) {
  if (n < 2) return n
  return fib(n-1) + fib(n-2)
}
let a = fib(30)
console.log(a)
```

```fib.nako3
●FIB(Nの)
　　もし、N<2ならばNで戻る。
　　((N-1)のFIB)+((N-2)のFIB)で戻る。
ここまで。
A=(30のFIB)
Aを表示。
```

**Comment by kujirahand** [comment]
考慮する、日本語の変数名展開やローカル変数の最適化など

**Comment by kujirahand** [comment]
ちなみにPythonのコード：

```
def fib(n):
    if n < 2: return n
    return fib(n-1) + fib(n-2)

a = fib(30)
print(a)
```

| python3.8.2 | 357.67 millis |
| cnako3 (行番号最適化) | 428.43 millis |
| cnako3 (行番号完全なし) | 338.18 millis |

**Comment by weyk** [comment]
生成されるコードを見ての感覚的なところなのですが。

数値演算メインの場合、parseFloatの影響が大きくありませんか。
オプションで、parseFoatとtoStringがオフにできて、「型の確保を開発者の責任で実装すること」とできると、リバーシの思考回路やシューティングの弾の処理のような純粋な数値演算が早くなるのでは　と思っているのですが、検証はできていません。

もう１つ、「それ」への代入のために、無名関数が多く生成されているように感じるので、「それ」を不要とする選択肢があっても良いかなと思いました。

この辺を調べるのに、簡易エディタに、生成されるトークン列を表示する機能と、生成されるJSコード(new Functionに渡されるコード)を表示する機能があると便利なのですが、なにか、開発用ツール的な位置づけで追加できないでしょうか。
手元では、demoのeditor.jsxの改造版で、この２つのボタンを追加したものを活用しています（意味不明なエラーになったときとか）

**Comment by yy0931** [comment]
ユーザーが書いたコード部分で実行時エラーが起きることはめったにない（※）ため、なでしこのプラグイン関数でエラーが起きた場合の行数さえ表示できれば、lineへの代入は無くしても問題ないのではないかと思います。
※ JavaScript では 0 除算してもエラーにならず、なでしこからコンパイルに成功していれば関数ではないオブジェクトを関数として呼ぶこともほとんどないため。

**Comment by yy0931** [comment]
オブジェクトのプロパティと配列要素の参照（`a[i]`）はエラーが飛びうるため、直前にlineを代入するべきかもしれないです。

**Comment by kujirahand** [comment]
閉じます。@yy0931 さん感謝。
