### ISSUE TITLE
なでしこで作ったモジュールの取り込みができない問題

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#684]
Webブラウザ版で、なでしこで作ったファイルを上手にロードして実行する方法を考える。
取り込む対象が「*.nako3」であれば、ファイルをfetch してevalする感じ？

#362 も関連。

 #628 ナデシコするで関数定義ができない問題

**Comment by weyk** [comment]
たしか、なでしこ１の時は、取り込み時に実行してたんですよね。
当方では、命令の箇所に取り込みつつ、１つのトークンの配列にしてから、後続の関数解析→トークン置換→パースで考えてました。cのincludeに近いです（埋め込むのはトークンにしてからですが）

前者の場合、依存が一方通行の部品の切り出しに向いていて、後者の場合、単純なファイル分割になるんですが、どちらも、相互依存のあるアプリケーション本体のモジュール分割には向かないんですよね。

気になるのは、ファイルの拡張子とmimetypeです。cnakoでローカルファイルならば、自由なんですが、
wnakoでサーバに置いたものをfetchする場合、
・サーバが未知の拡張子や許可されたmimetype(に紐づく拡張子)以外を配信しない可能性がある（IISとか）
・クロスオリジンはどうするか。
・取り込む分には、サーバにnako3で記述したファイルが使用可能となるものの、開始ファイルには使えないので、スタートアップコードだけhtmlへの埋め込みになってしまう。

**Comment by kujirahand** [comment]
そうです。なでしこv1の取り込むは、読み込んで評価するのと同じ感じでした。

#686 で実装済み
#687 で改善案を協議中

引き続き、このスレッドでは、wnako3で読み込み時のサーバー側の問題解決にフォーカスできればと思います。

MIMEはサーバー側の配慮が必要ですものね。
読み込み時に任意のMIMEを出力するよう補助Webアプリを介するようにするなど、工夫出来ると良いですが。
クロスオリジン問題、引き続き考えていきましょう。
この流れで行くと、なでしこのライブラリを吐き出すAPIサーバーのような存在が必要かもですね。

**Comment by kujirahand** [comment]
実装済み。
