### ISSUE TITLE
Web Workers APIの実装

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#691]
Web Workers APIなんとか実装する

実装方法
（1）なでしこのソースコードを受け取ってコンパイルして実行するワーカーを用意する。
（2）メインスレッドからワーカーに対してなでしこのソースコードを投げる
（3）ワーカー内でコンパイルして実行する

こんな感じでいけるかな？

- https://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by weyk** [comment]
文章にするのが自身ないので、とりあえずPRに入れておきました。

「ナデシコする」の命令をどうするかや、requireしているパッケージをbundleする必要があるプラグインの命令を考えると、
ワーカー側にも一式持つしかないのかな　と。

あとは、現在のplugin_browserのうち、ワーカーで動くものと、動かないものと、似ているけど少し違うものを、ワーカー側で取り込むpluginにする必要がありますね。browserプラグイン自体を機能別の小分けにして、requireで統合する形にするのがよさそうかなぁ　と思ってます。

**Comment by kujirahand** [comment]
https://github.com/kujirahand/nadesiko3/pull/692

上記、ありがとうございます！
ワーカーが使えるといろいろ便利になりますね。

この後は、『NAKOワーカーデータ返信受信時』など、動詞を重ねたものになっておいて、命令名に少し不自然な感じがありますので、ブラッシュアップさせて使いやすくシンプルにできたらと思います！

**Comment by weyk** [comment]
同じ、メッセージやデータの送受信が、起動された側はグローバルオブジェクトのメソッドになるのに対し、起動した側は起動したワーカーオブジェクトのインスタンスメソッドになるため、悩ましい感じになっています。
（親）[ワーカー]のデータ返信受信した時
（親）[ワーカー]に[データ]をデータ送信
（子）データ受信した時
（子）[データ]をデータ返信
以前の母艦のように、SELFに何か定数(例えば、親スレッド)に入れてしまい、
（親）[ワーカー]のデータ受信した時
（親）[ワーカー]に[データ]をデータ送信
（子）[親スレッド]のデータ受信した時
（子）[親スレッド]に[データ]をデータ送信
と、同じ命令で扱ってしまう手もあるのですが、定数の名前が悩ましいです（親もワーカーかで自分は孫かもしれない）
ワーカーから、ワーカーが起動できるので、ワーカー内では呼び出す側・呼び出される側の両方の命令を使えるようにしないといけないのが悩ましいです。

**Comment by kujirahand** [comment]
改善案ですが、
まず、「wwnako3」が何のことか分かりづらいので「wnako3webworker」と分かりやすくするのはどうでしょうか？
また、ワーカーを生み出す親と、作られた子ということで、親子関係があることに注目した命名をすると良いかなと思います。

それで、親子だとありきたりなので、WebWorkerを無理矢理日本語に直して、
「依頼主と仕事人」という感じにするのはどうでしょうか。

- 「ワーカー起動」→「裏作業依頼」
- 「NAKOワーカーデータ返信受信」→「依頼主裏データ受信」
- 「NAKOワーカーデータ返信」→「裏データ返信」
- 「NAKOワーカーデータ送信」→「仕事人裏データ送信」

さすがにちょっと無理がありますね。
系統は別ですが、同じ命令で扱ってしまうのも手かと思います。

**Comment by weyk** [comment]
wwnako3.jsは、本来はなでしこのソースにファイル名が出てこない想定で、wnako3.jsと同じURLに存在する前提でファイルを参照したいのですが、cnakoやwnakoとは少し違うかもしれません（nako3serverが近い？）
scriptから自身のURLを取得できるか調査中です（ベースURLはhtmlの場所になってしまうので）

あとは、今後出そろってきそうな共有ワーカもあり、そっちもまた少し違う感じです（親子関係ではなくなるから？）
また、ワーカーの子側が、さらにワーカーを起動するとは限らない（どちらかというと少なそう）なので、既定のプラグインは、ブラウザの互換版＋子側の機能だけでもよさそうかなぁと思っています。
そのかわり、ワーカー起動時に任意のpluginが組込めるようにしたいのですが、日本語の命令名として、どう指定させるかは不明です（グローバル変数に配列で入れる形にする？）
実際の取り込みは、importsScript()を並べたらできるかな　と試す予定です。

**Comment by kujirahand** [comment]
(memo) #700 にて上記改善済み

**Comment by kujirahand** [comment]
実装済み。
