### ISSUE TITLE
条件分岐構文を実装した件

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#694]
v1にあった条件分岐構文を実装するかどうか話し合いましょう。

```
R＝（６の乱数）＋１。
Rを表示。
Rで条件分岐
　　１ならば
　　　　「🐟」と表示。
　　ここまで
　　２ならば
　　　　「🐕」と表示。
　　ここまで
　　３ならば
　　　　「😸」と表示。
　　ここまで
　　４ならば
　　　　「🐵」と表示。
　　ここまで
　　違えば
　　　　「🐭」と表示。
　　ここまで
ここまで。
```

個人的にはなくても良いかと思っていたのですが、あっても良いかもとは思います。

**Comment by weyk** [comment]
リバーシ作っているときは、ないのに気が付かずに普通に使って普通にエラーになりました。
それはおいといて。

プログラム言語としては、より、同じ動きでも、意図に適した構文があるのは、読み解く際に有用です。
特に、分岐内が短く、全体が１画面に収まる程度であれば、見通しが良くなると思います。
また、多くの言語から読み替える際にも、swtch/caseやselect/caseに対応する命令として有用です。
なのですが、日本語プログラム言語としてみたとき、「ここまで」構文には合わないような気もします（行が進みすぎる）。
条件分気分には対応するここまでを持つとして、個々のcaseにはここまで不要とかはダメですかね。次の「ならば」もしくは、「違えば」もしくは、条件分岐を閉じる「ここまで」のいずれかがブロックの最後になるはずなので、構文解析自体は困らないはずなんですが。「もし」構文のthen節でも、「ここまで、違えば」とはしていませんし。

**Comment by kujirahand** [comment]
そうですね。せっかくないことに気付いたので対応しましょう。

上記の「ここまで」を多用した条件分岐は、「##インデント構文」に対応させるとこうなるというのを示したもので、省略できる仕組みにするのもありですね。ここまでがあってもエラーにはならない仕組みにすると「インデント構文」とぶつかりません。

```
R＝（６の乱数）＋１。
Rを表示。
Rで条件分岐
　　１ならば
　　　　「🐟」と表示。
　　２ならば
　　　　「🐕」と表示。
　　３ならば
　　　　「😸」と表示。
　　４ならば
　　　　「🐵」と表示。
　　違えば
　　　　「🐭」と表示。
ここまで。
```

**Comment by kujirahand** [comment]
うーむ、やはり「##インデント構文」があるので難しい。

```
2で条件分岐
　　１ならば
　　　　「🐟」と表示。
　　ここまで
　　２ならば
　　　　「🐕」と表示。
　　ここまで
　　違えば
　　　　「🐭」と表示。
　　ここまで
ここまで。
```

各条件の末尾の「ここまで」を省略できる仕様にすると、「違えば」末尾の「ここまで」なのか、「条件分岐」末尾の「ここまで」なのかを判定できない。。。むむむ。
やはり、、、暫定的に「＊＊ならば・・・ここまで」は必須とすることにします。

**Comment by kujirahand** [comment]
やはり「ここまで」を「♪（おんぷ）」などで置き換えできるとおしゃれかもしれませんね。

```
2で条件分岐
　　１ならば、「🐟」と表示♪
　　２ならば、「🐕」と表示♪
　　違えば、「🐭」と表示♪
ここまで。
```

「♪」ではなく「💧」も良いのですが、IMEですぐ出てこないとあまり意味ないですしね。

```
2で条件分岐
　　１ならば、「🐟」と表示💧
　　２ならば、「🐕」と表示💧
　　違えば、「🐭」と表示💧
ここまで。
```

¶（だんらく）でも良いかもですが。

**Comment by kujirahand** [comment]
この件、#706 に移して話し合いましょう。とりあえず、実装済みなので、こちらは閉じます。
