### ISSUE TITLE
turtleプラグインの配布サイズ対策（カメ画像）

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#698]
現在、カメ画像としてturtle64.png他がinlineで格納されてますが、pngの画像の圧縮は、
多数の方法があり、多くは最小サイズとはなっていません。
（実際に、それぞれ圧縮して比較してみないわからない。予測は不可能。モノクロ除く。）
サイズ優先でいろいろなサイト・ツールで圧縮を試行して変換してくれるものが
あるので、いかがでしょうか。

おそらく、今は32bitのrgbaのパレット無しと思いますが、使用している色数が少ないので、
変換すると8bit indexed（パレットカラー）になるのではと思います。そうなった場合、
大きくサイズ削減が可能です。格納形式の方法自体の調整での小サイズ化なので、
劣化等はありません（ちゃんとしたツールなら）
※亀だけ64なのを32に合わせる手もありますが、indexedへ変換されてしまうなら、
　もったいないかも。

蛇足。
影響はturtleだけなので、あえて、このまま置いといて、なでしこ１や３で圧縮を試行して
比較するツールを書くのも有りかもしれません（pngはそんなに難しくないです。）
その場合、deflateとcrc32演算はあった方がいいかもしれません。

**Comment by kujirahand** [comment]
良いですね！
とは言え、そもそもカメ画像の絶対URLをnadesi.com内に作っておいて、アーカイブに梱包しないというのもありかと思っています。

**Comment by kujirahand** [comment]
nadesiko3docにattachディレクトリを作り、その中に画像を入れました。

- https://nadesi.com/v3/doc/attach/turtle64.png
- https://nadesi.com/v3/doc/attach/elephant64.png
- https://nadesi.com/v3/doc/attach/panda64.png
- https://nadesi.com/v3/doc/attach/nako64.png

**Comment by kujirahand** [comment]
とは言え、よく使うカメはとにかく軽量化して埋め込み、パンダと象は上記URLを使うとかでも良さそうですね。

**Comment by kujirahand** [comment]
軽量化したら50KB→3KBに！
もっと早くやっておけば良かったですね。
