### ISSUE TITLE
タートルグラフィックスで、ゾウ作成するのにカメ進むって不自然

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#703]
タートルグラフィックスですが・・・
やっぱり「ゾウ作成」するのに結局「カメ進む」って不自然な感じですよね。

- 右回転
- 歩進む

などなど、カメの接頭辞なしでも被る命令ないのでは。。。
検討する。

**Comment by massongit** [comment]
以下のように `タートルグラフィック` で抽象化してしまうのもありかもしれません。

```
「ゾウ」でタートルグラフィック作成
1だけタートルグラフィック進む
```

**Comment by kujirahand** [comment]
タートルグラフィック で抽象化の案も良いですね。
とは言え、`タートルグラフィック作成`となると、ちょっと命名規則として長い感じもします。
そこで、タートルグラフィックスを`動物ボット`とするのはどうでしょうか？

```
「ゾウ」の動物ボット作成。
4回
　　90度動物ボット右回転
　　100歩動物ボット進む
ここまで。
```

ただ「(N)度右回転」や「(N)歩進む」は他の命令と被らないので、両方対応するのもありかも。

```
「ゾウ」の動物ボット作成。
4回
　　90度右回転
　　100歩進む
ここまで。
```

**Comment by kujirahand** [comment]
さすがに`動物ボット`は不自然なので、やはり`タートル`くらいが良いかも。

```
「ゾウ」のタートル作成。
4回
　　90だけ右回転
　　100だけ進む
ここまで
```

**Comment by kujirahand** [comment]
現状、問題なく使えているので、とりあえず、もっと画期的なアイデアを思いついたら実装する。
よく考える。
