### ISSUE TITLE
オーディオ停止の不具合？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#715]
**再現方法：**
　再生している途中で停止ボタンを押せば、オーディオ再生位置は０になりますが、その後もう一度再生を押すと、なぜか停止をした時の位置に戻っており、そこから再生されます。
　停止ボタンを二回押せば、０からになるようです。
```
音＝「https://snowdrops89.github.io/audio/Congratulation_53.mp3」をオーディオ開く。

「再生」のボタン作成して、再生ボタンに代入。
「停止」のボタン作成して、停止ボタンに代入。
「一時停止」のボタン作成して、一時停止ボタンに代入。

再生ボタンをクリックした時には、
　オーディオ再生位置を言う。
　音をオーディオ再生。
ここまで。

停止ボタンをクリックした時には、
　音をオーディオ停止。
　オーディオ再生位置を言う。
ここまで。

一時停止ボタンをクリックした時には、
　音をオーディオ一時停止。
　オーディオ再生位置を言う。
ここまで。
```

**Comment by weyk** [comment]
未検証なんですが、停止時に内部で登録しているイベント（随時、現在位置の更新をオーディオ再生位置に設定する）が呼び出されるタイミングの問題っぽいですね。動きは推測できるんですが、じゃぁどうしようはどうしましょうか。

ボタンのイベント開示
停止命令でpauseする
→pauseにより現在位置を確定されるため、更新イベントが発火されるがシングルスレッドなので実行は待機。
現在再生位置を０にする
ここでボタンのイベントを抜けて、スレッドが空く
待機してた更新イベントが実行されて、pause時点の現在位置を現在再生位置に設定する
更新イベント終わる
（この時点では、実際のaudioは再生位置はもとのまま）
再生する際は、常に、現在再生位置に頭出ししてからになるので、結果として続きからになる。

ここで再生せずに、もう１度停止のボタンを押した場合、
pauseしても、（現在位置は動いてない）更新イベントが発火しないので、
現在再生位置を０にする処理の後に上書きされることがない。
（この時点では、実際のaudioは再生位置はもとのまま）
次に再生するときは位置０に頭出ししてからの再生になるので、最初から再生される　と。

停止時には、puaseと合わせて、audio自体の再生位置を０に設定することまでしてしまえば、おそらく、その更新イベントも発火して、先頭が記録される気がするのですが、連続再生することの方が少ないかもしれなと考えると、無駄な動作になりますね（再生しているものが、頭出しが軽負荷とも限らないので、不要な呼び出しは無い方が良いのかな）

**Comment by kujirahand** [comment]
修正しましたので、閉じます。
