### ISSUE TITLE
JavaScriptのコーディング規約について

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#72]
JSのコーディングについて、意見が分かれそうなので、最初から、JavaScriptのコーディング規約を決めてしまうのはどうでしょうか。調べてみると、最近、流行のコーディング規約には、JS Standard Styleというのがあるようです。

- JavaScript Standard Style - https://github.com/feross/standard
- (参考) - http://akabeko.me/blog/tag/javascript-standard-style/
- (参考) - http://var.blog.jp/archives/65336708.html

**Comment by massongit** [comment]
JS Standard Styleを適用するのは個人的にはありだと思います。

**Comment by kujirahand** [comment]
それでは、少しずつ対応させていきましょう！

**Comment by massongit** [comment]
.eslintrc.jsonの以下の記述に関してですが、値はtrueとfalseどちらでしょうか？ ([ESLint 最初の一歩 - Qiita](http://qiita.com/mysticatea/items/f523dab04a25f617c87d#%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A7%E5%AE%9A%E7%BE%A9%E3%81%99%E3%82%8B)によれば、追加定義するグローバル変数が書き換え可能かどうかを値で表すようです)

```
"globals": {'describe', 'it', 'before'}
```
