### ISSUE TITLE
クジラ飛行机さんへ

### ISSUE THREAD

**Issue by takuyatahata** [kujirahand/nadesiko3#740]
@kujirahand  さんへ
あなたの参考書に書いてある、芥川龍之介の作風の変化についてeメールを送ったのですが技術的な質問以外は受け付けていないのでしょうか？

**Comment by kujirahand** [comment]
おやっ？！メールを見落としていると思います。再度、メールをいただければと思います。

**Comment by takuyatahata** [comment]
@kujirahand 　さんへ
宛先はweb@kujirahand.comで間違いないですか？最初に＠マークを全角で打ち込んで届かなかったので半角にしました。
迷惑メールのフォルダに入っているということではないですよね？
もう一度質問内容を考え直してから送ります。

**Comment by kujirahand** [comment]
web@kujirahand.com です。お手数おかけします。メールお待ちしています。

**Comment by takuyatahata** [comment]
@kujirahand  さんへ
フリーメール送れないみたいですよ。一度目はGmailで、二度目はヤフーメールで送りました。二度目のメール送ってから二週間以上経っています。ホストのメールサーバーがはじいてしまうのでしょうか？

質問内容は　小説の作風の変化をAIが解釈できないのかどうかです。参考書では青空文庫の作品を単純に比較しているだけなので融通が利かないですよね。

**Comment by kujirahand** [comment]
@akuyatahata 返信しました。あまりお役に立てないかもですが、今後ともどうぞよろしくお願いします。

**Comment by takuyatahata** [comment]
@kujirahand 
お忙しい中、返信していただいてありがとうございました。ネット喫茶のパソコンの処理速度が遅いので、私も個人で勉強するのは限界があります。
参考書はお金に余裕がないのと、部屋に本を置くスペースがないので本屋で拾い読みしています。
本の誤植なんか見つけましたらまた、連絡報告相談します。今日はこれで失礼します。
