### ISSUE TITLE
文字列内の計算式展開の是非(念のため)

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#752]
下記で文字列内にある計算式を展開して実行するようなコミットをいただきました。
機能的には素晴らしいのですが、セキュリティ的にはどうでしょうか。
念のため一度検討したいと思います。

- https://github.com/kujirahand/nadesiko3/pull/750

**Comment by yy0931** [comment]
問題になる場面が思いつかないのですが、なでしこ言語の自動生成とかを考えていますか？

**Comment by weyk** [comment]
一応意見を。
なでしこソース上に定数文字列として記述したものにしか適用されず、変数経由では適用されないという認識でよいのですよね？

元々の実装でコードを実行するようになっているため、今回の変更でセキュリティ的にリスクが増えることはなさそうだと思っています。

もし、問題になるとしたら、「なでしこする」などのeval系の命令と組み合わせた場合と思いますので、なにか対策するとしたら、「ナデシコする」系の命令かな　と思っています。

**Comment by kujirahand** [comment]
@weyk さん、ご意見ありがとうございます。
利便性も格段に向上しましたし、大きな問題もないと思いますので、解決とします。
@yy0931 さん、実装ありがとうございました！！
