### ISSUE TITLE
エラーメッセージでノードを再帰的に表示する

### ISSUE THREAD

**Issue by yy0931** [kujirahand/nadesiko3#756]
たとえばプログラム
```
「こんにち」はと表示
```
は構文エラー
```
『演算子[eq]』がありますが文が解決していません。
```
を表示しますが、これでは意味が分かりづらいため、ある程度の深さまで再帰を許して
```
『文字列『こんにち』と単語『表示』に演算子『eq』を適用した式』がありますが文が解決していません。
```
くらいまで表示できると分かりやすいと考えています。

@kujirahand 文面など、何か意見はありますか？

**Comment by kujirahand** [comment]
エラーメッセージはとにかく『親切』になると良いと思いますので実現できると良いですね。
文面としては、根本的なエラー理由を最初に示し、詳細な理由がその後に続くと読みやすいでしょうか。

```
不完全な文です。演算子『eq』が解決していません。文字列『こんにち』と関数『表示』があります。
```

**Comment by yy0931** [comment]
『eq』の部分に複数のノードが表示される場合があり、その場合続く文がどちらのノードの話をしているか分からなかったため、明記するように実装してしまいました。
