### ISSUE TITLE
より正確なソースコード位置と長さの取得

### ISSUE THREAD

**Issue by yy0931** [kujirahand/nadesiko3#765]
[knaさんによって書かれたVSCode拡張](https://github.com/kna/nadesiko3-vscode-extension) ではトークンの色付けを[正規表現](https://github.com/kna/nadesiko3-vscode-extension/blob/nadesiko3/syntaxes/nadesiko3.tmLanguage.json)で行っているため、十分なシンタックスハイライトを提供できていません。

そのため、トークンの可視化まで可能なVSCode拡張機能を作りました ([GitHub](https://github.com/yy0931/nadesiko3-vscode), [Marketplace](https://marketplace.visualstudio.com/items?itemName=yy0931.nadesiko3-vscode))。（もし既にインストールしていたら、更新をお願いします。）

それを作るにあたって、各トークンの先頭位置と長さの正確な情報が必要だったため、コンパイラに変更を加えています。
- [nako_indent に挿入された行と削除された行のリストを出力させる](https://github.com/yy0931/nadesiko3-vscode/blob/main/src/nadesiko3/nako_indent.ts#L8)
- [nako_prepare で行われる置換の逆操作を行うクラスを追加](https://github.com/yy0931/nadesiko3-vscode/blob/main/src/nadesiko3/nako_prepare.ts#L8)
- [convertTokens で消されるコメントを保存しておく](https://github.com/yy0931/nadesiko3-vscode/blob/main/src/nadesiko3/nako3.ts#L200)
- [トークンに、ソースコード上の位置、長さ、置換前の助詞、関数の定義元かどうかのフラグ を持たせる](https://github.com/yy0931/nadesiko3-vscode/blob/main/src/nadesiko3/nako3.ts#L28)
- エラーにプリプロセッサ上とソースコード上の位置を持たせる ([lexerのエラー](https://github.com/yy0931/nadesiko3-vscode/blob/main/src/nadesiko3/nako3.ts#L16), [parserのエラー](https://github.com/yy0931/nadesiko3-vscode/blob/main/src/nadesiko3/nako3.ts#L51))

@kujirahand 
なでしこ言語に変更があるたびに拡張機能へポートすることは難しいため、このレポジトリに変更を適用してもよいですか？　

これらの実装を使えば、エラーメッセージでソースコード位置を矢印で示すことも可能になるはずです。

**Comment by kujirahand** [comment]
なんと、素晴らしいです。

> なでしこ言語に変更があるたびに拡張機能へポートすることは難しいため、このレポジトリに変更を適用してもよいですか？　
ぜひ、お願いします。
