### ISSUE TITLE
なでしこ簡易エディタで「クリア」ボタンおしても「秒毎」のタイマーが止まらない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#769]
なでしこ簡易エディタで「クリア」ボタンおしても「秒毎」のタイマーが止まらない

**Comment by kujirahand** [comment]
nako3storageについても同じ
直す

**Comment by weyk** [comment]
これはpluginに共通I/F持たせて、nako3から一括して呼び出せるようにする必要があるんですよね。

**Comment by kujirahand** [comment]
なるほど。
今のところプラグインごとに、初期化処理のみがあるので、
片付け処理を行うメソッドを追加して、そこで処理するのがエレガントかもしれませんね。

**Comment by kujirahand** [comment]
現在プラグインのインターフェイスに、「初期化」があるが「クリア」を追加します。

**Comment by kujirahand** [comment]
修正完了。
