### ISSUE TITLE
助詞「しなければ」の追加

### ISSUE THREAD

**Issue by yy0931** [kujirahand/nadesiko3#774]
if文で「ハッシュキー存在」やファイルの存在確認の「存在」の否定を使うとき、
```
もしpathが存在でなければ
```
ではなく
```
もしpathが存在しなければ
```
と書けるようにしたいです。

**Comment by kujirahand** [comment]
これはいいですね！

```
もし、Fが存在しなければ・・・
もし、Nが30以上でなければ・・・
```

「しなければ」「でなければ」の二つに対応すると良いでしょうか。
他の場面ありますか？

**Comment by yy0931** [comment]
他にはboolを返す関数は見当たらないです

**Comment by yy0931** [comment]
もう一度見返したら、数値比較の「等しくなければ」もありますね

**Comment by yy0931** [comment]
「しなければ」を「なければ」に変更することでどちらにも対応できそうです。「でなければ」は助詞「で」にマッチさせないために残す必要があります。
```javascript
等
しく    // 送り仮名（助詞「し」、「しく」は存在しない）
なければ  // 助詞
```
