### ISSUE TITLE
簡易エディタv2のページについて

### ISSUE THREAD

**Issue by yy0931** [kujirahand/nadesiko3#781]
https://nadesi.com/v3/doc/index.php?%E7%B0%A1%E6%98%93%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BFv2
なでしこのバージョンが3.1.16のままエディタが更新されたため、エラーを吐いているようです。

**Comment by yy0931** [comment]
@kujirahand

**Comment by kujirahand** [comment]
おっと、Gitがコンフリクトしてアップデートミスしてみましたね。
アップデートしました。
