### ISSUE TITLE
変数のスコープについて

### ISSUE THREAD

**Issue by yy0931** [kujirahand/nadesiko3#787]
変数を参照するとき、現在の実装だと__varslistの要素を末尾から先頭まで順番に探索していきますが、コンパイル時と実行時でpush/popの条件が違うため正しく動作しません。

たとえば、次の場合、F2のAはF1のAを参照して、1つ前の関数呼び出しの変数を参照するようにコンパイルされますが、呼び出し元がF1ではないため、想定しない動作になります。この例だけでなく、再帰呼び出ししたときも同じ問題が生じます。

```
!インデント構文

●F1とは
    A=1
    ●F2とは
        F1
        Aを表示  # 2が表示される

●F3とは
    A=2
    F2

F3

```

そのため、変数の探索先を `__varslist[0], [1], [2], [__varslist.length - 1]` に限定すべきだと思います。あるいは、スコープのルール自体を考え直すべきかもしれません。
 
追記: 例があまり良くなかったため、`F1` の行を追加しました

**Comment by yy0931** [comment]
もっと良い例がありました。

```
!インデント構文

●F1とは
    A=1
    ●F2とは
        Aを表示  # undefinedが表示される
    F2

# 別の関数を挟んでからF1を呼ぶことで、__varslistの参照すべき添字をずらす
●F3とは
    F1

F3
```

**Comment by kujirahand** [comment]
スコープですが、確かに、こだわらなくても良い部分なので、修正後の速度重視で行きましょう。
修正ありがとうございます！
