### ISSUE TITLE
speed mode の部分的な有効化

### ISSUE THREAD

**Issue by yy0931** [kujirahand/nadesiko3#789]
https://github.com/kujirahand/nadesiko3/issues/683 でspeed mode を追加していますが、speed mode をコード全体に対して有効化するのは悪影響が大きすぎるため、unchecked ブロックや unsafe ブロックのように、速度向上が必要な一部の処理のみでspeed modeを有効化する構文を追加すると良いと考えています。たとえば https://github.com/kujirahand/nadesiko3/issues/683 のFIBの場合、次のような構文です。

```
行数の記録を無効化
    ●FIB(Nの)
    　　もし、N<2ならばNで戻る。
    　　((N-1)のFIB)+((N-2)のFIB)で戻る。
    ここまで。
ここまで

A=(30のFIB)
Aを表示。
```

このままだと意図が伝わりづらいため、文法をもう少し考える必要がありそうです。

**Comment by kujirahand** [comment]
なるほど。確かにこれは良いアイデアですね。構文にしてしまうのも良いですね。

とは言え、高速化したいオプションごとに構文を作るのも、ちょっと面倒な感じがするので、実行速度優先で引数に細かいオプションを指定できる感じが良いかもですね。

```
※ --- とにかく速くしたい ---
「全て」で実行速度優先
　　# 高速に動かしたい処理
ここまで。

※ --- 細かくオプションを指定して高速化 ---
「行番号記録なし/それ無効化/変数インライン化」で実行速度優先
　　# 高速に動かしたい処理
ここまで。
```

**Comment by yy0931** [comment]
それは良いですね。実装してみます。

**Comment by kujirahand** [comment]
文法マニュアルに追記しました
https://nadesi.com/doc3/go.php?16416
