### ISSUE TITLE
プラグイン関数と同名の関数を定義したときの挙動

### ISSUE THREAD

**Issue by yy0931** [kujirahand/nadesiko3#801]
1を実行してから2を実行すると、プラグイン関数が消されているためコンパイルエラーになる。エディタで1度でもプラグイン関数と同じ名前の関数を書くと、シンタックスハイライトのためのパースでプラグイン関数が消されてしまう。

1. 
```
●（Aの）足すとは
ここまで
```

2. 
```
1と2を足す
```

**Comment by kujirahand** [comment]
こちら検討をありがとうございます。
確かに関数の上書きは、弊害が大きそうです。
敢えて標準の関数を上書きするという場面は多くあります。

しかし、そのために、なかなか問題に気付かないという問題も起きそうですね。。

##【解決案1】

関数の上書きを禁止する『オプション』を導入するのも手ですね。

```
! 関数上書き禁止
●aaaとは
ここまで
●bbbとは
ここまで
! 関数上書き許可
```

##【解決案2】

基本は上書きは禁止だが、「再定義」を指定することで上書き可能にする案。

```
●再定義(Sを)表示とは
ここまで
```

##【解決案3】

プラグイン関数定義時に、上書き禁止フラグを導入する。上書きされたくない関数のみエラーにする。


いずれも、要検討ですね。
シンプルで覚える必要がない方法を模索しましょう。

**Comment by yy0931** [comment]
変数を追加して直せました。

**Comment by yy0931** [comment]
とはいえ、プラグイン関数を意図せず上書きするとデバッグが難しいため、警告があってもいいかもしれないですね

**Comment by kujirahand** [comment]
修正ありがとうございました！！

そう言えば、なでしこでは警告を出力しませんね。
普段は表示されないのがデフォルトにして、レベルを指定して警告を指定できるようにしましょう。
とは言え、これは別途Issueを立てます。
