### ISSUE TITLE
「表示」をすると「それ」の内容が消えてしまうのは仕様ですか？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#819]
**再現方法：**
```
それは１。
それに２を足して表示。
それに２を足して表示。
```
v1では２行目に５が表示されるところですが、v3では「NaN」となります。
単に「それを表示」してみると、「undefined」にクリアされてしまっているみたいなんです。
結構長い間、ｖ３はこうゆう物、と思って使ってきたので今さらなのですが、近頃急に、本当にそうゆうモノなんだろうかという疑問が湧き上がってきたので；
もし、やむを得ない仕儀でこうなってるわけじゃ無いのであれば、同じように動いた方が良いのでは無いかと思ったりもして。

**Comment by yy0931** [comment]
ブラウザで `navigator.nako3.setFunc('表示', [['と', 'を']], ...)` で「表示」関数を上書きしたときに `return_none: true` が消えて、値を返す関数の場合のコードが生成されているようですね。

setFunc関数にreturn_noneかどうかの引数を追加すれば良さそうです。あるいは、現在のmasterの各デモではsetFuncで「表示」を上書きせずにloggerを通して結果を取得していて、同様の変更をWebサイトのエディタにも適用しても解決します。

**Comment by kujirahand** [comment]
navigator.nako3.setFunc の仕様を変更して、末尾にreturn_noneのパラメータを追記することにしましょう。デフォルトは、return_none: trueになるようにしつつ。
