### ISSUE TITLE
連文について

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#821]
もう一つ、ｖ１と同じつもりで何気なく書くと、エラーになってしまう件です。

**再現方法：**
```
１に２を足して４を掛けて表示。
１に２を足し、４を掛け、表示。
```
v1であれば、どちらも問題なく１２が表示されますが、v3では、後者ではエラーになってしまいます。
```
[実行時エラー](3行目): エラー『TypeError: (intermediate value).call(...) is not a function』が発生しました。 [バージョン] 3.1.18
```
わたしはこれも、ｖ３はこうゆう物として、すっかり慣れてしまったのでいいんですがｗ
ｖ１ユーザーでは、タブン後者のように記述してる人が多いと思うので、可能なら互換性を保った方が良いと思うし、もし難しいことならば、マニュアルの「連文について」のトコにでも、ｖ１ではこうも書けたけどｖ３ではこっちだけですぅ～、という旨、記載した方が良いような。

**Comment by yy0931** [comment]
それに関しては、ちょうど5日前に https://github.com/kujirahand/nadesiko3/pull/810 で直したところなので、おそらく次のバージョンでは使えるはずです！

**Comment by snowdrops89** [comment]
おぉ、既出でしかも修正済みだったのですね。
ぜんぜん気付いてなかったというか内容理解してなかっ……orz
ありがとうございます！
