### ISSUE TITLE
もし文で引数を持つ関数が実行できない？

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#830]
以下を「a.nako3」で保存。してcnako3で実行すると常にfalseとなる

```
F=「a.nako3」
もし、Fが存在するならば
　　「存在」と表示
違えば
　　「存在しない」と表示。
ここまで。
```

なお、カッコで括ると正しく存在と表示される。

```
もし、(Fが存在する)ならば
```

**Comment by yy0931** [comment]
`もし F ＝ 存在する ならば` にパースされています。

**Comment by yy0931** [comment]
関数を比較することは余り考えられないため、右辺が関数のとき比較に置換させなければよさそうです。
