### ISSUE TITLE
「間」文の自動区切りルールを見直す - システム時間がエラーになる

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#831]
以下のプログラムが動きません。

```
v=システム時間
vを表示
```

以下のエラーがでます。

```
a.nako(2行目): [文法エラー]『間』で条件がありません。
[バージョン] 3.1.18
```

**Comment by kujirahand** [comment]
todo: nako_lexer.js の169行目の判定を見直す

**Comment by kujirahand** [comment]
考え直してみて「等しい間」が例外的と思います。
大抵は「Aが５以上の間」となるので。
そこで、ここで無理矢理、語句を分割せず「等 |  間」という構文を作ることで対処するのが良さそうですね。

**Comment by yy0931** [comment]
直前がひらがなのときに限定すれば「一致する間」などにも適用できそうです。

**Comment by kujirahand** [comment]
ついでに、配列も比較可能な「一致」命令を追加しますね。
