### ISSUE TITLE
ゲームをっぽいものを作成したなかでの要望

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#836]
幾つかゲームをっぽいものを作成したなかで、必要となりそうな機能の要望です。
（実装時、JS実行を使った機能）

ほぼ必須
・window.requestAnimationFrame/cancelAnimationFrame
　実体はsetTimeout()に似ている。が、vsyncに合わせて呼び出してくれるという特徴がある。
　表示にかかわるデータが変化したらこのAPIを呼び出して、コールバック関数内でデータをもとに画面を書き換えるのが基本的な使い方。
　連続で呼び出すのか、単発でいいのかは、ゲームに依る。基本的には、このcallbackの中でのみ画面を更新することで、vsyncに同期した画面更新が可能になる（表示されないタイミングでの過剰な更新が不要になる）。
　ブラウザ固有APIではあるんですが、どの命令グループが適切なのかはよくわからない。

canvas使うならほぼ必要
・context.save()、context.restore()
　コンテキストの状態の保存と復帰。matrix等の戻すのが難しい変更を使うなら必須。

canvas使用時にあった方がよさそう。
・各stroke命令と、各fill命令の、個別の命令。
・pathのbegin,endと、fill
　今は塗りつぶし無しの自由が無い。
・translate,rotate,scale,matrixの描画matrixの取得・変更の命令
　絵文字に利用した。🚀を右に４５度傾けたり。画像描画でも活用できる。
１案として、１つの文字列か配列を渡して複数命令分を連続で処理する命令はあると便利そう。同一コンテキストに対して、連続してこれらの命令を発行して使うケースが多い。特に、saveから始まって、色やサイズの設定となんかの描画後、restoreで戻すというセット。

命令不足の対策のために、context(sys.__ctx)を返す命令があると、そのために内部実装に依存した参照(sys変数にランタイム環境を保持するnako3の実体があるはず)が避けられてよさそう。

**Comment by yy0931** [comment]
[p5.js](https://github.com/processing/p5.js/) をラップするのが良いと考えているのですがどうでしょうか。canvasのAPIで関数を一つ一つ実装するのには相当の作業量が必要になる上、関数群を考えるのも大変です。図形の描画だけでなく、マウスイベントや画像処理、色の生成などの多くの関数を簡単に追加できるはずです。requestAnimationFrameはdraw()、save, restore は push()とpop()、透明色はnofill()、といったように対応します。

問題は、LGPLなためscriptタグを別で読み込ませる必要があること、既存のcanvasの命令と関数名が衝突すること、ライブラリを挟むため拡張性が下がることです。

**Comment by weyk** [comment]
通常でも、汎用ライブラリとゲーム用ライブラリが分かれていたりするので、命令グループとしてはそれぞれがあっても良さそうです。

pluginのとりこみは、同名の命令を上書きして取り込むと思うので、
・既存のcanvasの命令はそのまま。必要なものだけ追加で細かい命令までは入れない。簡易利用用。ほかライブラリ不要。
・外部フィルpluginを別途用意。命令は必要なものは上書き（動作が変わるものもある）し、使えなくなる命令もわざと上書きして、使えない旨でエラーにする。追加でp5.jsの参照も必要。
という感じでしょうか。
おそらく、ばりばりのシューティングを組めるような命令群があったとしても通常の利用では過剰になりそうですし。

どちらかというと、nako3storageのpluginやjsライブラリが固定なのがネックになりそうです。
自サイトに置く分には、自分専用にpluginつくっておくという手もありますし。
（p5.jsを組み込むとしたら、常になのか　とか、上記の標準＋拡張構成にしたら、選択はどうすればいいい　とか。アドバンスド設定とかで、任意のpluginの組み合わせを選べるといいんですが。）

**Comment by kujirahand** [comment]
あと以下の命令が未実装なので実装する。

>・translate,rotate,scale,matrixの描画matrixの取得・変更の命令
>　絵文字に利用した。🚀を右に４５度傾けたり。画像描画でも活用できる。
>１案として、１つの文字列か配列を渡して複数命令分を連続で処理する命令はあると便利そう。同一コンテキストに対して、連続してこれらの命令を発行して使うケースが多い。特に、saveから始まって、色やサイズの設定となんかの描画後、restoreで戻すというセット。

**Comment by kujirahand** [comment]
v3.2.4で基本的な命令を追加したので、とりあえず閉じますね！
有益な報告をありがとうございました。
