### ISSUE TITLE
Webエディタのツールチップからマニュアルを開きたい

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#837]
Webエディタで、命令にマウスオーバーしたときに出るツールチップからマニュアルを開けると嬉しいです。

**Comment by yy0931** [comment]
スマートフォンでの動作をどうするかが問題です。ダブルクリックにするにしても、スマートフォンだと誤動作しそうです。

**Comment by kujirahand** [comment]
ツールチップ内にリンクアイコンとか埋め込めると良いですね？

**Comment by yy0931** [comment]
そうしたいとは思っていたのですが、ace editorにはドキュメンテーション用のホバーの機能が無いため自作する必要があります。

**Comment by kujirahand** [comment]
残念ですねー。これはそこまで必要な機能ではないので一度閉じますね。
