### ISSUE TITLE
オブジェクトのインスタンスメソッドが呼び出せる版が欲しい

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#854]
JS関数実行の、インスタンスメソッドが呼び出せる版が欲しいです。

命令のイメージは以下で、
OBJのMETHODをARGSでJSメソッド実行

OBJ:関数呼び出し時にthisに入るオブジェクト
METHOD:OBJのプロパティで関数なもののプロパティ名(string)または、関数そのもの(function)
ARGS:引数を配列で(JS関数実行と同じ)

多くの場合、このケースで呼び出したい関数はobjの(プロトタイプの)プロパティなので、プロパティ名のみを文字列で渡すのが、利用する際も実装する際も良さそうです（evalを振りかざさなくても良い）

これがあると、pluginで実装せずにJavascriptのほとんどの機能が利用できるようになると思います。

**Comment by kujirahand** [comment]
良いアイデアありがとうございます！実装しました。

**Comment by kujirahand** [comment]
実装し、v3.1.20に反映済みです。
