### ISSUE TITLE
プログラムの行番号を強制変更するオプション

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#880]
通常、プログラムの先頭行が1行目ですが、行番号を強制変更できれば、個別のエディタなどの初期化処理分を処理できて便利かも。

**Comment by yy0931** [comment]
そのためにrun()にpreCode引数を追加していて、preCodeの部分に初期化処理を入れればその分行数を引いて計算してくれます。

**Comment by kujirahand** [comment]
@yy0931  さん、なるほど。素晴らしいです！
