### ISSUE TITLE
テストをtestディレクトリのサブディレクトリ配下へ移動

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#887]
以下のような感じのPRを準備中です。
・テストを./test以下のサブディレクトリに階層移動。
・mochaで動いている./test中、karma可能なものを分離してkarmaでのテストも用意する（流すかどうかは別）
・階層移動の際、module-aliasとwebpackのresolve.aliasを用いて「..地獄」を軽減。
予定）
./test
  -node - 旧./testのなかのkarmaで動かないもの
  -common - 旧./testのなかのmocha/karmaの両方でうごくもの
  -browser - 旧test_browser
  -bundled - 旧test_bundled
  -ace-editor - 旧test_ace-editor

その後の対応で以下を予定しています。
・fetchテストで使っているtestdoubleは「報告する」に置き換え。
・tesstdoubleをsinonに置き換え。
・karmaでのテスト可能なブラウザにIEを追加(testdoubleはIE未対応)。

作業中に気が付いたのが１点。babelでtranspileした環境ではstandaloneにはできません。変換されたファイルはruntimeのヘルパの呼び出しが含まれるため、それらのfunctionをtoStringしたものは、独立して動作できません(corejsやbabelのruntimeが必要)。なので、nodejs用のcnako環境ではstandalone可能で、webpack+babel前提のwnako環境では不可と思われます。可能性は、全esmodule化して、babel無しのwebpackでesmodule出力するだけにとどめれば、動く状態にできるかもしれません。

**Comment by yy0931** [comment]
私の感覚では、../を使ったほうが外部ライブラリとプロジェクト内のファイルの区別が付きやすく、読みやすい気がします。

standaloneはテストがなく壊れたまま放置されていたものを、https://github.com/kujirahand/nadesiko3/commit/fee382d81b0273cc7b775750596e340191fd3227 でとりあえずnode.jsで簡単なプログラムのみ動くように微修正した状態のため、おそらく多くの機能が動きません。どうするか考える必要があります。

**Comment by weyk** [comment]
では、後ほど取り消しておきます。

**Comment by kujirahand** [comment]
あれ？テストも通っていたのでマージしちゃったんですけど大丈夫でした？戻しますか？

**Comment by kujirahand** [comment]
確かに、何か問題があった際、グローバルにインストールしているmochaで頻繁にテストしているので、やはり、../を指定したモジュールの指定が便利と思います。

**Comment by weyk** [comment]
リバートをお願いします。

**Comment by kujirahand** [comment]
@weyk さん、既に @yy0931 さんがかなり手を加えてますし、私もかなり手を加えたので、これを元に作業しませんか？

**Comment by kujirahand** [comment]
現状、ブラウザが不要なテストのみ、エイリアスを使わずパスを ../ に差し替えています。これでglobalにインストールしたmochaで気軽に文法のテストが可能です。

**Comment by kujirahand** [comment]
こちらは移動完了しているので閉じますね。
