### ISSUE TITLE
plugin_testでassertを使わないようにする

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#892]
#873 のWebPack5対応で、plugin_testでassertをrequireしているのが問題になっています。
特にテスト関連の命令が標準でなくても良いので、デフォルトでplugin_testを使わない設定に変更する。

- (1) 現在、asssert モジュールを package.jsonに記述しているので外す
- (2) Node.jsの場合のみ plugin_test を使うようにする

その他、ブラウザ版でmochaによるテストがどうなっているのか、あまり理解していないので調査する。

**Comment by yy0931** [comment]
現在mochaを使わずにテストを実行しています。日本語化することが難しかったことや、it()以外のmochaの機能を使っていなかったためです。assertについては、一致しないときにエラーが飛べば何でもよく、日本語化のためにも自作した方がいいと思います。

---

たとえばこのコードをコンパイルすると、
```
●テスト:足すとは
    1と2を足す
    それと3がASSERT等しい
ここまで

●テスト:引くとは
    1と2を足す
    それと3がASSERT等しい
ここまで
```

以下のコードが出力されます。
```javascript
const __self = this.__self = this;
const __varslist = this.__varslist;
const __module = this.__module;
const __v0 = this.__v0 = this.__varslist[0];
const __v1 = this.__v1 = this.__varslist[1];
const __vars = this.__vars = this.__varslist[2];
__v0["!PluginSystem:初期化"](__self);
__v0["!PluginMath:初期化"](__self);
const __tests = [];
__tests.push({
    name: '足す',
    f: () => {
        (__varslist[2]["それ"] = __varslist[0]["足"](1, 2, __self));;
        (__varslist[2]["それ"] = __varslist[0]["ASSERT等"](__varslist[2]["それ"], 3, __self));;
    }
});;;
__tests.push({
    name: '引く',
    f: () => {
        (__varslist[2]["それ"] = __varslist[0]["足"](1, 2, __self));;
        (__varslist[2]["それ"] = __varslist[0]["ASSERT等"](__varslist[2]["それ"], 3, __self));;
    }
});;;
__self._runTests(__tests);
```

対応するnako_genの部分:
https://github.com/kujirahand/nadesiko3/blob/master/src/nako_gen.js#L265
https://github.com/kujirahand/nadesiko3/blob/master/src/nako_gen.js#L682-L688
https://github.com/kujirahand/nadesiko3/blob/master/src/nako_gen.js#L35-L37

__runTestsはここに定義されていて、loggerにstdoutで結果を送ります。
https://github.com/kujirahand/nadesiko3/blob/master/src/nako_global.js#L58-L79

**Comment by kujirahand** [comment]
おぉ、そうなんですね。すると、ブラウザ版のページのscript要素で、mochaを取り込んでいますが、不要ですね。

**Comment by kujirahand** [comment]
assertを使わないように直しました。
