### ISSUE TITLE
ローカルのテストは通るのにGitHubの自動テストで失敗する

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#904]
ローカルでよくテストしているので問題ないけれど、精神的によくない。
今、テストに50分かかっているとか出てる。。。
コミット時のテストは、簡易版にするなど対策が必要かも。

**Comment by yy0931** [comment]
え11時間前からずっとbuildが走ったままのようですが、無限ループとかかしていませんか？止めたほうが良さそうです
https://github.com/kujirahand/nadesiko3/runs/2228373574?check_suite_focus=true

**Comment by yy0931** [comment]
いや永遠に開始していないだけですね。調べたら他の人も同じ問題に遭遇しているようなので後で確認します。

**Comment by kujirahand** [comment]
項目を探したのですが、停止とか項目がありませんね。。。

**Comment by kujirahand** [comment]
GitHubのバグということで了解です。
閉じます。
