### ISSUE TITLE
WebWorkerのエラー周りの補足強化

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#919]
WebWorkerでの動作を難しくしているのが、エラーを補足できていないことなのですが、
・ブラウザスレッド側のWoker,onerrorから、loggerにエラーを通知する（汎用）
・NAKOワーカーを使っている場合、Worker側にもloggerがいるはずなので、addListenerでerrorを監視して、postMessageでブラウザスレッド側に通知し、ブラウザスレッド側のloggerでエラーを復元して通知する。
のような感じでしょうか？
new Worker()時のunsafeのエラーをどこで補足できるものなのかも、未確認です。
（コンストラクタより前にエラーイベントを監視を設定する？）

loggerに切り替わって以降、いまいちよくわかっていません。

**Comment by kujirahand** [comment]
@yy0931 さん！どうか簡単にloggerの概要を教えてください！

**Comment by yy0931** [comment]
たとえばこれを実行すると、

```javascript
const logger = new NakoLogger()
logger.addListener('info', (data) => { console.log(data) })
logger.info("foo", { line: 1 })
logger.error("foo", { line: 1, file: "foo.nako3" })
```

これがconsole.logで出力されます。errorはinfoより重要度が高いため、addListener('info', ...) でキャッチされます。
```javascript
{
  noColor: '[情報](2行目): foo',
  nodeConsole: '\x1B[1m\x1B[34m[情報]\x1B[0m(2行目): foo\x1B[0m',
  browserConsole: [
    '%c%c[情報]%c(2行目): foo',
    'color: inherit; font-weight: bold;',
    'color: blue; font-weight: bold;',
    'color: inherit; font-weight: inherit;'
  ],
  html: '<div style=""><span></span><span style="color: inherit; font-weight: bold;"></span><span style="color: blue; font-weight: bold;">[情報]</span><span style="color: inherit; font-weight: inherit;">(2行目): foo</span></div>',
  level: 'info',
  position: { line: 1 }
}
{
  noColor: '[エラー]foo.nako3(2行目): foo',
  nodeConsole: '\x1B[1m\x1B[31m[エラー]\x1B[0mfoo.nako3(2行目): foo\x1B[0m',
  browserConsole: [
    '%c%c[エラー]%cfoo.nako3(2行目): foo',
    'color: inherit; font-weight: bold;',
    'color: red; font-weight: bold;',
    'color: inherit; font-weight: inherit;'
  ],
  html: '<div style=""><span></span><span style="color: inherit; font-weight: bold;"></span><span style="color: red; font-weight: bold;">[エラー]</span><span style="color: inherit; font-weight: inherit;">foo.nako3(2行目): foo</span></div>',
  level: 'error',
  position: { line: 1, file: 'foo.nako3' }
}
```

**Comment by yy0931** [comment]
cnakoの場合は https://github.com/kujirahand/nadesiko3/blob/master/src/cnako3.js#L74-L79 、ウェブの場合は https://github.com/kujirahand/nadesiko3/blob/master/src/wnako3_editor.js#L1578 で表示しています。

NakoColors.color の要素をテキストに埋め込むことで、色の付いた出力も表示できます。
使い方は https://github.com/kujirahand/nadesiko3/blob/master/src/nako_global.js#L59-L78 を参照してください。https://github.com/kujirahand/nadesiko3/blob/master/src/nako_logger.js#L75 で埋め込まれた色の情報をhtmlやnodeのエスケープコードに変換しています。
