### ISSUE TITLE
「ここまで」「💧」をもっと簡単に表現したい

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#925]
より簡単に表現できる方法を議論したいです。
なでしこ3になって「ここまで」にだいぶ慣れたのですが、もっと簡単に書きたい感じがあります。

# これまでにやったこと

 - 「ここまで」の代わりに「💧」と書いても良くした・・・「💧」も良いのですが、、、「しずく」とタイプするなら「ここまで」とタイプするのとそれほど変わらない感じがしています。
 - 「!ここまでだるい」構文を実装した #596 でインデント構文を復活させていますが、個人的にはあまり使っていないです。

**Comment by kujirahand** [comment]
簡単なアイデアとして、「。。。」と3回句点を打ったら、ここまでと同じというのは良いかな？とも思っています。
日本語でも、確かに。。。と書くこともあるので。

**Comment by kujirahand** [comment]
少し複雑になりますが、
Python風にして行末尾に「：」をつけたら、そこだけインデント構文にするとか。

**Comment by kujirahand** [comment]
母音３回が打ちやすいので「おおお」を「ここまで」と同じにしてしまうとか。

```
１００回
　　「お」を表示。
おおお。
```

**Comment by kujirahand** [comment]
そういえば、昨今の「了解」を「りょ」と書く文化に鑑みて、「ここまで」を「こ。」と書くことにするのはどうでしょうか。

```
１００回
　　「お」を表示。
こ。
```

**Comment by kujirahand** [comment]
C言語/Java風に、ブロックを｛・・・｝で表現できるようにするのもありかも？

**Comment by kujirahand** [comment]
「＠」はどうでしょうか？？？IMEで打ちやすいし、なんかループ最初に戻るような気にもなります。

```
１００回
　　「お」を表示。
＠
```

**Comment by kujirahand** [comment]
普通に「END」でも良いかも

```
１００回
　　「お」を表示。
END。
```
これなら「ここまで」とそう変わらないかも。

**Comment by kujirahand** [comment]
他には、「以上」もいいかも。「以上」関数はあるものの、単体で使ったら「ここまで」と同じ意味にする感じです。

```
１００回
　　「お」を表示。
以上。
```

他には「拝啓」「敬具」の組み合わせは面白いかもです。便利というよりは・・・、面白いの機能ですが。。。

```
拝啓、１００回
　　「お世話になります」を表示。
敬具
```

**Comment by kujirahand** [comment]
「。。。」はいまいちだけど、「！！！」なら許せる感じがしませんか？

```
１００回
　　「お」を表示。
！！！
```

**Comment by kujirahand** [comment]
「💧」よりも「🔃」（読み：とけいまわり）のほうが良かったのでは感。

```
１００回
　　「お」を表示。
🔃
```

いや、💧の方が美しいと思いました。

**Comment by kujirahand** [comment]
締切の「〆」はどうでしょうか？

```
10回
　　「こんにちは」と表示。
〆
```

良いけど結局変換作業が必要になるので、あまりうれしくないかも。

**Comment by kujirahand** [comment]
「イエーイ」はどうでしょうか。

```
10回
　　「こんにちは」と表示。
イエーイ
```
ノリノリですね。かなり高感度高いです。

**Comment by kujirahand** [comment]
「🌈」はどうでしょうか。

```
10回
　　「こんにちは」と表示。
🌈
```

「🌈」も良いですが「💧」の方が美しいです。

**Comment by kujirahand** [comment]
「ｗｗｗ」はどうでしょうか。

```
10回
　　「こんにちは」と表示。
ｗｗｗ
```

こちらも高感度高いですｗｗｗ

**Comment by snowdrops89** [comment]
現実的な利便性を考えるなら、「@」案のように、スマホでもPCでも変換なく打てる一般的な記号が良いと思います。
@は他の記号と比べても、PCでもシフトキーを伴わないのが良いですね。
「www」も打ちやすいっちゃ打ちやすいwww
わたしは、「こ」と打ったら「ここまで。」になるから、ベツにここまでだるくないですけれどねwww

**Comment by eznavi** [comment]
個人的には、「。」「💨」ですね。
個人的には、②のように語尾の最後に３文字同じ文字並んだら、
ここまでと同じだと見た目ですがすっきりするかなっとも思いました。

①
10回
　　「なでしこ」と表示
　　「こんにちは」と表示。
💨💨💨

②
10回
　　「なでしこ」と表示
　　「こんにちは」と表示💨💨💨
（ここまで記載なし）

**Comment by eznavi** [comment]
個人的には、「。」「💨」が好きですね。

②のように語尾の最後に３文字同じ文字並んだら、
ここまでと同じだと見た目ですがすっきりするかなっとも思いました。

①
10回
　　「こんにちは」と表示。
💨💨💨

②
10回
　　「こんにちは」と表示。💨💨💨

**Comment by kujirahand** [comment]
ご意見、ありがとうございました！
試験的に、「＠」を「💧」の代わりに使う方法と
「。。。」で「ここまで」を表す方法を取り入れてみます。

ちなみに「💨」はどうやったら出て来ますか？
絵文字の欠点は読み方を新たに覚えないといけないという点ですね😆ｗｗｗ

**Comment by eznavi** [comment]
ご苦労様です😉
確かに絵文字は覚えるのに時間がかかりますね。
※「ダッシュ」で「💨」になります。

ちなみに白と黒を基本とした絵文字が、文字に対して違和感がないのかなっと思い「💨」はTwitterなどで意識して使っています。

**Comment by kujirahand** [comment]
とりあえず、「。。。」を追加したので、今回は閉じます。
しばらく様子を見て、まだダルいようなら、また考えましょう！😃
