### ISSUE TITLE
全角半角問題を解決しよう

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#94]
今回、前処理なしに、PEGJSにソースコードを流し込んでいるので、
全角・半角を両方PEG側で処理しないといけません。

そのせいで、今頃になって、マイナス記号でエラーが出るという
イージーミスがありました。

ほかにも、全角・半角文字の違いでエラーが出るといけないので、
念のため、テストを作ると、良いと思います。

**Comment by massongit** [comment]
以下のような手順を行うことで、全角と半角、どちらかのみを定義すればいいようにする、というのはNGなのでしょうか？
1. コードの文字列以外の箇所で半角に変換できる部分は全て半角に変換する (あるいは文字列以外の箇所を全て全角に変換する)
2. 変換したコードをPEGJSに流し込む

**Comment by kujirahand** [comment]
PEGJSの威力を最大限活かそうと頑張ったのですが、やはり、おっしゃるように、PEGJSに流し込む前に、前処理をした方が、安全ですよね。
