### ISSUE TITLE
インデント構文で「違えばもし」がエラーになるようです

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3#940]
**質問掲示板からの転載**
> https://www.eznavi.net/site/bbs/index2.php?pagetop=1030

**再現方法:**
```
！インデント構文
Aは2
もしAが1ならば
　　Aを表示
違えばもしAが2ならば
　　Aを表示
違えば
　　Aを表示
```
**エラー:**
```
[文法エラー]main.nako3(5行目):　構文解析でエラー。『違えば』の使い方が間違っています。
```

それで質問者様は「違えばもし」は無かったと思われたみたいですが、普通に「ここまで」を使って書いた場合は問題ないものでした。

**Comment by kujirahand** [comment]
インデント構文で「違えばもし」が考慮されていませんでした。
修正しました。

**Comment by kujirahand** [comment]
修正済みなので、閉じます。
@snowdrops89  ご報告ありがとうございました！感謝😀
