### ISSUE TITLE
「画像描画」を「画像部分描画」に分割する

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#941]
画像描画の使い方が複雑なので、機能を分割したら分かりやすくなると思います。
また、画像を読み込む命令も必要かも。

**Comment by kujirahand** [comment]
よく見たらよくできた命令でした。マニュアルを分かりやすくします。

**Comment by kujirahand** [comment]
「画像描画」が分かりづらい理由が引数の助詞でした。
同じ助詞が被ると使いづらい原因になります。
そこで、「画像描画」→「画像拡大描画」と名前を変更し以下のように仕様変更したいと思います。

# 画像拡大描画

画像IMGの、元画像の座標[sx, sy, sw, sh]から描画先座標[dx, dy, dw, dh]へ描画し、Imageオブジェクトを返す

```
    type: 'func',
    josi: [['の', 'を'], ['から'], ['へ', 'に']],
    pure: true,
```

**Comment by snowdrops89** [comment]
拡大・・・ではないような・・・？
dw,dhの価を小さく取れば、縮小もできるので・・・
むしろ、「画像部分描画」のほうが妥当な気がするのですが。

**Comment by kujirahand** [comment]
@snowdrops89  確かに。変更しますね。

**Comment by kujirahand** [comment]
マニュアルも一応書いたので閉じます。
https://nadesi.com/v3/doc/index.php?plugin_browser%2F%E7%94%BB%E5%83%8F%E6%8F%8F%E7%94%BB&show
