### ISSUE TITLE
指定element起点のquerySelector系の命令

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#947]
りばーしのオプション選択画面を実装していて気が付いたのですが、
DOMを取得する命令で、指定エレメントを基準とするものがないようです。
今ある
document.getElementsTagName/getElementById
document.querySelector/All
ないっぽい
element.getElementsTagName
element.querySelector/All

命令の名前はちょっと悩ましい感じがします。既存のdocumentを起点にした命令に、
オプショナルとなる助詞を追加してelementを受け取るのがよさそう？
命令の定義の変化により解析時に引数の紐づけ方が変わる可能性があるのがちょっと怖いかも。

**Comment by kujirahand** [comment]
確かに！！
「elementのqueryをDOM子要素取得」命令を追加しますね。

**Comment by kujirahand** [comment]
とりあえず追加しました！
