### ISSUE TITLE
取り込まれたかトップレベルか判定する方法が欲しい

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#956]
たぶん、pythonを使用したことがあると伝わると思うのですが、
「if __name__ == '__main__'」の判定ができる機能です。

今、実行されているのが、トップレベルなのか、「取り込む」等によりライブラリ的な用途でとりこまれて実行されているのかが解る方法が欲しいです。

用途・使い道としては、
・そのまま実行すると、ライブラリのサンプル動作になる。
・取り込むとライブラリとして使えて、サンプル動作は行わない。
ということができたら便利かなと。

貯蔵庫でいうと、トランプ画像作成とか、迷路作成とかがこの形式で動くようになったら便利かなと。

**Comment by kujirahand** [comment]
Pythonの__name__に対応するもの、日本語では何が良いでしょうか。
「プラグイン名」とかが自然でしょうか。

**Comment by weyk** [comment]
もしくは、目的に絞って、メインかメインではないかを返すだけの機能に絞るか　のいずれかと思っています。
もし、１つのhtmlに複数のなでしこのソースのscriptタグ亞あった場合は、両方がメインの判定で良いかと思っています（「取り込む」で取り込まれてはいないから）
例えば、サーバがnako3storageのようなcgiだった場合、取り込む際のURLから名前として人いだすのは困難かもしれません。
取り込まれる側が、なにか名前を名乗るような仕組みがあるとそれはそれで便利そうですが。

**Comment by kujirahand** [comment]
単純に定数「プラグイン名」をグローバルに領域に配置して、これを参照できるようにしましょう。この定数名を変更する命令も用意しましょう。

初期値では、「プラグイン名」を「メイン」にしておいて、『取り込む』とそのプラグイン名になるという感じで。

**Comment by kujirahand** [comment]
v3.2.6で追加したので閉じますね。

**Comment by kujirahand** [comment]
> なでしこ３の、「プラグイン名」のグローバル変数、自身が読み込まれた場合以外にも、ほかのプラグインを読み込んんだ場合もそのプラグイン名残っちゃう --- https://twitter.com/weykt/status/1400986872671727617

とのこと。確認する。

**Comment by kujirahand** [comment]
コミットログに書きそびれたのですが、609824f774d0f9aba5da27d77b7f8fac78f7204b で修正しました。

**Comment by kujirahand** [comment]
#1112 の修正で、プラグイン名が、取り込んだファイルでなくパスを抜いたファイル名になることをメモ。
