### ISSUE TITLE
未定義のプロパティもしくは取得した値がundefinedとなるプロパティ参照の検出と警告

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3#963]
"undefined"な変数へのアクセスの検出の亜種です。

hoge["fuga"]形式のプロパティへのアクセスについても、検出ができると助かります。
ただ、性能へ影響しそうである（毎アクセス毎にチェックが走るため）ため、
・デバッグオプション的なもので有効にしたらチェックする。
・高速化オプションに無効にするオプションを追加して、既定はオンにする。
いずれかなのですが、今まで、ほぼ、Javascriptそのものな速度の部分に、チェックロジックが入る（多段ならば、多段分）ことになるため、後者では厳しいかなという印象です。
結構、送り仮名の差異等、はまりやすく、見つけずらい部分と思っています。

**Comment by kujirahand** [comment]
やはりオプションで不正なプロパティアクセスに対する警告できるようにすると良いでしょうね。
