### ISSUE TITLE
なでしこがElectron上で動くパックを作る

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#98]
- Electronでなでしこが動くようにする
- Win/Mac/Linuxごとのパックを用意する

**Comment by massongit** [comment]
こちらの記事が参考になりそうです → http://qiita.com/Quramy/items/a4be32769366cfe55778

**Comment by kujirahand** [comment]
@massongit 素晴らしいコミットありがとうございました！

将来的なプランとして、なでしこv1と同じように、ユーザーの作ったプログラムを簡単にパックして、配布できる開発環境を用意できると良いですよね。

初心者ユーザーだと、Node.jsのインストールとコマンドラインによるライブラリインストールすらハードルが高いと思いますので・・・っと、これは、Electron対応を超えたIssueなので、新たにIssueを立ち上げます。

**Comment by kujirahand** [comment]
当面の目的を果たしたので、こちらは閉じます。
