### ISSUE TITLE
ミリ秒単位の時間差を得る方法がない

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nadesiko3#997]
ストップウォッチを作ろうと思って、ふと気付いた・・・

**Comment by weyk** [comment]
参考。

https://developer.mozilla.org/ja/docs/Web/API/Performance/now

命令はあるものの、わざと精度が落とされてしまうので、精度の高いタイマを得るのは難しいです。
（chromeはユーザ保護などどこ吹く風で良い精度が返ってきます）
requestAnimationFrameのcallback時の引数もこの値です。
また、PRで止まってますが、パフォーマンス測定もこの機能です。

とはいっても、欲しい機能ではあるので、精度を得る命令とセットで実装してユーザに判断してもらうしかなさそうです。
あとは、２回値を取って差を求めることには意味がありますが、単発の値そのものにはあまり意味がないので、
「何を得る命令」として定義するかでしょうか。

**Comment by kujirahand** [comment]
PRのパフォーマンス測定、どうやって取り込んだら良いのか分からず止まっていてすみません。[review]のボタンを押すと、取り込めるんですね。。。長らくそのままですみませんでした。

**Comment by kujirahand** [comment]
とりあえず、『時間ミリ秒取得』命令を追加しました。

**Comment by kujirahand** [comment]
追加したので閉じますね。ありがとうございました！
